"""
Django Management Command to Map Legacy Tables to Django Models
Creates model definitions for imported legacy tables
"""

import os
from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Map legacy database tables and generate Django model code'

    def add_arguments(self, parser):
        parser.add_argument(
            '--output',
            type=str,
            default='hospital/models_legacy_generated.py',
            help='Output file for generated models'
        )
        parser.add_argument(
            '--tables',
            nargs='+',
            help='Specific tables to map'
        )
        parser.add_argument(
            '--category',
            type=str,
            choices=['blood', 'admission', 'lab', 'pharmacy', 'insurance', 'accounting', 'all'],
            default='all',
            help='Category of tables to map'
        )

    def handle(self, *args, **options):
        output_file = options['output']
        specific_tables = options.get('tables')
        category = options['category']

        self.stdout.write(self.style.SUCCESS('Analyzing legacy database tables...'))

        # Get all tables
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT name FROM sqlite_master 
                WHERE type='table' 
                AND name NOT LIKE 'sqlite_%'
                AND name NOT LIKE 'django_%'
                AND name NOT LIKE 'auth_%'
                ORDER BY name
            """)
            all_tables = [row[0] for row in cursor.fetchall()]

        self.stdout.write(f'Found {len(all_tables)} legacy tables')

        # Filter tables based on criteria
        tables_to_map = self.filter_tables(all_tables, specific_tables, category)
        
        if not tables_to_map:
            self.stdout.write(self.style.WARNING('No tables found matching criteria'))
            return

        self.stdout.write(f'Will map {len(tables_to_map)} tables')

        # Generate model code
        model_code = self.generate_models(tables_to_map)

        # Write to file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(model_code)

        self.stdout.write(self.style.SUCCESS(f'\n✓ Models generated: {output_file}'))
        self.stdout.write('\nNext steps:')
        self.stdout.write('1. Review the generated models')
        self.stdout.write('2. Add to INSTALLED_APPS if needed')
        self.stdout.write('3. Run: python manage.py makemigrations')
        self.stdout.write('4. Run: python manage.py migrate')

    def filter_tables(self, all_tables, specific_tables, category):
        """Filter tables based on criteria"""
        if specific_tables:
            return [t for t in all_tables if t in specific_tables]

        if category == 'all':
            return all_tables

        # Category prefixes
        category_prefixes = {
            'blood': ['blood_'],
            'admission': ['admission_', 'admissions'],
            'lab': ['lab_', 'procedure_'],
            'pharmacy': ['drug_', 'drugs', 'prescriptions'],
            'insurance': ['insurance_', 'claim_'],
            'accounting': ['acc_', 'accounts'],
        }

        prefixes = category_prefixes.get(category, [])
        filtered = []
        for table in all_tables:
            for prefix in prefixes:
                if table.startswith(prefix) or table == prefix.rstrip('_'):
                    filtered.append(table)
                    break

        return filtered

    def generate_models(self, tables):
        """Generate Django model code for tables"""
        code_parts = []
        
        # Header
        code_parts.append('"""')
        code_parts.append('Auto-generated Django models for legacy database tables')
        code_parts.append('Generated by: python manage.py map_legacy_tables')
        code_parts.append('"""')
        code_parts.append('')
        code_parts.append('from django.db import models')
        code_parts.append('from django.utils import timezone')
        code_parts.append('')
        code_parts.append('')

        # Generate each model
        for table_name in tables:
            model_code = self.generate_single_model(table_name)
            code_parts.append(model_code)
            code_parts.append('')

        return '\n'.join(code_parts)

    def generate_single_model(self, table_name):
        """Generate code for a single model"""
        with connection.cursor() as cursor:
            # Get table info
            cursor.execute(f'PRAGMA table_info("{table_name}")')
            columns = cursor.fetchall()

        # Generate class name
        class_name = self.table_to_class_name(table_name)

        lines = []
        lines.append(f'class {class_name}(models.Model):')
        lines.append(f'    """Legacy table: {table_name}"""')
        lines.append('')

        # Generate fields
        for col in columns:
            cid, name, type_, notnull, dflt_value, pk = col
            field_def = self.column_to_field(name, type_, notnull, dflt_value, pk)
            lines.append(f'    {field_def}')

        lines.append('')
        lines.append('    class Meta:')
        lines.append('        db_table = f"{table_name}"')
        lines.append(f'        verbose_name = "{class_name}"')
        lines.append(f'        verbose_name_plural = "{class_name}s"')
        lines.append('        managed = False  # Don\'t let Django manage this table')
        lines.append('')
        lines.append('    def __str__(self):')
        
        # Smart __str__ method
        if 'name' in [col[1] for col in columns]:
            lines.append('        return str(self.name)')
        elif 'id' in [col[1] for col in columns]:
            lines.append(f'        return f"{class_name} {{self.id}}"')
        else:
            lines.append('        return f"{class_name} object"')

        return '\n'.join(lines)

    def table_to_class_name(self, table_name):
        """Convert table name to PascalCase class name"""
        # Remove prefixes for cleaner names
        name = table_name
        for prefix in ['acc_', 'admission_', 'form_', 'insurance_', 'lab_']:
            if name.startswith(prefix):
                name = name[len(prefix):]
                break

        # Convert to PascalCase
        parts = name.split('_')
        return ''.join(word.capitalize() for word in parts)

    def column_to_field(self, name, type_, notnull, dflt_value, pk):
        """Convert SQLite column to Django field"""
        field_type = 'models.CharField'
        field_args = []
        field_kwargs = {}

        # Map SQLite types to Django fields
        type_lower = type_.lower()
        
        if pk:
            return f'{name} = models.AutoField(primary_key=True)'
        
        if 'int' in type_lower:
            field_type = 'models.IntegerField'
        elif 'real' in type_lower or 'double' in type_lower or 'float' in type_lower:
            field_type = 'models.FloatField'
        elif 'decimal' in type_lower:
            field_type = 'models.DecimalField'
            field_kwargs['max_digits'] = 12
            field_kwargs['decimal_places'] = 2
        elif 'text' in type_lower:
            if 'long' in type_lower or 'medium' in type_lower:
                field_type = 'models.TextField'
            else:
                field_type = 'models.TextField'
        elif 'blob' in type_lower:
            field_type = 'models.BinaryField'
        elif 'date' in type_lower or 'time' in type_lower:
            field_type = 'models.DateTimeField'
        elif 'bool' in type_lower:
            field_type = 'models.BooleanField'
        else:
            # Default to CharField
            field_kwargs['max_length'] = 255

        # Add null/blank
        if not notnull:
            field_kwargs['null'] = 'True'
            field_kwargs['blank'] = 'True'

        # Add default
        if dflt_value and dflt_value not in ('NULL', 'CURRENT_TIMESTAMP'):
            field_kwargs['default'] = dflt_value

        # Build field definition
        kwargs_str = ', '.join(f'{k}={v}' for k, v in field_kwargs.items())
        return f'{name} = {field_type}({kwargs_str})'


class Command(BaseCommand):
    help = 'Generate Django models from legacy tables'
    # ... (keep all the existing code above)




















