"""
Management command to sync existing PharmacyStock to InventoryItem
"""
from django.core.management.base import BaseCommand
from django.db.models import Sum, F
from hospital.models import PharmacyStock, Drug
from hospital.models_procurement import Store, InventoryItem, InventoryCategory


class Command(BaseCommand):
    help = 'Sync all PharmacyStock items to InventoryItem for unified inventory tracking'

    def handle(self, *args, **options):
        self.stdout.write('Starting pharmacy stock to inventory sync...')
        
        # Find or create pharmacy store
        pharmacy_store = Store.objects.filter(
            store_type='pharmacy',
            name__icontains='pharmacy'
        ).first()
        
        if not pharmacy_store:
            from hospital.models import Department
            pharmacy_dept = Department.objects.filter(name__icontains='pharmacy').first()
            pharmacy_store = Store.objects.create(
                name='Pharmacy Store',
                code='PHARM',
                store_type='pharmacy',
                department=pharmacy_dept,
                is_active=True
            )
            self.stdout.write(self.style.SUCCESS(f'Created pharmacy store: {pharmacy_store.name}'))
        else:
            self.stdout.write(f'Using existing pharmacy store: {pharmacy_store.name}')
        
        # Get or create pharmacy category
        pharmacy_category = InventoryCategory.objects.filter(
            is_for_pharmacy=True,
            is_active=True
        ).first()
        
        if not pharmacy_category:
            pharmacy_category = InventoryCategory.objects.create(
                name='Pharmacy / Pharmaceuticals',
                code='PHARM',
                is_for_pharmacy=True,
                display_order=1,
                is_active=True,
                description='Pharmaceuticals, drugs, and medications'
            )
            self.stdout.write(self.style.SUCCESS(f'Created pharmacy category: {pharmacy_category.name}'))
        else:
            self.stdout.write(f'Using existing pharmacy category: {pharmacy_category.name}')
        
        # Get all active drugs that have pharmacy stock
        drugs_with_stock = Drug.objects.filter(
            is_active=True,
            stock__is_deleted=False
        ).distinct()
        
        synced_count = 0
        created_count = 0
        updated_count = 0
        
        for drug in drugs_with_stock:
            # Get all pharmacy stock batches for this drug
            pharmacy_stocks = PharmacyStock.objects.filter(
                drug=drug,
                is_deleted=False
            )
            
            if not pharmacy_stocks.exists():
                continue
            
            # Aggregate quantities and costs
            stock_summary = pharmacy_stocks.aggregate(
                total_quantity=Sum('quantity_on_hand'),
                total_cost=Sum(F('quantity_on_hand') * F('unit_cost'))
            )
            
            total_quantity = stock_summary['total_quantity'] or 0
            total_cost = stock_summary['total_cost'] or 0
            avg_cost = total_cost / total_quantity if total_quantity > 0 else 0
            
            # Get reorder level from latest stock entry
            latest_stock = pharmacy_stocks.order_by('-created').first()
            reorder_level = latest_stock.reorder_level if latest_stock else 0
            
            # Get or create inventory item (item_code will be auto-generated)
            inventory_item, created = InventoryItem.objects.get_or_create(
                store=pharmacy_store,
                drug=drug,
                defaults={
                    'category': pharmacy_category,
                    'item_name': f"{drug.name} {drug.strength} {drug.form}",
                    'item_code': '',  # Will be auto-generated by save() method
                    'description': f"{drug.name} - {drug.generic_name or ''}",
                    'quantity_on_hand': total_quantity,
                    'reorder_level': reorder_level,
                    'unit_cost': avg_cost,
                    'unit_of_measure': drug.form or 'units',
                    'is_active': True
                }
            )
            
            # Ensure codes are generated for new items
            if created and (not inventory_item.item_code or inventory_item.item_code.strip() == ''):
                inventory_item.save()  # Trigger auto-generation
            
            if created:
                created_count += 1
                self.stdout.write(f'  Created inventory item for: {drug.name}')
            else:
                # Update existing item
                inventory_item.category = pharmacy_category  # Ensure category is set
                inventory_item.quantity_on_hand = total_quantity
                inventory_item.unit_cost = avg_cost
                inventory_item.reorder_level = reorder_level
                inventory_item.save()
                updated_count += 1
                self.stdout.write(f'  Updated inventory item for: {drug.name}')
            
            synced_count += 1
        
        self.stdout.write(self.style.SUCCESS(
            f'\nSync completed!'
            f'\n  Total drugs synced: {synced_count}'
            f'\n  Created: {created_count}'
            f'\n  Updated: {updated_count}'
        ))

