"""
Django settings for hms project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys

# Fix for Windows colorama OSError: [Errno 22] Invalid argument
# This must be done before any other imports that might use colorama
if sys.platform == 'win32':
    # Disable colorama completely by monkey-patching before import
    try:
        # Prevent colorama from auto-initializing
        os.environ.setdefault('COLORAMA_DISABLE_AUTOWRAP', '1')
        os.environ.setdefault('FORCE_COLOR', '0')
        
        # Import and patch colorama's write_plain_text to handle errors gracefully
        try:
            import colorama
            # Disable wrapping completely
            try:
                colorama.init(strip=False, convert=False, wrap=False)
            except (OSError, AttributeError):
                pass
            
            # Monkey-patch the write_plain_text method to catch OSError
            try:
                from colorama.ansitowin32 import StreamWrapper
                original_write_plain_text = StreamWrapper.write_plain_text
                
                def safe_write_plain_text(self, text):
                    try:
                        return original_write_plain_text(self, text)
                    except OSError:
                        # If write fails, try writing directly to the wrapped stream
                        try:
                            if hasattr(self, 'wrapped') and self.wrapped:
                                self.wrapped.write(text)
                                self.wrapped.flush()
                        except (OSError, AttributeError):
                            # If that also fails, silently ignore
                            pass
                
                StreamWrapper.write_plain_text = safe_write_plain_text
            except (ImportError, AttributeError):
                # If patching fails, at least we disabled initialization
                pass
        except ImportError:
            # colorama not installed, no problem
            pass
    except Exception:
        # If anything fails, continue anyway
        pass

from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='e77uf3k0c3!53--4jid)7%08=n(8vf)^)#utg-aq+590i%*qq0')

# SECURITY WARNING: don't run with debug turned on in production!
# Production MUST set DEBUG=False in .env. When DEBUG is True: cached template
# loaders are disabled, APP_DIRS template discovery is slower, WhiteNoise static
# cache is 0, and security checks are relaxed.
DEBUG = config('DEBUG', default=True, cast=bool)

# Allow all hosts in DEBUG mode, or use configured hosts in production
# For Docker/network access, include local network IPs
# In production, ALLOWED_HOSTS must be explicitly set via environment variable
if DEBUG:
    # In DEBUG mode, allow common development hosts and IP addresses
    # Include all common local network IPs for easier access from other devices
    default_hosts = 'localhost,127.0.0.1,0.0.0.0,192.168.2.97,192.168.2.216,192.168.233.1,192.168.64.1,172.20.112.1,192.168.1.1,192.168.0.1,192.168.0.105,10.0.0.1,10.132.245.143'
else:
    # In production, require explicit ALLOWED_HOSTS configuration
    # Default to localhost only if not set (will fail in production - user must configure)
    default_hosts = config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
    # Warn if using default in production
    if default_hosts == 'localhost,127.0.0.1':
        import warnings
        warnings.warn(
            "⚠️ WARNING: Using default ALLOWED_HOSTS in production. "
            "Please set ALLOWED_HOSTS environment variable with your domain(s).",
            UserWarning
        )

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=default_hosts, cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# Django validates the Host header, but doesn't include port numbers
# So '192.168.2.97:8000' is validated as '192.168.2.97'
# In DEBUG mode, we need to ensure IP addresses work properly
if DEBUG:
    # Add common local IPs if not already present
    # Also add common private network ranges for easier network access
    common_hosts = [
        '192.168.2.97', '192.168.2.216', '127.0.0.1', 'localhost', '0.0.0.0',
        '192.168.233.1', '192.168.64.1', '172.20.112.1',
        '192.168.1.1', '192.168.0.1', '192.168.0.105', '10.0.0.1', '10.132.245.143'
    ]
    for host in common_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
    
    # In DEBUG mode, be more permissive - allow any 192.168.x.x, 10.x.x.x, 172.16-31.x.x
    # This is a workaround for network access - in production, specify exact hosts
    import re
    def is_local_ip(host):
        """Check if host is a local/private IP address"""
        if not host or host in ['localhost', '127.0.0.1', '0.0.0.0']:
            return True
        # Match private IP ranges: 192.168.x.x, 10.x.x.x, 172.16-31.x.x
        private_ip_pattern = r'^(192\.168\.|10\.|172\.(1[6-9]|2[0-9]|3[0-1])\.)'
        return bool(re.match(private_ip_pattern, host))
    
    # Note: We can't use wildcards, but we allow common private IP ranges above


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'guardian',
    'rest_framework_simplejwt',
    'django_celery_beat',
    'django_celery_results',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_bootstrap5',
    'django_tables2',
    'widget_tweaks',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    # 'django_ratelimit',  # Temporarily disabled - requires Redis/shared cache backend
    # 'auditlog',  # Temporarily disabled due to import issues
    'simple_history',
    'model_utils',
    # 'uuidfield',  # Temporarily disabled - incompatible with Django 4.2
    'django_extensions',
    'import_export',
    'storages',
    'health_check',
    'health_check.db',
    'health_check.cache',
    'health_check.storage',
    'django_prometheus',
    
    # Debug tools (only in development) - DISABLED for performance
    # 'debug_toolbar',  # Disabled for performance
    # 'silk',  # Disabled for performance
    
    # HMS Apps
    'hospital',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'hms.middleware.PermissiveHostMiddleware',  # Allow private IPs in DEBUG mode
    'hospital.middleware_autosave.AutoSaveMiddleware',  # Auto-save support
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'hospital.middleware_validation_error.ValidationErrorJSONMiddleware',  # Return safe JSON on ValidationError (e.g. invalid UUID)
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Must come before BulkCreationMonitorMiddleware
    'hospital.middleware_finance_admin_access.FinanceAccountAdminAccessMiddleware',  # Grant finance/account users admin access (is_staff) so they are not asked to log in again
    'hospital.middleware_bulk_creation_monitor.BulkCreationMonitorMiddleware',  # Monitor and prevent bulk creation (after AuthenticationMiddleware)
    'django.contrib.messages.middleware.MessageMiddleware',  # Must come after SessionMiddleware and AuthenticationMiddleware
    'hospital.middleware_session_timeout.SessionTimeoutMiddleware',  # Auto-logout after 2 hours idle
    'hospital.middleware_audit.AuditMiddleware',  # Audit logging for compliance
    # 'hospital.middleware_accountant_restriction.AccountantRestrictionMiddleware',  # DISABLED: Restrict accountants to accounting features only - temporarily disabled to restore app access
    # 'hospital.middleware_hr_restriction.HRRestrictionMiddleware',  # DISABLED: Restrict HR staff to HR features only - temporarily disabled to restore app access
    'hospital.middleware_midwife_restriction.MidwifeRestrictionMiddleware',  # Block midwives from finance/lab/pharmacy; allow nurse-equivalent clinical paths
    'allauth.account.middleware.AccountMiddleware',  # Required by allauth
    # 'django_otp.middleware.OTPMiddleware',  # Disabled for performance
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'auditlog.middleware.AuditlogMiddleware',  # Temporarily disabled
    'simple_history.middleware.HistoryRequestMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    
    # Debug tools (only in development) - DISABLED for performance
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',  # Disabled for performance
    # 'silk.middleware.SilkyMiddleware',  # Disabled for performance
]

ROOT_URLCONF = 'hms.urls'

# Custom error handlers
handler404 = 'hms.views.handler404'
handler500 = 'hms.views.handler500'
handler403 = 'hms.views.handler403'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Keep project templates in `hms/templates/`, and also allow templates
        # to be resolved directly from `hospital/templates/` (useful for shared
        # deployments and avoids surprises when APP_DIRS is toggled).
        'DIRS': [
            BASE_DIR / 'hms' / 'templates',
            BASE_DIR / 'hospital' / 'templates',
        ],
        # In DEBUG, do NOT use cached template loaders—otherwise missing-template
        # errors can be cached and persist until restart.
        'APP_DIRS': True if DEBUG else False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'hospital.context_processors.global_csrf_token',
                'hospital.context_processors.staff_activity_reminders',
            ],
            # Performance optimizations
            'debug': DEBUG,
            'string_if_invalid': '',  # Never use 'INVALID' - it was breaking store transfer (UUID validation). Use '' so bad vars are empty.
            'autoescape': True,
        },
    },
]

# Use CACHED loaders for MUCH better performance in production.
# Important: Keep this OUT of DEBUG to avoid caching template misses while developing.
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]

WSGI_APPLICATION = 'hms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ==============================================================================
# SINGLE POSTGRESQL DATABASE - USED BY ALL SERVICES
# ==============================================================================
# This ensures Docker Desktop, Cursor server, and all services use the SAME database
# Database URL is defined in .env file (single source of truth)
# Docker services override hostname to 'db' instead of 'localhost'
# ==============================================================================

# Single PostgreSQL Database URL - Read from .env file
# Format: postgresql://USER:PASSWORD@HOST:PORT/DATABASE
# - Local/Cursor: postgresql://hms_user:hms_password@localhost:5432/hms_db
# - Docker: postgresql://hms_user:hms_password@db:5432/hms_db (auto-overridden in docker-compose.yml)
DATABASE_URL = config('DATABASE_URL', default='postgresql://hms_user:hms_password@localhost:5432/hms_db')

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=config('DATABASE_CONN_MAX_AGE', default=600, cast=int),  # Connection pooling - keep connections for 10 min
        conn_health_checks=config('DATABASE_CONN_HEALTH_CHECKS', default=True, cast=bool),  # Check connection health before using
    )
}

# Server deployment: Ensure database connection settings are robust
if not DEBUG:
    # Production database settings - more robust connection handling
    DATABASES['default']['CONN_MAX_AGE'] = 600  # Keep connections alive for 10 minutes
    DATABASES['default']['OPTIONS'] = DATABASES['default'].get('OPTIONS', {})
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': 30,  # 30 second connection timeout
        'options': '-c statement_timeout=30000',  # 30 second query timeout
    })

# Database-Specific Optimizations
db_engine = DATABASES['default'].get('ENGINE', '')

# PostgreSQL Performance Optimizations (Local or Remote)
if db_engine == 'django.db.backends.postgresql':
    DATABASES['default'].setdefault('OPTIONS', {})
    
    # Base options for all PostgreSQL connections - OPTIMIZED FOR PERFORMANCE
    base_options = {
        'connect_timeout': config('DATABASE_TIMEOUT', default=10, cast=int),
        'options': '-c statement_timeout=30000 -c work_mem=16MB',  # Optimized query settings (shared_buffers requires server restart, set in postgresql.conf)
        'keepalives': 1,
        'keepalives_idle': 30,
        'keepalives_interval': 10,
        'keepalives_count': 5,
    }
    
    # Add SSL support for remote database connections
    ssl_mode = config('DATABASE_SSL_MODE', default='prefer')  # disable, allow, prefer, require, verify-ca, verify-full
    if ssl_mode and ssl_mode != 'disable':
        base_options['sslmode'] = ssl_mode
        
        # Optional: Specify SSL certificate files for verify-ca or verify-full modes
        ssl_root_cert = config('DATABASE_SSL_ROOT_CERT', default='')
        ssl_cert = config('DATABASE_SSL_CERT', default='')
        ssl_key = config('DATABASE_SSL_KEY', default='')
        
        if ssl_root_cert:
            base_options['sslrootcert'] = ssl_root_cert
        if ssl_cert:
            base_options['sslcert'] = ssl_cert
        if ssl_key:
            base_options['sslkey'] = ssl_key
    
    DATABASES['default']['OPTIONS'].update(base_options)
    DATABASES['default']['ATOMIC_REQUESTS'] = False  # Disable for better performance (use transactions explicitly)
    # Increased connection pool for better performance
    DATABASES['default']['CONN_MAX_AGE'] = config('DATABASE_CONN_MAX_AGE', default=600, cast=int)
    DATABASES['default']['AUTOCOMMIT'] = True
    # Performance optimizations
    DATABASES['default']['OPTIONS']['connect_timeout'] = 10

# PostgreSQL is the ONLY supported database for this application
# SQLite and MySQL configurations have been removed to prevent duplicate data issues
if db_engine != 'django.db.backends.postgresql':
    raise ValueError(
        f"❌ ERROR: Only PostgreSQL is supported. "
        f"Current database engine: {db_engine}\n"
        f"Please set DATABASE_URL to a PostgreSQL connection string in your .env file.\n"
        f"Example: DATABASE_URL=postgresql://user:password@localhost:5432/hms_db"
    )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators


# Admin forms (e.g., Group permissions) submit thousands of fields
DATA_UPLOAD_MAX_NUMBER_FIELDS = 20000


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Location defaults for login tracking / geofencing
TEST_IP_ADDRESS = config('TEST_IP_ADDRESS', default='102.176.95.4')
DEFAULT_LOGIN_COUNTRY = config('DEFAULT_LOGIN_COUNTRY', default='Ghana')
DEFAULT_LOGIN_REGION = config('DEFAULT_LOGIN_REGION', default='Greater Accra')
DEFAULT_LOGIN_CITY = config('DEFAULT_LOGIN_CITY', default='Accra')
DEFAULT_LOGIN_LATITUDE = config('DEFAULT_LOGIN_LATITUDE', default=5.6037, cast=float)
DEFAULT_LOGIN_LONGITUDE = config('DEFAULT_LOGIN_LONGITUDE', default=-0.1870, cast=float)
DEFAULT_LOGIN_TIMEZONE = config('DEFAULT_LOGIN_TIMEZONE', default='Africa/Accra')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# Static files directories - only in development (not needed when using collectstatic)
# In production, use collected static files from STATIC_ROOT only
STATICFILES_DIRS = [
    BASE_DIR / 'hospital' / 'static',
] if DEBUG else []  # Empty in production - use collected static files only

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site ID for django.contrib.sites
SITE_ID = 1

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
        # 'django_filters.rest_framework.DjangoFilterBackend',  # Temporarily disabled - incompatible with Python 3.14 (pkgutil.find_loader removed)
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# CORS Settings
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000', cast=lambda v: [s.strip() for s in v.split(',')])
CORS_ALLOW_CREDENTIALS = True

# Cache Configuration - Redis for High Performance (ENABLED BY DEFAULT)
# Auto-detect Redis URL based on environment
# In Docker: use 'redis://redis:6379/0'
# Locally: use 'redis://127.0.0.1:6379/0' (if Redis is exposed from Docker)
import os
import socket

def get_redis_url():
    """Auto-detect the best Redis URL based on environment"""
    # Check if REDIS_URL is explicitly set
    explicit_url = os.environ.get('REDIS_URL')
    if explicit_url:
        return explicit_url
    
    # Check if we're in Docker by looking for Docker-specific environment
    # Docker Compose sets COMPOSE_PROJECT_NAME, or we can check hostname
    if os.path.exists('/.dockerenv') or os.environ.get('COMPOSE_PROJECT_NAME'):
        return 'redis://redis:6379/0'  # Docker internal network
    
    # Try to resolve 'redis' hostname (works in Docker network)
    try:
        socket.gethostbyname('redis')
        return 'redis://redis:6379/0'  # Docker internal network
    except (socket.gaierror, OSError):
        # Not in Docker, use localhost (Redis exposed from Docker on port 6379)
        return 'redis://127.0.0.1:6379/0'

REDIS_URL = config('REDIS_URL', default=get_redis_url())
# Enable Redis by default for maximum performance
USE_REDIS_CACHE = config('USE_REDIS_CACHE', default=True, cast=bool)
REDIS_MAX_CONNECTIONS = config('REDIS_MAX_CONNECTIONS', default=200, cast=int)
REDIS_SOCKET_TIMEOUT = config('REDIS_SOCKET_TIMEOUT', default=5, cast=int)

# Test Redis connection and fallback to local memory if unavailable
redis_available = False
if USE_REDIS_CACHE:
    try:
        import redis
        # Try to connect to Redis with short timeout
        redis_client = redis.from_url(REDIS_URL, socket_connect_timeout=2, socket_timeout=2)
        redis_client.ping()
        redis_available = True
    except Exception as e:
        # Redis not available, fallback to local memory cache (per-process, not
        # shared across Gunicorn workers; sessions use DB). In production, ensure
        # Redis is running and reachable to avoid this fallback.
        redis_available = False
        USE_REDIS_CACHE = False
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Redis not available at {REDIS_URL}: {e}. Falling back to local memory cache.")

if USE_REDIS_CACHE and redis_available:
    # Redis Cache (Best Performance)
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': REDIS_SOCKET_TIMEOUT,
                'SOCKET_TIMEOUT': REDIS_SOCKET_TIMEOUT,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': REDIS_MAX_CONNECTIONS,
                    'retry_on_timeout': True,
                },
                'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',  # Use pickle to support Django querysets
            },
            'KEY_PREFIX': 'hms',
            'TIMEOUT': 600,  # 10 minutes default cache timeout for better performance
            'VERSION': 1,
        },
        # Separate cache for sessions
        'sessions': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL.replace('/0', '/1'),  # Use different DB for sessions
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': REDIS_SOCKET_TIMEOUT,
                'SOCKET_TIMEOUT': REDIS_SOCKET_TIMEOUT,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': REDIS_MAX_CONNECTIONS,
                    'retry_on_timeout': True,
                },
                'SERIALIZER': 'django_redis.serializers.pickle.PickleSerializer',  # Use pickle to support Django querysets
            },
            'KEY_PREFIX': 'hms_sessions',
            'TIMEOUT': 86400,  # 24 hours for sessions
        },
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
    SESSION_CACHE_ALIAS = 'sessions'
else:
    # Local Memory Cache (Fallback - Still Fast)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'hms-cache',
            'OPTIONS': {
                'MAX_ENTRIES': 10000,  # Store up to 10k items
            },
            'TIMEOUT': 300,
        }
    }
    # Use database for sessions if Redis not available
    SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Celery Configuration
# Use the same Redis URL detection logic
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)
# Use Redis for result backend when available to avoid DB load from task results
if USE_REDIS_CACHE and redis_available:
    _celery_redis = REDIS_URL.replace('/0', '/3') if '/0' in REDIS_URL else f'{REDIS_URL}/3'
    CELERY_RESULT_BACKEND = _celery_redis
else:
    CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# Throughput: lower prefetch avoids long tasks blocking other work; tune per deployment.
CELERY_WORKER_PREFETCH_MULTIPLIER = config('CELERY_WORKER_PREFETCH_MULTIPLIER', default=4, cast=int)
CELERY_TASK_ACKS_LATE = config('CELERY_TASK_ACKS_LATE', default=True, cast=bool)

# Activity audit: async INSERT via Celery (faster requests). Set AUDIT_LOG_ASYNC=False for synchronous DB write.
AUDIT_LOG_ASYNC = config('AUDIT_LOG_ASYNC', default=True, cast=bool)

# Cacheops Configuration (if used)
CACHEOPS_REDIS = config('CACHEOPS_REDIS', default=REDIS_URL.replace('/0', '/2') if '/0' in REDIS_URL else f'{REDIS_URL}/2')

# Authentication settings
# Use custom HMS login instead of admin login
LOGIN_URL = '/hms/login/'
LOGIN_REDIRECT_URL = '/hms/'
LOGOUT_REDIRECT_URL = '/hms/'

# Static files (CSS, JavaScript, Images) - Optimized for Performance
STATIC_URL = '/static/'
# Use environment variable for STATIC_ROOT if set (for server deployment)
STATIC_ROOT = config('STATIC_ROOT', default=str(BASE_DIR / 'staticfiles'))
# Ensure STATIC_ROOT is a Path object
if isinstance(STATIC_ROOT, str):
    STATIC_ROOT = Path(STATIC_ROOT)
# WhiteNoise with compression and caching for maximum performance
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# WhiteNoise Configuration for Maximum Performance
WHITENOISE_USE_FINDERS = False  # Use collected static files only
WHITENOISE_AUTOREFRESH = DEBUG  # Only auto-refresh in DEBUG mode
WHITENOISE_MAX_AGE = 31536000 if not DEBUG else 0  # 1 year cache in production
WHITENOISE_MANIFEST_STRICT = False  # Don't fail on missing files
WHITENOISE_ADD_HEADERS_FUNCTION = None  # Use default headers

# Static files finders optimization
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Media files
MEDIA_URL = '/media/'
# Use environment variable for MEDIA_ROOT if set (for server deployment)
MEDIA_ROOT = config('MEDIA_ROOT', default=str(BASE_DIR / 'media'))
# Ensure MEDIA_ROOT is a Path object
if isinstance(MEDIA_ROOT, str):
    MEDIA_ROOT = Path(MEDIA_ROOT)

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Django Allauth
AUTHENTICATION_BACKENDS = [
    'hospital.backends.EmailOrUsernameModelBackend',  # Custom: supports username OR email
    'django.contrib.auth.backends.ModelBackend',  # Fallback to standard backend
    'guardian.backends.ObjectPermissionBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

# SMS Configuration - SMS Notify GH
SMS_API_KEY = config('SMS_API_KEY', default='84c879bb-f9f9-4666-84a8-9f70a9b238cc')
SMS_SENDER_ID = config('SMS_SENDER_ID', default='PrimeCare')
SMS_API_URL = config('SMS_API_URL', default='https://sms.smsnotifygh.com/smsapi')

# Site URL for SMS links (appointments, confirmations, etc.)
# Set this to your production domain (e.g., 'https://yourdomain.com')
# Leave empty to auto-detect from Site framework or ALLOWED_HOSTS
SITE_URL = config('SITE_URL', default='')

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@primecare.com')

# Hospital Branding (for emails and notifications)
HOSPITAL_NAME = config('HOSPITAL_NAME', default='PrimeCare Hospital')
HOSPITAL_LOGO_URL = config('HOSPITAL_LOGO_URL', default='')

# Queue SMS ticket prefix when department config would yield a bad code (e.g. ACC- from "Accounts")
QUEUE_TICKET_PREFIX_FALLBACK = config('QUEUE_TICKET_PREFIX_FALLBACK', default='VIS')

# WhatsApp Configuration (Twilio WhatsApp API)
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = config('TWILIO_WHATSAPP_FROM', default='whatsapp:+14155238886')  # Twilio Sandbox number

# Alternative: Meta WhatsApp Business API
USE_META_WHATSAPP_API = config('USE_META_WHATSAPP_API', default=False, cast=bool)
META_WHATSAPP_ACCESS_TOKEN = config('META_WHATSAPP_ACCESS_TOKEN', default='')
META_WHATSAPP_PHONE_NUMBER_ID = config('META_WHATSAPP_PHONE_NUMBER_ID', default='')

# Logging Configuration
import logging
import os

# Ensure logs directory exists
logs_dir = BASE_DIR / 'logs'
logs_dir.mkdir(exist_ok=True)

# Create a safe StreamHandler for Windows that avoids colorama issues
if sys.platform == 'win32':
    class SafeStreamHandler(logging.StreamHandler):
        """StreamHandler that catches OSError from colorama and handles gracefully"""
        def emit(self, record):
            try:
                super().emit(record)
            except OSError:
                # If colorama causes OSError, try writing directly to underlying stream
                try:
                    stream = self.stream
                    if hasattr(stream, 'wrapped'):
                        # If stream is wrapped by colorama, try to access original
                        original_stream = stream.wrapped
                        msg = self.format(record)
                        original_stream.write(msg + self.terminator)
                        self.flush()
                    else:
                        # Fall back to sys.__stdout__ or sys.__stderr__
                        fallback = sys.__stdout__ if stream is sys.stdout else sys.__stderr__
                        msg = self.format(record)
                        fallback.write(msg + self.terminator)
                        fallback.flush()
                except Exception:
                    # If all else fails, silently ignore to prevent crash
                    pass
else:
    # On non-Windows, use standard StreamHandler
    SafeStreamHandler = logging.StreamHandler

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'bulk_creation': {
            'format': '🚨 {levelname} {asctime} - {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'bulk_creation_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'bulk_creation.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'bulk_creation',
            'level': 'WARNING',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'hospital.bulk_creation_monitor': {
            'handlers': ['console', 'bulk_creation_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Legacy LOGGING configuration (if exists, will be merged)
_legacy_logging = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(logs_dir / 'django.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(logs_dir / 'django_errors.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'bulk_creation_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(logs_dir / 'bulk_creation.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'bulk_creation',
        },
        'console': {
            'level': 'DEBUG',
            '()': SafeStreamHandler,  # Use safe handler that catches colorama errors
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'hospital': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'hospital.bulk_creation_monitor': {
            'handlers': ['file', 'console', 'bulk_creation_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Cross-Origin-Opener-Policy (COOP)
# Only set in production with HTTPS to avoid browser warnings
# In development, browsers ignore COOP on non-HTTPS/non-localhost origins
if not DEBUG:
    # In production, set COOP for security
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
else:
    # In development, don't set COOP to avoid browser warnings
    # The warning is harmless but can be annoying
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# Production Security Settings (Conditional)
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    # CSRF_COOKIE_SECURE is set below in CSRF Security section
    
    # HSTS Settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Secure referrer policy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Additional security headers
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Rate limiting
    RATELIMIT_ENABLE = True
else:
    # Explicitly disable HTTPS redirect in DEBUG mode
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    
# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_COOKIE_SECURE = not DEBUG  # Set to True in production with HTTPS
# Don't set cookie domain for IP addresses to work properly
SESSION_COOKIE_DOMAIN = None
# Ensure session cookies work with IP addresses in Docker
SESSION_SAVE_EVERY_REQUEST = False  # Only save session when modified

# CSRF Security
# Use cookies for CSRF tokens (more reliable than sessions, especially in Docker)
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to read the token
CSRF_COOKIE_SAMESITE = 'Lax'  # Allows same-site and top-level navigation requests
CSRF_USE_SESSIONS = False  # Use cookies instead of sessions for better Docker compatibility
CSRF_COOKIE_AGE = 31449600  # 1 year
CSRF_COOKIE_SECURE = not DEBUG  # Set to True in production with HTTPS
# Don't set cookie domain for IP addresses to work properly
CSRF_COOKIE_DOMAIN = None
# Ensure CSRF cookie is set on all requests, not just POST
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

# CSRF_TRUSTED_ORIGINS - Allow localhost and local network IPs
# In Docker, this should include the host machine's IP address
# Also includes common local network IPs for development
# In production, automatically add HTTPS origins based on ALLOWED_HOSTS
default_csrf_origins = 'http://localhost:8000,http://127.0.0.1:8000,http://0.0.0.0:8000,http://192.168.2.97:8000,http://192.168.233.1:8000,http://192.168.64.1:8000,http://192.168.0.105:8000,http://172.20.112.1:8000,http://10.132.245.143:8000'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default=default_csrf_origins, cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])

# In production (non-DEBUG), automatically add HTTPS origins for all ALLOWED_HOSTS
if not DEBUG:
    # Get SITE_URL from settings or construct from ALLOWED_HOSTS
    site_url = config('SITE_URL', default='')
    if site_url:
        # Add the site URL to CSRF trusted origins
        if site_url not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(site_url)
        # Also add without trailing slash
        site_url_no_slash = site_url.rstrip('/')
        if site_url_no_slash not in CSRF_TRUSTED_ORIGINS and site_url_no_slash != site_url:
            CSRF_TRUSTED_ORIGINS.append(site_url_no_slash)
    
    # Add HTTPS origins for all ALLOWED_HOSTS (for production domains)
    for host in ALLOWED_HOSTS:
        if host and host not in ['localhost', '127.0.0.1', '0.0.0.0']:
            # Add both HTTP and HTTPS (some deployments may not have SSL initially)
            http_origin = f'http://{host}'
            https_origin = f'https://{host}'
            if http_origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(http_origin)
            if https_origin not in CSRF_TRUSTED_ORIGINS:
                CSRF_TRUSTED_ORIGINS.append(https_origin)
            # Also add with common ports
            for port in [80, 443, 8000, 8080]:
                http_port_origin = f'http://{host}:{port}'
                https_port_origin = f'https://{host}:{port}'
                if http_port_origin not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(http_port_origin)
                if https_port_origin not in CSRF_TRUSTED_ORIGINS:
                    CSRF_TRUSTED_ORIGINS.append(https_port_origin)

# In DEBUG mode, add additional common development origins
if DEBUG:
    additional_origins = [
        'http://0.0.0.0:8000',
        'http://localhost:8000',
        'http://127.0.0.1:8000',
        'http://localhost',
        'http://127.0.0.1',
        'http://192.168.2.97',
        'http://192.168.233.1',
        'http://192.168.64.1',
        'http://192.168.0.105:8000',
        'http://192.168.0.105',
        'http://172.20.112.1',
        'http://10.132.245.143:8000',
        'http://10.132.245.143',
    ]
    for origin in additional_origins:
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

# Password Security
# Relax password rules so admins can pick any password (even short/simple)
AUTH_PASSWORD_VALIDATORS = []

# Performance Optimizations
# Disable database query logging in production for better performance
if not DEBUG:
    if 'loggers' in LOGGING:
        LOGGING['loggers']['django.db.backends'] = {
            'handlers': ['console'],
            'level': 'ERROR',  # Only log errors, not all queries
            'propagate': False,
        }

# Optimize file uploads for better performance
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB - use disk for larger files
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440  # 2.5 MB
# DATA_UPLOAD_MAX_NUMBER_FIELDS already set to 20000 above

# Enable connection pooling optimizations
if db_engine == 'django.db.backends.postgresql':
    # Increase connection pool size for better performance
    DATABASES['default']['CONN_MAX_AGE'] = config('DATABASE_CONN_MAX_AGE', default=600, cast=int)

# Content Security Policy (if django-csp is installed)
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net", "cdnjs.cloudflare.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "cdn.jsdelivr.net", "fonts.googleapis.com")
CSP_FONT_SRC = ("'self'", "fonts.gstatic.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'",)

# Debug Toolbar (development) and optional staging profiling (STAGING_PROFILING + requirements-dev.txt)
if DEBUG:
    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]

STAGING_PROFILING = config('STAGING_PROFILING', default=False, cast=bool)
if STAGING_PROFILING:
    try:
        import debug_toolbar  # noqa: F401
    except ImportError:
        import logging

        logging.getLogger(__name__).warning(
            'STAGING_PROFILING is True but debug_toolbar is not installed. '
            'Run: pip install django-debug-toolbar'
        )
    else:
        if 'debug_toolbar' not in INSTALLED_APPS:
            INSTALLED_APPS = list(INSTALLED_APPS) + ['debug_toolbar']
        _ddt_mw = 'debug_toolbar.middleware.DebugToolbarMiddleware'
        if _ddt_mw not in MIDDLEWARE:
            _mw = list(MIDDLEWARE)
            try:
                _ins = _mw.index('django.middleware.security.SecurityMiddleware') + 1
            except ValueError:
                _ins = 0
            _mw.insert(_ins, _ddt_mw)
            MIDDLEWARE = _mw
        INTERNAL_IPS = ['127.0.0.1', 'localhost', '::1']
        extra_ips = config('DEBUG_TOOLBAR_EXTRA_IPS', default='', cast=str)
        if extra_ips.strip():
            INTERNAL_IPS.extend(s.strip() for s in extra_ips.split(',') if s.strip())

# Health Check
HEALTH_CHECK = {
    'DISK_USAGE_MAX': 90,  # percent
    'MEMORY_MIN': 100,    # in MB
}

# Sentry Configuration (if SENTRY_DSN is provided)
SENTRY_DSN = config('SENTRY_DSN', default=None)
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.celery import CeleryIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            CeleryIntegration(),
        ],
        traces_sample_rate=0.1,
        send_default_pii=True,
    )

# Fix for Python 3.14 compatibility with Django 4.2.7
# This patches Django's BaseContext.__copy__ method to work with Python 3.14
# The issue: Python 3.14 changed how __copy__ works, causing AttributeError
# when Django tries to copy template contexts (especially with crispy_forms)
if sys.version_info >= (3, 14):
    try:
        import copy
        from django.template.context import BaseContext
        
        def _fixed_basecontext_copy(self):
            """Fixed __copy__ method for Python 3.14 compatibility"""
            # Create a new instance of the same class
            duplicate = self.__class__()
            # Copy the instance dictionary
            duplicate.__dict__.update(copy.copy(self.__dict__))
            # Manually copy the dicts list if it exists
            if hasattr(self, 'dicts'):
                duplicate.dicts = self.dicts[:]
            return duplicate
        
        # Apply the monkey patch
        BaseContext.__copy__ = _fixed_basecontext_copy
    except (ImportError, AttributeError):
        # If Django isn't loaded yet or the class doesn't exist, ignore
        pass
