# Generated by Django 4.2.7 on 2025-10-28 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0006_add_staff_shifts_and_qualifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="date_of_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SMSNotification",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday"),
                            ("appointment", "Appointment"),
                            ("lab_result", "Lab Result"),
                            ("payment", "Payment"),
                            ("reminder", "Reminder"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient_number", models.CharField(max_length=17)),
                ("recipient_name", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="BirthdayReminder",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[("staff", "Staff"), ("patient", "Patient")],
                        max_length=20,
                    ),
                ),
                ("birthday_date", models.DateField()),
                ("reminder_date", models.DateField()),
                ("notified", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("notification_sent_to", models.TextField(blank=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_reminders",
                        to="hospital.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="birthday_reminders",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["reminder_date"],
                "unique_together": {
                    ("reminder_type", "patient", "birthday_date"),
                    ("reminder_type", "staff", "birthday_date"),
                },
            },
        ),
    ]
