# Generated by Django 4.2.7 on 2025-10-28 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0008_add_missing_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalChart",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("chart_date", models.DateField(default=datetime.date.today)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.staff",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_charts",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_charts",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-chart_date"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecialistProfile",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialists",
                        to="hospital.specialty",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_profile",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["specialty", "staff__user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="SpecialistConsultation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "consultation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("chief_complaint", models.TextField()),
                ("history_of_present_illness", models.TextField(blank=True)),
                ("review_of_systems", models.TextField(blank=True)),
                ("examination_findings", models.TextField(blank=True)),
                ("vitals", models.JSONField(blank=True, default=dict)),
                ("assessment", models.TextField(blank=True)),
                ("differential_diagnosis", models.TextField(blank=True)),
                ("plan", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_consultations",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "orders",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialist_consultations",
                        to="hospital.order",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_consultations",
                        to="hospital.patient",
                    ),
                ),
                (
                    "prescriptions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialist_consultations",
                        to="hospital.prescription",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="hospital.specialistprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="OphthalmologyChart",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("chart_date", models.DateField(default=datetime.date.today)),
                ("visual_acuity_re_right", models.CharField(blank=True, max_length=20)),
                ("visual_acuity_re_left", models.CharField(blank=True, max_length=20)),
                ("visual_acuity_le_right", models.CharField(blank=True, max_length=20)),
                ("visual_acuity_le_left", models.CharField(blank=True, max_length=20)),
                (
                    "iop_right",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "iop_left",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("refraction_right", models.CharField(blank=True, max_length=100)),
                ("refraction_left", models.CharField(blank=True, max_length=100)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.staff",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ophthalmology_charts",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ophthalmology_charts",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-chart_date"],
            },
        ),
        migrations.CreateModel(
            name="DentalProcedure",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("procedure_code", models.CharField(max_length=50)),
                ("procedure_name", models.CharField(max_length=200)),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Diagnostic"),
                            ("preventive", "Preventive"),
                            ("restorative", "Restorative"),
                            ("endodontic", "Endodontic"),
                            ("periodontic", "Periodontic"),
                            ("oral_surgery", "Oral Surgery"),
                            ("prosthodontic", "Prosthodontic"),
                            ("orthodontic", "Orthodontic"),
                            ("cosmetic", "Cosmetic"),
                        ],
                        max_length=30,
                    ),
                ),
                ("teeth", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("procedure_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "dental_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="hospital.dentalchart",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CardiologyChart",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("chart_date", models.DateField(default=datetime.date.today)),
                ("blood_pressure", models.CharField(blank=True, max_length=20)),
                ("heart_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ejection_fraction",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("cardiac_history", models.TextField(blank=True)),
                ("medications", models.TextField(blank=True)),
                ("allergies", models.TextField(blank=True)),
                ("ecg_findings", models.TextField(blank=True)),
                ("echo_findings", models.TextField(blank=True)),
                ("stress_test_results", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.staff",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardiology_charts",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardiology_charts",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-chart_date"],
            },
        ),
        migrations.CreateModel(
            name="ToothCondition",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("tooth_number", models.CharField(max_length=10)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("carious", "Carious"),
                            ("filled", "Filled"),
                            ("missing", "Missing"),
                            ("crown", "Crown"),
                            ("bridge", "Bridge"),
                            ("implant", "Implant"),
                            ("root_canal", "Root Canal Treated"),
                            ("extraction_needed", "Extraction Needed"),
                            ("erupting", "Erupting"),
                            ("impacted", "Impacted"),
                            ("deciduous", "Deciduous (Baby Tooth)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("surface", models.CharField(blank=True, max_length=50)),
                ("color_code", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("procedure_date", models.DateField(blank=True, null=True)),
                (
                    "dental_chart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tooth_conditions",
                        to="hospital.dentalchart",
                    ),
                ),
            ],
            options={
                "ordering": ["tooth_number"],
                "unique_together": {("dental_chart", "tooth_number", "surface")},
            },
        ),
    ]
