# Generated by Django 4.2.7 on 2025-10-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0009_dentalchart_specialty_specialistprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="insurance_company",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Insurance Company Name"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="insurance_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Insurance ID/Policy Number"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_group_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Group Number"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_member_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Insurance Member ID"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="insurance_policy_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Policy Number (Legacy)"
            ),
        ),
    ]
