# Generated by Django 4.2.7 on 2025-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0011_add_procurement_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="National ID",
            ),
        ),
    ]
