# Generated by Django 4.2.7 on 2025-10-28 17:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0012_fix_national_id_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "service_code",
                    models.CharField(
                        choices=[
                            ("registration", "Patient Registration"),
                            ("consultation_general", "General Consultation"),
                            ("consultation_specialist", "Specialist Consultation"),
                            ("vital_signs", "Vital Signs Recording"),
                            ("lab_test", "Laboratory Test"),
                            ("imaging", "Imaging Study"),
                            ("pharmacy", "Pharmacy Dispensing"),
                            ("admission", "Admission Fee"),
                            ("bed_day", "Bed Day Charge"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "default_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="GHS",
                        help_text="Currency code (GHS, USD, etc.)",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Default Price",
                "verbose_name_plural": "Default Prices",
                "ordering": ["service_code"],
            },
        ),
        migrations.CreateModel(
            name="PayerPrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "service_code",
                    models.CharField(
                        choices=[
                            ("registration", "Patient Registration"),
                            ("consultation_general", "General Consultation"),
                            ("consultation_specialist", "Specialist Consultation"),
                            ("vital_signs", "Vital Signs Recording"),
                            ("lab_test", "Laboratory Test"),
                            ("imaging", "Imaging Study"),
                            ("pharmacy", "Pharmacy Dispensing"),
                            ("admission", "Admission Fee"),
                            ("bed_day", "Bed Day Charge"),
                        ],
                        max_length=50,
                    ),
                ),
                ("custom_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payer_prices",
                        to="hospital.payer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payer Price",
                "verbose_name_plural": "Payer Prices",
                "ordering": ["payer", "service_code"],
                "unique_together": {("payer", "service_code")},
            },
        ),
    ]
