# Generated by Django 4.2.7 on 2025-10-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0013_add_pricing_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicalnote",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinical_notes",
                to="hospital.staff",
            ),
        ),
    ]
