# Generated by Django 4.2.7 on 2025-10-28 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0015_add_encounter_current_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagingstudy",
            options={
                "ordering": ["-scheduled_at", "-created"],
                "verbose_name_plural": "Imaging Studies",
            },
        ),
        migrations.AlterField(
            model_name="encounter",
            name="current_activity",
            field=models.CharField(
                blank=True,
                db_column="current_activity",
                help_text="Current department activity: Consulting, Lab, Pharmacy",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("reason", models.TextField(help_text="Reason for referral")),
                (
                    "clinical_summary",
                    models.TextField(
                        blank=True, help_text="Clinical summary and relevant findings"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent", "Urgent"),
                            ("stat", "STAT"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "referred_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("appointment_date", models.DateTimeField(blank=True, null=True)),
                ("consultation_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "specialist_notes",
                    models.TextField(
                        blank=True, help_text="Specialist's notes and response"
                    ),
                ),
                (
                    "declined_reason",
                    models.TextField(
                        blank=True, help_text="Reason if referral is declined"
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_source",
                        to="hospital.specialistconsultation",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="hospital.patient",
                    ),
                ),
                (
                    "referring_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_made",
                        to="hospital.staff",
                    ),
                ),
                (
                    "specialist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals_received",
                        to="hospital.specialistprofile",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="hospital.specialty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
                "ordering": ["-referred_date"],
            },
        ),
        migrations.CreateModel(
            name="ImagingImage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload medical imaging picture",
                        upload_to="imaging_studies/%Y/%m/%d/",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of this image",
                        max_length=200,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Order/sequence of this image in the study"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imaging_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hospital.imagingstudy",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_images",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Imaging Images",
                "ordering": ["imaging_study", "sequence_number", "uploaded_at"],
                "unique_together": {("imaging_study", "sequence_number")},
            },
        ),
    ]
