# Generated by Django 4.2.7 on 2025-10-29 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0016_alter_imagingstudy_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowanceType",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for this allowance type",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage of Basic Salary"),
                            ("per_unit", "Per Unit (e.g., per hour, per day)"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default amount or percentage",
                        max_digits=12,
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this allowance is subject to tax",
                    ),
                ),
                (
                    "is_statutory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a statutory/required allowance",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display in payroll"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Allowance Type",
                "verbose_name_plural": "Allowance Types",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DeductionType",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for this deduction type",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "calculation_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Amount"),
                            ("percentage", "Percentage of Basic Salary"),
                            ("percentage_of_gross", "Percentage of Gross Pay"),
                            ("tiered", "Tiered Calculation (e.g., tax brackets)"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "default_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Default amount or percentage",
                        max_digits=12,
                    ),
                ),
                (
                    "is_statutory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a statutory/required deduction",
                    ),
                ),
                (
                    "is_loan",
                    models.BooleanField(
                        default=False, help_text="Whether this is a loan repayment"
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum deduction amount (if applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum deduction amount (if applicable)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display in payroll"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Deduction Type",
                "verbose_name_plural": "Deduction Types",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PayrollConfiguration",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        default="Default Payroll Configuration", max_length=100
                    ),
                ),
                (
                    "tax_calculation_method",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate"),
                            ("progressive", "Progressive (Tax Brackets)"),
                            ("custom", "Custom Calculation"),
                        ],
                        default="progressive",
                        max_length=20,
                    ),
                ),
                (
                    "default_tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Default flat tax rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_free_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax-free allowance amount",
                        max_digits=12,
                    ),
                ),
                (
                    "social_security_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Social security contribution rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "social_security_max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum social security contribution",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pension_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Pension contribution rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "pension_max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum pension contribution",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "default_payroll_day",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Default day of month for payroll processing",
                    ),
                ),
                (
                    "regular_hours_per_day",
                    models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Overtime multiplier (e.g., 1.5 for time and a half)",
                        max_digits=4,
                    ),
                ),
                ("currency_symbol", models.CharField(default="GHS", max_length=10)),
                ("currency_code", models.CharField(default="GHS", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=True, help_text="Use this as the default configuration"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Payroll Configuration",
                "verbose_name_plural": "Payroll Configurations",
            },
        ),
        migrations.CreateModel(
            name="TaxBracket",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("bracket_name", models.CharField(max_length=100)),
                (
                    "min_income",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum income for this bracket",
                        max_digits=12,
                    ),
                ),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum income for this bracket (null = no upper limit)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate as percentage (e.g., 15.00 for 15%)",
                        max_digits=5,
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fixed tax amount for this bracket",
                        max_digits=12,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Date this bracket becomes effective"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this bracket expires (null = current)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tax Bracket",
                "verbose_name_plural": "Tax Brackets",
                "ordering": ["min_income"],
            },
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={
                "ordering": ["item_name"],
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
            },
        ),
        migrations.AlterModelOptions(
            name="procurementrequest",
            options={
                "ordering": ["-request_date", "-created"],
                "verbose_name": "Procurement Request",
                "verbose_name_plural": "Procurement Requests",
            },
        ),
        migrations.AlterModelOptions(
            name="procurementrequestitem",
            options={
                "ordering": ["created"],
                "verbose_name": "Procurement Request Item",
                "verbose_name_plural": "Procurement Request Items",
            },
        ),
        migrations.AlterModelOptions(
            name="store",
            options={
                "ordering": ["name"],
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
            },
        ),
        migrations.AlterModelOptions(
            name="storetransfer",
            options={
                "ordering": ["-transfer_date", "-created"],
                "verbose_name": "Store Transfer",
                "verbose_name_plural": "Store Transfers",
            },
        ),
        migrations.AlterModelOptions(
            name="storetransferline",
            options={
                "ordering": ["created"],
                "verbose_name": "Store Transfer Line",
                "verbose_name_plural": "Store Transfer Lines",
            },
        ),
        migrations.CreateModel(
            name="PayrollDeduction",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "deduction_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_deductions",
                        to="hospital.deductiontype",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deduction_items",
                        to="hospital.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Deduction",
                "verbose_name_plural": "Payroll Deductions",
                "ordering": ["deduction_type__display_order"],
            },
        ),
        migrations.CreateModel(
            name="PayrollAllowance",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_taxable", models.BooleanField(default=True)),
                (
                    "allowance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_allowances",
                        to="hospital.allowancetype",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_items",
                        to="hospital.payroll",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Allowance",
                "verbose_name_plural": "Payroll Allowances",
                "ordering": ["allowance_type__display_order"],
            },
        ),
    ]
