# Generated by Django 4.2.7 on 2025-10-29 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0017_add_payroll_configuration"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_for_pharmacy",
                    models.BooleanField(
                        default=False,
                        help_text="If True, items in this category are considered pharmacy/pharmaceutical items",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for display in dropdowns"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Inventory Category",
                "verbose_name_plural": "Inventory Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Category helps organize items (Pharmacy, Equipment, Supplies, etc.)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="hospital.inventorycategory",
            ),
        ),
    ]
