# Generated by Django 4.2.7 on 2025-10-29 13:45

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0019_create_default_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalProcedureCatalog",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Procedure code (e.g., D0110)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("diagnostic", "Diagnostic"),
                            ("preventive", "Preventive"),
                            ("restorative", "Restorative"),
                            ("endodontic", "Endodontic"),
                            ("periodontic", "Periodontic"),
                            ("oral_surgery", "Oral Surgery"),
                            ("prosthodontic", "Prosthodontic"),
                            ("orthodontic", "Orthodontic"),
                            ("cosmetic", "Cosmetic"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dental Procedure Catalog",
                "verbose_name_plural": "Dental Procedure Catalog",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="referral",
            options={"ordering": ["-referred_date"]},
        ),
        migrations.RemoveField(
            model_name="referral",
            name="consultation",
        ),
    ]
