# Generated by Django 4.2.7 on 2025-10-29 19:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0020_dentalprocedurecatalog_alter_referral_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceClaimItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "patient_insurance_id",
                    models.CharField(
                        max_length=100,
                        verbose_name="Patient Insurance ID/Member Number",
                    ),
                ),
                ("service_description", models.CharField(max_length=500)),
                (
                    "service_date",
                    models.DateField(help_text="Date service was provided"),
                ),
                (
                    "billed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount approved by insurance",
                        max_digits=12,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount actually paid by insurance",
                        max_digits=12,
                    ),
                ),
                (
                    "claim_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Submission"),
                            ("submitted", "Submitted to Insurance"),
                            ("processing", "Processing"),
                            ("approved", "Approved"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid in Full"),
                            ("rejected", "Rejected"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "claim_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number from insurance company",
                        max_length=100,
                    ),
                ),
                (
                    "submitted_date",
                    models.DateField(
                        blank=True,
                        help_text="Date claim was submitted to insurance",
                        null=True,
                    ),
                ),
                (
                    "approved_date",
                    models.DateField(
                        blank=True,
                        help_text="Date claim was approved by insurance",
                        null=True,
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True,
                        help_text="Date payment was received from insurance",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason if claim was rejected"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claim_items",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_items",
                        to="hospital.invoice",
                    ),
                ),
                (
                    "invoice_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_items",
                        to="hospital.invoiceline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Claim Item",
                "verbose_name_plural": "Insurance Claim Items",
                "ordering": ["-service_date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyInsuranceClaim",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "claim_number",
                    models.CharField(
                        help_text="Monthly claim number (auto-generated)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "claim_month",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        help_text="Month (1-12)",
                    ),
                ),
                ("claim_year", models.IntegerField(help_text="Year (e.g., 2025)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready_for_submission", "Ready for Submission"),
                            ("submitted", "Submitted"),
                            ("processing", "Processing"),
                            ("partially_paid", "Partially Paid"),
                            ("fully_paid", "Fully Paid"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "total_items",
                    models.IntegerField(
                        default=0, help_text="Total number of claim items"
                    ),
                ),
                (
                    "total_billed_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_approved_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True,
                        help_text="Date claim was submitted to insurance",
                        null=True,
                    ),
                ),
                (
                    "submission_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number from insurance company",
                        max_length=100,
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date payment was received", null=True
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, help_text="Payment reference number", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_claims",
                        to="hospital.payer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Insurance Claim",
                "verbose_name_plural": "Monthly Insurance Claims",
                "ordering": ["-claim_year", "-claim_month", "-created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineAIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("analysis_type", models.CharField(max_length=50)),
                ("input_data", models.JSONField(default=dict)),
                ("ai_response", models.JSONField(default=dict)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineConsultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("consultation_id", models.CharField(max_length=20, unique=True)),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Call"),
                            ("audio", "Audio Call"),
                            ("chat", "Text Chat"),
                            ("hybrid", "Hybrid (Video + Chat)"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("symptoms", models.JSONField(blank=True, default=list)),
                (
                    "ai_triage_score",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("ai_triage_recommendation", models.TextField(blank=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_date", models.DateTimeField(blank=True, null=True)),
                ("meeting_room_id", models.CharField(blank=True, max_length=100)),
                ("meeting_url", models.URLField(blank=True)),
                ("recording_url", models.URLField(blank=True)),
                ("quality_rating", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("ai_symptom_analysis", models.JSONField(blank=True, default=dict)),
                (
                    "ai_diagnosis_suggestions",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "ai_prescription_suggestions",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_consultations",
                        to="hospital.staff",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_consultations",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("device_name", models.CharField(max_length=100)),
                ("device_type", models.CharField(max_length=50)),
                ("os", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_devices",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineLabOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("instructions", models.TextField(blank=True)),
                ("is_urgent", models.BooleanField(default=False)),
                ("priority", models.CharField(default="normal", max_length=20)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_orders",
                        to="hospital.telemedicineconsultation",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.labtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File Attachment"),
                            ("prescription", "Prescription"),
                            ("lab_order", "Lab Order"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="telemedicine/attachments/"
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="hospital.telemedicineconsultation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("consultation_scheduled", "Consultation Scheduled"),
                            ("consultation_starting", "Consultation Starting"),
                            ("consultation_reminder", "Consultation Reminder"),
                            ("message_received", "Message Received"),
                            ("prescription_ready", "Prescription Ready"),
                            ("lab_result_ready", "Lab Result Ready"),
                            ("payment_required", "Payment Required"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.telemedicineconsultation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemedicine_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicinePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                ("payment_method", models.CharField(max_length=50)),
                ("payment_status", models.CharField(default="pending", max_length=20)),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("payment_gateway", models.CharField(blank=True, max_length=50)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="hospital.telemedicineconsultation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicinePrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("instructions", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="hospital.telemedicineconsultation",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hospital.drug"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TelemedicineVitalSigns",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "blood_pressure_systolic",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "blood_pressure_diastolic",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("heart_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to="hospital.telemedicineconsultation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="claims_batch",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="encounter",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="patient_insurance",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="pre_authorization",
        ),
        migrations.RemoveField(
            model_name="insuranceclaim",
            name="transaction",
        ),
        migrations.AlterUniqueTogether(
            name="patientinsurance",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="patientinsurance",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="patientinsurance",
            name="payer",
        ),
        migrations.DeleteModel(
            name="ClaimLineItem",
        ),
        migrations.DeleteModel(
            name="InsuranceClaim",
        ),
        migrations.DeleteModel(
            name="PatientInsurance",
        ),
        migrations.AddField(
            model_name="telemedicineaianalysis",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_analyses",
                to="hospital.telemedicineconsultation",
            ),
        ),
        migrations.AddField(
            model_name="insuranceclaimitem",
            name="monthly_claim",
            field=models.ForeignKey(
                blank=True,
                help_text="Monthly claim this item belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claim_items",
                to="hospital.monthlyinsuranceclaim",
            ),
        ),
        migrations.AddField(
            model_name="insuranceclaimitem",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insurance_claims",
                to="hospital.patient",
            ),
        ),
        migrations.AddField(
            model_name="insuranceclaimitem",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claim_items",
                to="hospital.payer",
            ),
        ),
        migrations.AddField(
            model_name="insuranceclaimitem",
            name="service_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claim_items",
                to="hospital.servicecode",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyinsuranceclaim",
            index=models.Index(
                fields=["payer", "claim_year", "claim_month"],
                name="hospital_mo_payer_i_fc5a7a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyinsuranceclaim",
            index=models.Index(fields=["status"], name="hospital_mo_status_54fed6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyinsuranceclaim",
            unique_together={("payer", "claim_month", "claim_year")},
        ),
        migrations.AddIndex(
            model_name="insuranceclaimitem",
            index=models.Index(
                fields=["patient", "service_date"],
                name="hospital_in_patient_4a132a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceclaimitem",
            index=models.Index(
                fields=["payer", "claim_status"], name="hospital_in_payer_i_31cf84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceclaimitem",
            index=models.Index(
                fields=["monthly_claim"], name="hospital_in_monthly_f33c87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceclaimitem",
            index=models.Index(
                fields=["claim_status", "service_date"],
                name="hospital_in_claim_s_986b5f_idx",
            ),
        ),
    ]
