# Generated by Django 4.2.7 on 2025-11-03 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0024_add_payment_allocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceKPI",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("kpi_code", models.CharField(max_length=50, unique=True)),
                ("kpi_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical Excellence"),
                            ("customer_service", "Customer Service"),
                            ("teamwork", "Teamwork & Collaboration"),
                            ("communication", "Communication"),
                            ("punctuality", "Punctuality & Attendance"),
                            ("leadership", "Leadership"),
                            ("technical", "Technical Skills"),
                            ("productivity", "Productivity"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "kpi_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("program_code", models.CharField(max_length=50, unique=True)),
                ("program_name", models.CharField(max_length=200)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory"),
                            ("optional", "Optional"),
                            ("certification", "Certification"),
                            ("cme", "Continuing Medical Education"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("objectives", models.TextField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("validity_months", models.PositiveIntegerField(blank=True, null=True)),
                ("provider", models.CharField(max_length=200)),
                (
                    "cost_per_person",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["program_name"],
            },
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="leave_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="contact_during_leave",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="covering_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covering_for",
                to="hospital.staff",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="handover_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="request_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="achievements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="development_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="improvement_areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="overall_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="promotion_recommended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="recommended_increase_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="review_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Review"),
                    ("probation", "Probation Review"),
                    ("mid_year", "Mid-Year Review"),
                    ("special", "Special Review"),
                ],
                default="annual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="salary_increase_recommended",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="staff_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="staff_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Staff Acknowledgment"),
                    ("acknowledged", "Acknowledged by Staff"),
                    ("approved", "Approved by Management"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="training_needs",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="assessment_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="certificate_file",
            field=models.FileField(
                blank=True, null=True, upload_to="training_certificates/"
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="funded_by",
            field=models.CharField(
                choices=[
                    ("hospital", "Hospital"),
                    ("self", "Self-Funded"),
                    ("sponsor", "External Sponsor"),
                ],
                default="hospital",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="passed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="trainer_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="days_requested",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Leave"),
                    ("sick", "Sick Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("emergency", "Emergency Leave"),
                    ("study", "Study Leave"),
                    ("bereavement", "Bereavement Leave"),
                    ("compensatory", "Compensatory Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="goals",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="overall_rating",
            field=models.CharField(
                choices=[
                    ("outstanding", "Outstanding (5)"),
                    ("excellent", "Excellent (4)"),
                    ("good", "Good (3)"),
                    ("satisfactory", "Satisfactory (2)"),
                    ("needs_improvement", "Needs Improvement (1)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="strengths",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="performancereview",
            name="weaknesses",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="hospital.trainingprogram",
            ),
        ),
        migrations.CreateModel(
            name="PerformanceKPIRating",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("score", models.DecimalField(decimal_places=1, max_digits=3)),
                ("comments", models.TextField(blank=True)),
                ("evidence", models.TextField(blank=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.performancekpi",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_ratings",
                        to="hospital.performancereview",
                    ),
                ),
            ],
            options={
                "ordering": ["kpi__category", "kpi__kpi_name"],
                "unique_together": {("review", "kpi")},
            },
        ),
    ]
