# Generated by Django 4.2.7 on 2025-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0025_enhance_hr_leave_training"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="address",
            field=models.TextField(blank=True, help_text="Residential address"),
        ),
        migrations.AddField(
            model_name="staff",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="staff",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name="staff",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On Leave"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="license_number",
            field=models.CharField(
                blank=True, help_text="Professional license number", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Single"),
                    ("married", "Married"),
                    ("divorced", "Divorced"),
                    ("widowed", "Widowed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="personal_email",
            field=models.EmailField(
                blank=True, help_text="Personal email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="specialization",
            field=models.CharField(
                blank=True, help_text="Area of specialization", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about staff member"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="employee_id",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Medical council registration number",
                max_length=50,
            ),
        ),
    ]
