# Generated by Django 4.2.7 on 2025-11-04 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0026_enhance_staff_auto_id_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        default="Hospital Management System", max_length=200
                    ),
                ),
                (
                    "hospital_tagline",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'Quality Healthcare for All'",
                        max_length=200,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(default="Ghana", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Hospital logo for reports and letterheads",
                        null=True,
                        upload_to="hospital_settings/",
                    ),
                ),
                (
                    "logo_width",
                    models.IntegerField(
                        default=150, help_text="Logo width in pixels for reports"
                    ),
                ),
                (
                    "logo_height",
                    models.IntegerField(
                        default=150, help_text="Logo height in pixels for reports"
                    ),
                ),
                (
                    "report_header_color",
                    models.CharField(
                        default="#2196F3",
                        help_text="Hex color code for report headers",
                        max_length=7,
                    ),
                ),
                (
                    "report_footer_text",
                    models.TextField(
                        blank=True, help_text="Footer text for printed reports"
                    ),
                ),
                (
                    "lab_department_name",
                    models.CharField(default="Clinical Laboratory", max_length=200),
                ),
                ("lab_phone", models.CharField(blank=True, max_length=50)),
                ("lab_email", models.EmailField(blank=True, max_length=254)),
                (
                    "lab_accreditation",
                    models.CharField(
                        blank=True, help_text="E.g., ISO 15189:2012", max_length=200
                    ),
                ),
                ("lab_license_number", models.CharField(blank=True, max_length=100)),
                (
                    "radiology_department_name",
                    models.CharField(default="Radiology Department", max_length=200),
                ),
                ("radiology_phone", models.CharField(blank=True, max_length=50)),
                ("radiology_email", models.EmailField(blank=True, max_length=254)),
                (
                    "pharmacy_department_name",
                    models.CharField(default="Hospital Pharmacy", max_length=200),
                ),
                ("pharmacy_phone", models.CharField(blank=True, max_length=50)),
                (
                    "pharmacy_license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("currency", models.CharField(default="GHS", max_length=10)),
                ("currency_symbol", models.CharField(default="₵", max_length=5)),
                (
                    "date_format",
                    models.CharField(
                        default="%d/%m/%Y",
                        help_text="Python date format",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        default="%H:%M", help_text="Python time format", max_length=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Settings",
                "verbose_name_plural": "Hospital Settings",
            },
        ),
    ]
