# Generated by Django 4.2.7 on 2025-11-05 17:50

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0027_hospitalsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisCode",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ICD-10 Code (e.g., J18.9)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Full description of the diagnosis", max_length=500
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, help_text="Short/Common name", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("infectious", "Infectious and Parasitic Diseases"),
                            ("neoplasms", "Neoplasms"),
                            ("blood", "Diseases of Blood and Blood-forming Organs"),
                            (
                                "endocrine",
                                "Endocrine, Nutritional and Metabolic Diseases",
                            ),
                            ("mental", "Mental and Behavioral Disorders"),
                            ("nervous", "Diseases of the Nervous System"),
                            ("eye", "Diseases of the Eye and Adnexa"),
                            ("ear", "Diseases of the Ear and Mastoid Process"),
                            ("circulatory", "Diseases of the Circulatory System"),
                            ("respiratory", "Diseases of the Respiratory System"),
                            ("digestive", "Diseases of the Digestive System"),
                            ("skin", "Diseases of the Skin and Subcutaneous Tissue"),
                            (
                                "musculoskeletal",
                                "Diseases of the Musculoskeletal System",
                            ),
                            ("genitourinary", "Diseases of the Genitourinary System"),
                            ("pregnancy", "Pregnancy, Childbirth and the Puerperium"),
                            (
                                "perinatal",
                                "Conditions Originating in the Perinatal Period",
                            ),
                            ("congenital", "Congenital Malformations"),
                            (
                                "symptoms",
                                "Symptoms, Signs and Abnormal Clinical Findings",
                            ),
                            ("injury", "Injury, Poisoning and External Causes"),
                            ("external", "External Causes of Morbidity"),
                            ("other", "Other Factors"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        blank=True,
                        help_text="ICD-10 Chapter (e.g., J00-J99)",
                        max_length=10,
                    ),
                ),
                (
                    "is_common",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Mark as commonly used diagnosis",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0, help_text="Track how often this code is used"
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis Code (ICD-10)",
                "verbose_name_plural": "Diagnosis Codes (ICD-10)",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="hospital_di_code_e790ba_idx"),
                    models.Index(
                        fields=["category", "is_common"],
                        name="hospital_di_categor_1df877_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_common"],
                        name="hospital_di_is_acti_cb6192_idx",
                    ),
                ],
            },
        ),
    ]
