# Generated by Django 4.2.7 on 2025-11-05 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0028_diagnosiscode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vitalsign",
            options={
                "ordering": ["-recorded_at"],
                "verbose_name": "Vital Signs",
                "verbose_name_plural": "Vital Signs",
            },
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="blood_glucose",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="mmol/L or mg/dL",
                max_digits=5,
                null=True,
                verbose_name="Blood Glucose",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="capillary_refill",
            field=models.PositiveIntegerField(
                blank=True, help_text="seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="consciousness_level",
            field=models.CharField(
                choices=[
                    ("alert", "Alert"),
                    ("cvpu", "Confusion/New Disorientation"),
                    ("voice", "Responds to Voice"),
                    ("pain", "Responds to Pain"),
                    ("unresponsive", "Unresponsive"),
                ],
                default="alert",
                max_length=20,
                verbose_name="Level of Consciousness",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="is_critical",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Flagged as critical/abnormal"
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="mews_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Modified Early Warning Score",
                null=True,
                verbose_name="MEWS Score",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="news2_score",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="National Early Warning Score 2",
                null=True,
                verbose_name="NEWS2 Score",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="oxygen_flow_rate",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="L/min", max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="pain_score",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "0 - No Pain"),
                    (1, "1 - Minimal"),
                    (2, "2 - Mild"),
                    (3, "3 - Uncomfortable"),
                    (4, "4 - Moderate"),
                    (5, "5 - Distressing"),
                    (6, "6 - Severe"),
                    (7, "7 - Very Severe"),
                    (8, "8 - Intense"),
                    (9, "9 - Excruciating"),
                    (10, "10 - Unbearable"),
                ],
                null=True,
                verbose_name="Pain Score (0-10)",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sitting", "Sitting"),
                    ("standing", "Standing"),
                    ("lying", "Lying"),
                    ("supine", "Supine"),
                ],
                help_text="Patient position during measurement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="requires_escalation",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Requires immediate medical attention",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="supplemental_oxygen",
            field=models.BooleanField(default=False, verbose_name="On Supplemental O2"),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="diastolic_bp",
            field=models.PositiveIntegerField(
                blank=True, help_text="mmHg", null=True, verbose_name="Diastolic BP"
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="height",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="cm", max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Clinical Notes"),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="pulse",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="beats per minute",
                null=True,
                verbose_name="Heart Rate/Pulse",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="recorded_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="respiratory_rate",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="breaths per minute",
                null=True,
                verbose_name="Respiratory Rate",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="spo2",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="percentage",
                null=True,
                verbose_name="SpO2 (Oxygen Saturation)",
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="systolic_bp",
            field=models.PositiveIntegerField(
                blank=True, help_text="mmHg", null=True, verbose_name="Systolic BP"
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="temperature",
            field=models.DecimalField(
                blank=True, decimal_places=1, help_text="°C", max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vitalsign",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, help_text="kg", max_digits=5, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="vitalsign",
            index=models.Index(
                fields=["-recorded_at", "encounter"],
                name="hospital_vi_recorde_a16700_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vitalsign",
            index=models.Index(
                fields=["is_critical", "requires_escalation"],
                name="hospital_vi_is_crit_df93b8_idx",
            ),
        ),
    ]
