# Generated by Django 4.2.7 on 2025-11-06 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0029_alter_vitalsign_options_vitalsign_blood_glucose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePaymentRequirement",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("lab_test", "Laboratory Test"),
                            ("lab_result", "Laboratory Result Release"),
                            ("pharmacy_prescription", "Pharmacy Prescription"),
                            ("pharmacy_otc", "Pharmacy OTC Sale"),
                            ("imaging_study", "Imaging Study"),
                            ("procedure", "Medical Procedure"),
                            ("consultation", "Consultation Fee"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "requires_prepayment",
                    models.BooleanField(
                        default=True, help_text="Must pay before service delivery"
                    ),
                ),
                (
                    "allow_credit",
                    models.BooleanField(
                        default=False, help_text="Allow credit for this service"
                    ),
                ),
                (
                    "credit_limit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "grace_period_hours",
                    models.PositiveIntegerField(
                        default=0, help_text="Hours to pay after service"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["service_type"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptQRCode",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("qr_code_data", models.TextField(help_text="Data encoded in QR code")),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="receipt_qr_codes/"
                    ),
                ),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="hospital.paymentreceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyDispensing",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("payment_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispensing_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("ready_to_dispense", "Ready to Dispense"),
                            ("partially_dispensed", "Partially Dispensed"),
                            ("fully_dispensed", "Fully Dispensed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=30,
                    ),
                ),
                ("quantity_ordered", models.PositiveIntegerField()),
                ("quantity_dispensed", models.PositiveIntegerField(default=0)),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dispensing_instructions",
                    models.TextField(
                        blank=True, help_text="Instructions given to patient"
                    ),
                ),
                ("counselling_given", models.BooleanField(default=False)),
                ("dispensing_notes", models.TextField(blank=True)),
                (
                    "counselled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counselled_patients",
                        to="hospital.staff",
                    ),
                ),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_medications",
                        to="hospital.staff",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_dispensing",
                        to="hospital.patient",
                    ),
                ),
                (
                    "payment_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.paymentreceipt",
                    ),
                ),
                (
                    "payment_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_pharmacy_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prescription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensing_record",
                        to="hospital.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PaymentVerification",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("lab_test", "Laboratory Test"),
                            ("lab_result", "Laboratory Result Release"),
                            ("pharmacy_prescription", "Pharmacy Prescription"),
                            ("pharmacy_otc", "Pharmacy OTC Sale"),
                            ("imaging_study", "Imaging Study"),
                            ("procedure", "Medical Procedure"),
                            ("consultation", "Consultation Fee"),
                        ],
                        max_length=30,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("qr_scan", "QR Code Scan"),
                            ("barcode", "Barcode Scan"),
                            ("receipt_number", "Receipt Number"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "scanned_data",
                    models.TextField(blank=True, help_text="QR/Barcode data"),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "imaging_study",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_verifications",
                        to="hospital.imagingstudy",
                    ),
                ),
                (
                    "lab_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_verifications",
                        to="hospital.labresult",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_verifications",
                        to="hospital.prescription",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="hospital.paymentreceipt",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LabResultRelease",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("payment_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "release_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending Payment"),
                            ("ready_for_release", "Ready for Release"),
                            ("released", "Released to Patient"),
                            ("emailed", "Emailed to Patient"),
                        ],
                        default="pending_payment",
                        max_length=30,
                    ),
                ),
                (
                    "released_to",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who collected",
                        max_length=200,
                    ),
                ),
                (
                    "released_to_relationship",
                    models.CharField(
                        blank=True, help_text="Relationship to patient", max_length=100
                    ),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., National ID, Passport",
                        max_length=50,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=100)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("in_person", "Collected in Person"),
                            ("email", "Emailed"),
                            ("proxy", "Collected by Proxy"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                (
                    "lab_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_record",
                        to="hospital.labresult",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_result_releases",
                        to="hospital.patient",
                    ),
                ),
                (
                    "payment_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.paymentreceipt",
                    ),
                ),
                (
                    "payment_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_lab_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_lab_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
