# Generated by Django 4.2.7 on 2025-11-06 15:15

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0030_servicepaymentrequirement_receiptqrcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("package_code", models.CharField(max_length=50, unique=True)),
                (
                    "included_services",
                    models.JSONField(
                        default=list, help_text="List of included services with codes"
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sum of individual service prices",
                        max_digits=10,
                    ),
                ),
                (
                    "package_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discounted package price",
                        max_digits=10,
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePriceList",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "payer_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Payment"),
                            ("nhis", "NHIS"),
                            ("private_insurance", "Private Insurance"),
                            ("corporate", "Corporate"),
                            ("staff", "Staff Discount"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="Price list name", max_length=200)),
                ("description", models.TextField(blank=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overall discount % (e.g., 10.00 for 10%)",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Price List",
                "verbose_name_plural": "Service Price Lists",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ProcedurePrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("minor_surgery", "Minor Surgery"),
                            ("major_surgery", "Major Surgery"),
                            ("dental", "Dental Procedure"),
                            ("ophthalmic", "Ophthalmic Procedure"),
                            ("endoscopy", "Endoscopy"),
                            ("biopsy", "Biopsy"),
                            ("injection", "Injection"),
                            ("wound_care", "Wound Care"),
                            ("catheterization", "Catheterization"),
                            ("other", "Other Procedure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("procedure_name", models.CharField(max_length=200)),
                ("procedure_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("includes_anesthesia", models.BooleanField(default=False)),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=30)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_prices",
                        to="hospital.servicepricelist",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "procedure_name"],
            },
        ),
        migrations.CreateModel(
            name="ImagingPrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "imaging_type",
                    models.CharField(
                        choices=[
                            ("xray", "X-Ray"),
                            ("ct", "CT Scan"),
                            ("mri", "MRI"),
                            ("ultrasound", "Ultrasound"),
                            ("mammography", "Mammography"),
                            ("fluoroscopy", "Fluoroscopy"),
                            ("dexa", "DEXA Scan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        help_text="e.g., Chest, Abdomen, Brain", max_length=100
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_prices",
                        to="hospital.servicepricelist",
                    ),
                ),
            ],
            options={
                "ordering": ["imaging_type", "body_part"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationPrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "encounter_type",
                    models.CharField(
                        choices=[
                            ("outpatient", "Outpatient Consultation"),
                            ("inpatient", "Inpatient Daily Care"),
                            ("er", "Emergency Visit"),
                            ("specialist", "Specialist Consultation"),
                            ("followup", "Follow-up Visit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific department (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.department",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_prices",
                        to="hospital.servicepricelist",
                    ),
                ),
            ],
            options={
                "ordering": ["encounter_type"],
                "unique_together": {("price_list", "encounter_type", "department")},
            },
        ),
        migrations.CreateModel(
            name="BedPrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("general_ward", "General Ward"),
                            ("semi_private", "Semi-Private Room"),
                            ("private", "Private Room"),
                            ("vip", "VIP Suite"),
                            ("icu", "ICU"),
                            ("nicu", "NICU"),
                            ("maternity", "Maternity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bed_prices",
                        to="hospital.servicepricelist",
                    ),
                ),
            ],
            options={
                "ordering": ["bed_type"],
                "unique_together": {("price_list", "bed_type")},
            },
        ),
    ]
