# Generated by Django 4.2.7 on 2025-11-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0031_servicepackage_servicepricelist_procedureprice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Cost from supplier",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Selling price per unit",
                max_digits=10,
            ),
        ),
    ]
