# Generated by Django 4.2.7 on 2025-11-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0032_add_drug_pricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalledger",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="generalledger",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_type",
            field=models.CharField(blank=True, default="manual", max_length=50),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posted_journal_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("posted", "Posted"), ("void", "Void")],
                default="posted",
                max_length=20,
            ),
        ),
    ]
