# Generated by Django 4.2.7 on 2025-11-07 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0033_add_accounting_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="service_details",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional service details"
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lab", "Laboratory Test"),
                    ("pharmacy", "Pharmacy/Medication"),
                    ("imaging", "Imaging/Radiology"),
                    ("imaging_study", "Imaging Study"),
                    ("consultation", "Consultation"),
                    ("admission", "Admission"),
                    ("procedure", "Procedure"),
                    ("combined", "Combined Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "sms_enabled",
                    models.BooleanField(
                        default=True, help_text="Receive SMS notifications"
                    ),
                ),
                (
                    "whatsapp_enabled",
                    models.BooleanField(
                        default=False, help_text="Receive WhatsApp messages"
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False, help_text="Receive email notifications"
                    ),
                ),
                (
                    "sms_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Phone number for SMS (uses patient phone if empty)",
                        max_length=17,
                    ),
                ),
                (
                    "whatsapp_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp number (uses SMS phone if empty)",
                        max_length=17,
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        help_text="Email address (uses patient email if empty)",
                        max_length=254,
                    ),
                ),
                (
                    "lab_results_notify",
                    models.BooleanField(
                        default=True, help_text="Notify when lab results are ready"
                    ),
                ),
                (
                    "appointment_notify",
                    models.BooleanField(
                        default=True, help_text="Appointment reminders"
                    ),
                ),
                (
                    "payment_notify",
                    models.BooleanField(default=True, help_text="Payment reminders"),
                ),
                (
                    "prescription_notify",
                    models.BooleanField(
                        default=True, help_text="Prescription ready notifications"
                    ),
                ),
                (
                    "send_full_results",
                    models.BooleanField(
                        default=False,
                        help_text="Include full lab results in notification (if false, just notify that results are ready)",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="MultiChannelNotificationLog",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("lab_result", "Lab Result Ready"),
                            ("appointment_reminder", "Appointment Reminder"),
                            ("payment_reminder", "Payment Reminder"),
                            ("prescription_ready", "Prescription Ready"),
                            ("general", "General Notification"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "message_body",
                    models.TextField(help_text="Main notification message"),
                ),
                (
                    "channels_attempted",
                    models.JSONField(
                        default=list,
                        help_text="List of channels tried: ['sms', 'whatsapp', 'email']",
                    ),
                ),
                (
                    "channels_successful",
                    models.JSONField(
                        default=list, help_text="List of channels that succeeded"
                    ),
                ),
                (
                    "channels_failed",
                    models.JSONField(
                        default=list, help_text="List of channels that failed"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent (at least one channel)"),
                            ("delivered", "Delivered (at least one channel)"),
                            ("failed", "Failed (all channels)"),
                            ("partial", "Partial (some channels failed)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("related_object_id", models.CharField(blank=True, max_length=100)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "channel_responses",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed responses from each channel: {'sms': {...}, 'whatsapp': {...}, 'email': {...}}",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_notifications",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multi-Channel Notification Log",
                "verbose_name_plural": "Multi-Channel Notification Logs",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created", "notification_type"],
                        name="hospital_mu_created_7ce517_idx",
                    ),
                    models.Index(
                        fields=["patient", "-created"],
                        name="hospital_mu_patient_ba8541_idx",
                    ),
                    models.Index(
                        fields=["status"], name="hospital_mu_status_8e7924_idx"
                    ),
                ],
            },
        ),
    ]
