# Generated by Django 4.2.7 on 2025-11-07 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0034_add_notification_system_and_payment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueEntry",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "queue_number",
                    models.CharField(
                        help_text="Unique queue number (e.g., OPD-042)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "queue_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date when queue entry was created"
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        help_text="Daily sequence number (resets daily)"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "🔴 Emergency - Immediate"),
                            (2, "🟠 Urgent - High Priority"),
                            (3, "🟢 Normal - Standard"),
                            (4, "🔵 Follow-up - Lower Priority"),
                        ],
                        default=3,
                        help_text="Queue priority (1=Emergency, 3=Normal)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("checked_in", "✅ Checked In - Waiting"),
                            ("called", "📢 Called - Please Proceed"),
                            ("in_progress", "👨\u200d⚕️ In Consultation"),
                            ("completed", "✓ Completed"),
                            ("no_show", "❌ No Show"),
                            ("cancelled", "🚫 Cancelled"),
                        ],
                        default="checked_in",
                        max_length=20,
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When patient checked in"
                    ),
                ),
                (
                    "called_time",
                    models.DateTimeField(
                        blank=True, help_text="When patient was called", null=True
                    ),
                ),
                (
                    "started_time",
                    models.DateTimeField(
                        blank=True, help_text="When consultation started", null=True
                    ),
                ),
                (
                    "completed_time",
                    models.DateTimeField(
                        blank=True, help_text="When consultation completed", null=True
                    ),
                ),
                (
                    "estimated_wait_minutes",
                    models.IntegerField(
                        default=0, help_text="Estimated wait time in minutes"
                    ),
                ),
                (
                    "actual_wait_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Actual wait time from check-in to consultation",
                        null=True,
                    ),
                ),
                (
                    "consultation_duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of consultation in minutes",
                        null=True,
                    ),
                ),
                (
                    "sms_sent",
                    models.BooleanField(
                        default=False, help_text="Whether check-in SMS was sent"
                    ),
                ),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_notification_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_count",
                    models.IntegerField(
                        default=0, help_text="Number of notifications sent"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True,
                        help_text="Consultation room assignment",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or special instructions"
                    ),
                ),
                (
                    "no_show",
                    models.BooleanField(
                        default=False, help_text="Patient did not show up when called"
                    ),
                ),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"groups__name": "Doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queue_entries",
                        to="hospital.department",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entry",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Entry",
                "verbose_name_plural": "Queue Entries",
                "ordering": ["queue_date", "priority", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="QueueNotification",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check-in Confirmation"),
                            ("progress_update", "Queue Progress Update"),
                            ("ready", "Ready for Consultation"),
                            ("no_show_warning", "No Show Warning"),
                            ("completed", "Consultation Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                        ],
                        default="sms",
                        max_length=20,
                    ),
                ),
                (
                    "message_content",
                    models.TextField(help_text="Full message content sent"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivered",
                    models.BooleanField(
                        default=False, help_text="Whether message was delivered"
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether message was read (if trackable)",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External provider message ID (for tracking)",
                        max_length=100,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if notification failed"
                    ),
                ),
                (
                    "queue_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="hospital.queueentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Notification",
                "verbose_name_plural": "Queue Notifications",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueConfiguration",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "queue_prefix",
                    models.CharField(
                        default="OPD",
                        help_text="Prefix for queue numbers (e.g., OPD, EMG, SPL)",
                        max_length=5,
                    ),
                ),
                (
                    "enable_queue",
                    models.BooleanField(
                        default=True,
                        help_text="Enable queue management for this department",
                    ),
                ),
                (
                    "average_consultation_minutes",
                    models.IntegerField(
                        default=15, help_text="Average consultation time in minutes"
                    ),
                ),
                (
                    "buffer_time_minutes",
                    models.IntegerField(
                        default=5, help_text="Buffer time between consultations"
                    ),
                ),
                (
                    "send_check_in_sms",
                    models.BooleanField(default=True, help_text="Send SMS on check-in"),
                ),
                (
                    "send_progress_updates",
                    models.BooleanField(
                        default=True, help_text="Send periodic queue progress updates"
                    ),
                ),
                (
                    "send_ready_notification",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification when patient's turn is ready",
                    ),
                ),
                (
                    "notification_interval_patients",
                    models.IntegerField(
                        default=5,
                        help_text="Send update every N patients (e.g., every 5 patients)",
                    ),
                ),
                (
                    "show_on_public_display",
                    models.BooleanField(
                        default=True, help_text="Show queue on public TV displays"
                    ),
                ),
                (
                    "display_upcoming_count",
                    models.IntegerField(
                        default=5,
                        help_text="Number of upcoming patients to show on display",
                    ),
                ),
                (
                    "default_room_number",
                    models.CharField(
                        blank=True, help_text="Default consultation room", max_length=20
                    ),
                ),
                (
                    "department",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_config",
                        to="hospital.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Queue Configuration",
                "verbose_name_plural": "Queue Configurations",
            },
        ),
        migrations.AddIndex(
            model_name="queueentry",
            index=models.Index(
                fields=["queue_date", "department", "status"],
                name="hospital_qu_queue_d_01528a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="queueentry",
            index=models.Index(
                fields=["queue_number"], name="hospital_qu_queue_n_3113ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queueentry",
            index=models.Index(
                fields=["queue_date", "status"], name="hospital_qu_queue_d_ee1fa0_idx"
            ),
        ),
    ]
