# Generated by Django 4.2.7 on 2025-11-07 13:45

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0035_queueentry_queuenotification_queueconfiguration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ARAgingSnapshot",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "snapshot_date",
                    models.DateField(help_text="Date of this AR snapshot", unique=True),
                ),
                (
                    "current_0_30",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Outstanding 0-30 days",
                        max_digits=12,
                    ),
                ),
                (
                    "days_31_60",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Outstanding 31-60 days",
                        max_digits=12,
                    ),
                ),
                (
                    "days_61_90",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Outstanding 61-90 days",
                        max_digits=12,
                    ),
                ),
                (
                    "days_91_120",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Outstanding 91-120 days",
                        max_digits=12,
                    ),
                ),
                (
                    "days_over_120",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Outstanding over 120 days",
                        max_digits=12,
                    ),
                ),
                (
                    "total_outstanding",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total AR balance",
                        max_digits=12,
                    ),
                ),
                (
                    "cash_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "corporate_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "insurance_outstanding",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("total_accounts", models.IntegerField(default=0)),
                ("overdue_accounts", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "AR Aging Snapshot",
                "verbose_name_plural": "AR Aging Snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="CorporateAccount",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company_name",
                    models.CharField(
                        help_text="Official company name", max_length=200, unique=True
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        help_text="Unique identifier code for the company",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Business registration number",
                        max_length=50,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, help_text="Tax identification number", max_length=50
                    ),
                ),
                ("billing_contact_name", models.CharField(max_length=200)),
                (
                    "billing_email",
                    models.EmailField(
                        help_text="Primary email for invoices", max_length=254
                    ),
                ),
                ("billing_phone", models.CharField(max_length=20)),
                ("billing_address", models.TextField()),
                (
                    "accounts_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("hr_contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Maximum outstanding balance allowed",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_terms_days",
                    models.IntegerField(
                        default=30, help_text="Payment due within X days (e.g., Net 30)"
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current outstanding balance",
                        max_digits=12,
                    ),
                ),
                (
                    "credit_status",
                    models.CharField(
                        choices=[
                            ("active", "✅ Active - Good Standing"),
                            ("suspended", "⚠️ Suspended - Credit Limit Exceeded"),
                            ("on_hold", "🔒 On Hold - Payment Issues"),
                            ("collection", "⛔ In Collection"),
                            ("closed", "❌ Account Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly - End of Month"),
                            ("bi_weekly", "Bi-Weekly"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom Schedule"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "billing_day_of_month",
                    models.IntegerField(
                        default=1, help_text="Day of month to generate statement (1-31)"
                    ),
                ),
                ("next_billing_date", models.DateField()),
                ("last_billing_date", models.DateField(blank=True, null=True)),
                (
                    "global_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Discount applied to all services",
                        max_digits=5,
                    ),
                ),
                ("contract_start_date", models.DateField()),
                (
                    "contract_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for ongoing contracts",
                        null=True,
                    ),
                ),
                (
                    "contract_document",
                    models.FileField(blank=True, upload_to="contracts/"),
                ),
                ("contract_notes", models.TextField(blank=True)),
                (
                    "send_statement_email",
                    models.BooleanField(
                        default=True, help_text="Email monthly statements"
                    ),
                ),
                (
                    "send_payment_reminders",
                    models.BooleanField(
                        default=True, help_text="Send automated payment reminders"
                    ),
                ),
                (
                    "reminder_days_before_due",
                    models.IntegerField(
                        default=7, help_text="Days before due date to send reminder"
                    ),
                ),
                ("total_employees_enrolled", models.IntegerField(default=0)),
                (
                    "lifetime_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "average_monthly_billing",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "require_pre_authorization",
                    models.BooleanField(
                        default=False, help_text="Require approval before services"
                    ),
                ),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_corporate_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "price_book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Custom price book for this company",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.pricebook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Account",
                "verbose_name_plural": "Corporate Accounts",
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyStatement",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "statement_number",
                    models.CharField(
                        help_text="Unique statement identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "statement_date",
                    models.DateField(help_text="Date statement was generated"),
                ),
                ("period_start", models.DateField(help_text="Billing period start")),
                ("period_end", models.DateField(help_text="Billing period end")),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Balance brought forward from previous statement",
                        max_digits=12,
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total new charges this period",
                        max_digits=12,
                    ),
                ),
                (
                    "total_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Payments received this period",
                        max_digits=12,
                    ),
                ),
                (
                    "total_adjustments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Adjustments/credits",
                        max_digits=12,
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount due",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_line_items",
                    models.IntegerField(
                        default=0, help_text="Number of service transactions"
                    ),
                ),
                (
                    "total_patients_served",
                    models.IntegerField(
                        default=0, help_text="Number of unique patients"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("written_off", "Written Off"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(help_text="Payment due by this date")),
                (
                    "payment_terms",
                    models.CharField(default="Net 30 days", max_length=100),
                ),
                ("sent_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sent_via",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("post", "Post"),
                            ("both", "Email & Post"),
                            ("portal", "Online Portal"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("sent_to_email", models.EmailField(blank=True, max_length=254)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF statement",
                        upload_to="statements/%Y/%m/",
                    ),
                ),
                ("last_payment_date", models.DateField(blank=True, null=True)),
                (
                    "last_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reminder_count",
                    models.IntegerField(
                        default=0, help_text="Number of payment reminders sent"
                    ),
                ),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Notes not visible to client"
                    ),
                ),
                (
                    "corporate_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="hospital.corporateaccount",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_statements",
                        to="hospital.payer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Statement",
                "verbose_name_plural": "Monthly Statements",
                "ordering": ["-statement_date"],
            },
        ),
        migrations.CreateModel(
            name="CorporateEmployee",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Company employee ID number", max_length=50
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("designation", models.CharField(blank=True, max_length=100)),
                ("employee_email", models.EmailField(blank=True, max_length=254)),
                ("enrollment_date", models.DateField(auto_now_add=True)),
                (
                    "termination_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when employee left company",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("has_annual_limit", models.BooleanField(default=False)),
                (
                    "annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum coverage per year",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "utilized_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Amount used this year",
                        max_digits=10,
                    ),
                ),
                (
                    "limit_reset_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when limit resets (usually Jan 1)",
                        null=True,
                    ),
                ),
                ("covers_dependents", models.BooleanField(default=False)),
                ("number_of_dependents", models.IntegerField(default=0)),
                (
                    "dependent_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "corporate_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="hospital.corporateaccount",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_enrollments",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Employee",
                "verbose_name_plural": "Corporate Employees",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="StatementLine",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "service_date",
                    models.DateField(help_text="Date service was provided"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, help_text="Company employee ID", max_length=50
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Service category (Consultation, Lab, Pharmacy, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final amount for this line",
                        max_digits=12,
                    ),
                ),
                ("provider_name", models.CharField(blank=True, max_length=200)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.encounter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.patient",
                    ),
                ),
                (
                    "service_code",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.servicecode",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hospital.monthlystatement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement Line",
                "verbose_name_plural": "Statement Lines",
                "ordering": ["service_date", "patient__last_name"],
                "indexes": [
                    models.Index(
                        fields=["statement", "service_date"],
                        name="hospital_st_stateme_d58965_idx",
                    ),
                    models.Index(
                        fields=["patient"], name="hospital_st_patient_a851c1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServicePricing",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "cash_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Walk-in/Cash patient price",
                        max_digits=10,
                    ),
                ),
                (
                    "corporate_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard corporate contracted price",
                        max_digits=10,
                    ),
                ),
                (
                    "insurance_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard insurance negotiated price",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(help_text="Price effective from this date"),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True, help_text="Leave blank for ongoing", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "custom_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Custom negotiated price for this payer",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("pricing_notes", models.TextField(blank=True)),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific payer (corporate/insurance) for custom pricing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.payer",
                    ),
                ),
                (
                    "service_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="hospital.servicecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Pricing",
                "verbose_name_plural": "Service Pricing",
                "ordering": ["-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["service_code", "is_active"],
                        name="hospital_se_service_009f8b_idx",
                    ),
                    models.Index(
                        fields=["payer", "is_active"],
                        name="hospital_se_payer_i_002400_idx",
                    ),
                    models.Index(
                        fields=["effective_from", "effective_to"],
                        name="hospital_se_effecti_37253a_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="monthlystatement",
            index=models.Index(
                fields=["statement_number"], name="hospital_mo_stateme_7711a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlystatement",
            index=models.Index(fields=["status"], name="hospital_mo_status_d10aaf_idx"),
        ),
        migrations.AddIndex(
            model_name="monthlystatement",
            index=models.Index(
                fields=["due_date"], name="hospital_mo_due_dat_535e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monthlystatement",
            index=models.Index(
                fields=["statement_date"], name="hospital_mo_stateme_138204_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporateemployee",
            index=models.Index(
                fields=["employee_id"], name="hospital_co_employe_dc6362_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporateemployee",
            index=models.Index(
                fields=["is_active"], name="hospital_co_is_acti_a53953_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="corporateemployee",
            unique_together={("corporate_account", "patient")},
        ),
        migrations.AddIndex(
            model_name="corporateaccount",
            index=models.Index(
                fields=["company_code"], name="hospital_co_company_eed2c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporateaccount",
            index=models.Index(
                fields=["credit_status"], name="hospital_co_credit__464fc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporateaccount",
            index=models.Index(
                fields=["next_billing_date"], name="hospital_co_next_bi_f9cd86_idx"
            ),
        ),
    ]
