# Generated by Django 4.2.7 on 2025-11-08 08:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0036_aragingsnapshot_corporateaccount_monthlystatement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Company Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the company (e.g., NHIS, GLICO)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.TextField(blank=True)),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        help_text="Contract/Agreement number with hospital",
                        max_length=100,
                    ),
                ),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "payment_terms_days",
                    models.IntegerField(
                        default=30,
                        help_text="Number of days for payment (e.g., NET 30)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="General discount % offered by hospital",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("billing_contact_name", models.CharField(blank=True, max_length=200)),
                ("billing_contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "billing_contact_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                (
                    "billing_address",
                    models.TextField(
                        blank=True, help_text="Address for sending claims"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Can patients register with this insurance?",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this insurance company",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="insurance_logos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Company",
                "verbose_name_plural": "Insurance Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InsurancePlan",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("plan_name", models.CharField(max_length=200)),
                (
                    "plan_code",
                    models.CharField(
                        help_text="Unique code for this plan",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Coverage"),
                            ("standard", "Standard Coverage"),
                            ("premium", "Premium Coverage"),
                            ("corporate", "Corporate Plan"),
                            ("family", "Family Plan"),
                            ("individual", "Individual Plan"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this plan covers"),
                ),
                (
                    "consultation_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="% covered for consultations",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "lab_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="% covered for lab tests",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "imaging_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="% covered for imaging/X-rays",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "pharmacy_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("80.00"),
                        help_text="% covered for medications",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "surgery_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("90.00"),
                        help_text="% covered for surgical procedures",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "admission_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="% covered for hospital admissions",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "annual_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum coverage per year (GHS). Leave blank for unlimited.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "consultation_limit_per_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Max consultations per year. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "requires_pre_authorization",
                    models.BooleanField(
                        default=False,
                        help_text="Does this plan require pre-authorization?",
                    ),
                ),
                (
                    "copay_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed copay amount per visit (GHS)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_date",
                    models.DateField(help_text="Date this plan becomes effective"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this plan expires (leave blank for no expiry)",
                        null=True,
                    ),
                ),
                (
                    "exclusions",
                    models.TextField(
                        blank=True, help_text="What is NOT covered by this plan"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="hospital.insurancecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Plan",
                "verbose_name_plural": "Insurance Plans",
                "ordering": ["insurance_company", "plan_name"],
            },
        ),
        migrations.CreateModel(
            name="PatientInsurance",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "policy_number",
                    models.CharField(
                        help_text="Insurance policy number", max_length=100
                    ),
                ),
                (
                    "member_id",
                    models.CharField(help_text="Member/subscriber ID", max_length=100),
                ),
                (
                    "group_number",
                    models.CharField(
                        blank=True, help_text="Group/employer number", max_length=100
                    ),
                ),
                (
                    "is_primary_subscriber",
                    models.BooleanField(
                        default=True, help_text="Is patient the primary policy holder?"
                    ),
                ),
                (
                    "relationship_to_subscriber",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("spouse", "Spouse"),
                            ("child", "Child"),
                            ("parent", "Parent"),
                            ("dependent", "Other Dependent"),
                        ],
                        default="self",
                        max_length=20,
                    ),
                ),
                (
                    "subscriber_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of primary policy holder",
                        max_length=200,
                    ),
                ),
                (
                    "subscriber_dob",
                    models.DateField(
                        blank=True,
                        help_text="Date of birth of primary subscriber",
                        null=True,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date insurance coverage starts"),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, help_text="Date insurance coverage ends", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Is this the patient's primary insurance?",
                    ),
                ),
                (
                    "last_verified_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date insurance was verified",
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        blank=True,
                        help_text="Result of last verification",
                        max_length=50,
                    ),
                ),
                (
                    "consultations_used",
                    models.IntegerField(
                        default=0, help_text="Number of consultations used this year"
                    ),
                ),
                (
                    "amount_used_this_year",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount claimed this year",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "insurance_card_front",
                    models.ImageField(
                        blank=True,
                        help_text="Front of insurance card",
                        null=True,
                        upload_to="insurance_cards/",
                    ),
                ),
                (
                    "insurance_card_back",
                    models.ImageField(
                        blank=True,
                        help_text="Back of insurance card",
                        null=True,
                        upload_to="insurance_cards/",
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_enrollments",
                        to="hospital.insurancecompany",
                    ),
                ),
                (
                    "insurance_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_enrollments",
                        to="hospital.insuranceplan",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Insurance",
                "verbose_name_plural": "Patient Insurances",
                "ordering": ["-is_primary", "-effective_date"],
            },
        ),
        migrations.AddIndex(
            model_name="insurancecompany",
            index=models.Index(fields=["code"], name="hospital_in_code_3c4bd6_idx"),
        ),
        migrations.AddIndex(
            model_name="insurancecompany",
            index=models.Index(fields=["status"], name="hospital_in_status_92c794_idx"),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(
                fields=["patient", "status"], name="hospital_pa_patient_c57257_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(
                fields=["insurance_company", "status"],
                name="hospital_pa_insuran_1889f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(
                fields=["policy_number"], name="hospital_pa_policy__46fe69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientinsurance",
            index=models.Index(
                fields=["member_id"], name="hospital_pa_member__0da44a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceplan",
            index=models.Index(
                fields=["insurance_company", "is_active"],
                name="hospital_in_insuran_2ef170_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceplan",
            index=models.Index(
                fields=["plan_code"], name="hospital_in_plan_co_e392e9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="insuranceplan",
            unique_together={("insurance_company", "plan_name")},
        ),
    ]
