# Generated by Django 4.2.7 on 2025-11-08 08:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0037_add_insurance_companies"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of pricing category (e.g., 'Cash Patients', 'NHIS', 'Corporate XYZ')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g., 'CASH', 'NHIS', 'CORP-XYZ')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Payment"),
                            ("insurance", "Insurance"),
                            ("corporate", "Corporate"),
                            ("government", "Government"),
                            ("discount", "Discounted Rate"),
                            ("premium", "Premium Rate"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this pricing category"
                    ),
                ),
                (
                    "default_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default discount % (negative = markup). E.g., 10 = 10% discount, -20 = 20% markup",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-100"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Priority order for display (lower = higher priority)",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color code for UI display (e.g., #3b82f6)",
                        max_length=7,
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to insurance company if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pricing_categories",
                        to="hospital.insurancecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Category",
                "verbose_name_plural": "Pricing Categories",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServicePrice",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in GHS for this service in this category",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date this price becomes effective",
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(
                        blank=True,
                        help_text="Date this price expires (leave blank for no expiry)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this price"
                    ),
                ),
                (
                    "pricing_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_prices",
                        to="hospital.pricingcategory",
                    ),
                ),
                (
                    "service_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flexible_prices",
                        to="hospital.servicecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Price",
                "verbose_name_plural": "Service Prices",
                "ordering": ["-effective_from", "service_code", "pricing_category"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Price Created"),
                            ("updated", "Price Updated"),
                            ("deleted", "Price Deleted"),
                            ("expired", "Price Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="New price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Reason for price change"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pricing_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="hospital.pricingcategory",
                    ),
                ),
                (
                    "service_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="hospital.servicecode",
                    ),
                ),
                (
                    "service_price",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="hospital.serviceprice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="BulkPriceUpdate",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name/description of this bulk update", max_length=200
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Change"),
                            ("fixed", "Fixed Amount Change"),
                            ("set_price", "Set Specific Prices"),
                        ],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "percentage_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="% change (e.g., 10 = increase by 10%, -10 = decrease by 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "fixed_amount_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed amount change (e.g., 5 = add GHS 5, -5 = subtract GHS 5)",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When the new prices become effective",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "services_affected",
                    models.IntegerField(
                        default=0, help_text="Number of services affected"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "pricing_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target pricing category (leave blank for all)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_updates",
                        to="hospital.pricingcategory",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_price_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Price Update",
                "verbose_name_plural": "Bulk Price Updates",
                "ordering": ["-created"],
            },
        ),
        migrations.AddIndex(
            model_name="serviceprice",
            index=models.Index(
                fields=["service_code", "pricing_category"],
                name="hospital_se_service_34dabf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprice",
            index=models.Index(
                fields=["pricing_category", "is_active"],
                name="hospital_se_pricing_fab25f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="serviceprice",
            index=models.Index(
                fields=["effective_from", "effective_to"],
                name="hospital_se_effecti_9cb531_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="serviceprice",
            unique_together={("service_code", "pricing_category", "effective_from")},
        ),
        migrations.AddIndex(
            model_name="pricingcategory",
            index=models.Index(fields=["code"], name="hospital_pr_code_f34d6e_idx"),
        ),
        migrations.AddIndex(
            model_name="pricingcategory",
            index=models.Index(
                fields=["category_type"], name="hospital_pr_categor_0158c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingcategory",
            index=models.Index(
                fields=["is_active"], name="hospital_pr_is_acti_46bce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["service_code", "-created"],
                name="hospital_pr_service_8fb3a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["pricing_category", "-created"],
                name="hospital_pr_pricing_83d6c4_idx",
            ),
        ),
    ]
