# Generated by Django 4.2.7 on 2025-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0038_add_flexible_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
