# Generated by Django 4.2.7 on 2025-11-08 10:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0039_fix_invoice_due_at_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "contract_number",
                    models.CharField(
                        help_text="Unique contract reference number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "contract_name",
                    models.CharField(
                        help_text="Name/Title of the contract", max_length=300
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Name of the other party (company/vendor)",
                        max_length=300,
                    ),
                ),
                (
                    "company_contact_person",
                    models.CharField(blank=True, max_length=200),
                ),
                ("company_phone", models.CharField(blank=True, max_length=20)),
                ("company_email", models.EmailField(blank=True, max_length=254)),
                ("company_address", models.TextField(blank=True)),
                (
                    "description",
                    models.TextField(help_text="What this contract covers"),
                ),
                (
                    "value_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Contract value in GHS",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="e.g., NET 30, Monthly, Quarterly",
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField(help_text="Contract start date")),
                ("end_date", models.DateField(help_text="Contract end date")),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date for renewal consideration",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("terminated", "Terminated"),
                            ("renewed", "Renewed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=False, help_text="Does this contract auto-renew?"
                    ),
                ),
                (
                    "alert_days_before",
                    models.IntegerField(
                        choices=[
                            (7, "7 days before"),
                            (14, "14 days before"),
                            (30, "30 days before"),
                            (60, "60 days before"),
                            (90, "90 days before"),
                        ],
                        default=30,
                        help_text="Alert X days before expiry",
                    ),
                ),
                ("last_alert_sent", models.DateField(blank=True, null=True)),
                (
                    "contract_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload contract PDF/DOC",
                        null=True,
                        upload_to="contracts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True,
                        help_text="Additional documents",
                        null=True,
                        upload_to="contracts/supporting/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes and comments"
                    ),
                ),
                ("terms_and_conditions", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "ordering": ["-end_date", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ContractCategory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("insurance", "Insurance Companies"),
                            ("supplier", "Suppliers/Vendors"),
                            ("service", "Service Providers"),
                            ("employment", "Employment Contracts"),
                            ("lease", "Lease/Rental"),
                            ("maintenance", "Maintenance Agreements"),
                            ("partnership", "Partnerships"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color_code",
                    models.CharField(
                        default="#3b82f6", help_text="Hex color for UI", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Contract Category",
                "verbose_name_plural": "Contract Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContractRenewal",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "previous_end_date",
                    models.DateField(help_text="Previous contract end date"),
                ),
                ("new_end_date", models.DateField(help_text="New contract end date")),
                (
                    "renewal_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date renewal was processed",
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "new_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "changes_made",
                    models.TextField(
                        blank=True, help_text="What changed in the renewal"
                    ),
                ),
                (
                    "renewal_document",
                    models.FileField(
                        blank=True, null=True, upload_to="contracts/renewals/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="hospital.contract",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_renewals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Renewal",
                "verbose_name_plural": "Contract Renewals",
                "ordering": ["-renewal_date"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="hospital.contractcategory",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                help_text="Hospital staff responsible for this contract",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "certificate_number",
                    models.CharField(
                        help_text="Certificate/License number",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("certificate_name", models.CharField(max_length=300)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("license", "Operating License"),
                            ("accreditation", "Accreditation"),
                            ("certification", "Certification"),
                            ("permit", "Permit"),
                            ("registration", "Registration"),
                            ("insurance", "Insurance Policy"),
                            ("compliance", "Compliance Document"),
                            ("quality", "Quality Certification"),
                            ("staff", "Staff License/Certification"),
                            ("equipment", "Equipment Certification"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        help_text="Organization that issued this certificate",
                        max_length=300,
                    ),
                ),
                ("authority_contact", models.CharField(blank=True, max_length=200)),
                ("authority_phone", models.CharField(blank=True, max_length=20)),
                ("authority_email", models.EmailField(blank=True, max_length=254)),
                (
                    "description",
                    models.TextField(help_text="What this certificate covers"),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True, help_text="Scope of certification/license"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(help_text="Date certificate was issued"),
                ),
                ("expiry_date", models.DateField(help_text="Date certificate expires")),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True, help_text="When to start renewal process", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("pending_renewal", "Pending Renewal"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                (
                    "alert_days_before",
                    models.IntegerField(
                        default=60, help_text="Alert X days before expiry"
                    ),
                ),
                ("last_alert_sent", models.DateField(blank=True, null=True)),
                (
                    "certificate_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload certificate scan/PDF",
                        null=True,
                        upload_to="certificates/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="certificates/supporting/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "renewal_process",
                    models.TextField(
                        blank=True, help_text="Steps required for renewal"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="If linked to a contract",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="hospital.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsible_person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person responsible for renewal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        blank=True,
                        help_text="If this is a staff member's certificate",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["expiry_date", "certificate_name"],
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["contract_number"], name="hospital_co_contrac_ee9580_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["company_name"], name="hospital_co_company_cef8b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["status"], name="hospital_co_status_238392_idx"),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["end_date"], name="hospital_co_end_dat_908ed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["certificate_number"], name="hospital_ce_certifi_125f6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["certificate_type"], name="hospital_ce_certifi_8f39cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["status"], name="hospital_ce_status_482f18_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["expiry_date"], name="hospital_ce_expiry__9188a2_idx"
            ),
        ),
    ]
