# Generated by Django 4.2.7 on 2025-11-08 11:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0040_add_contracts_certificates"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("holiday_name", models.CharField(max_length=200)),
                ("holiday_date", models.DateField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, help_text="Does this holiday occur every year?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Holiday",
                "verbose_name_plural": "Public Holidays",
                "ordering": ["-holiday_date"],
            },
        ),
        migrations.CreateModel(
            name="StaffPerformanceGoal",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("goal_title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("set_date", models.DateField(default=django.utils.timezone.now)),
                ("target_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("achieved", "Achieved"),
                            ("partially_achieved", "Partially Achieved"),
                            ("not_achieved", "Not Achieved"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveIntegerField(default=0, help_text="0-100%"),
                ),
                (
                    "target_value",
                    models.CharField(
                        blank=True,
                        help_text="Target to achieve (e.g., '95% patient satisfaction')",
                        max_length=200,
                    ),
                ),
                ("achieved_value", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_goals",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Goal",
                "verbose_name_plural": "Performance Goals",
                "ordering": ["-target_date", "-set_date"],
            },
        ),
        migrations.CreateModel(
            name="StaffEmploymentContract",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is this the current active contract?"
                    ),
                ),
                (
                    "probation_end_date",
                    models.DateField(
                        blank=True, help_text="End of probation period", null=True
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("annual_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("health_insurance", models.BooleanField(default=True)),
                ("pension_included", models.BooleanField(default=True)),
                (
                    "housing_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("annual_leave_days", models.PositiveIntegerField(default=21)),
                ("sick_leave_days", models.PositiveIntegerField(default=10)),
                (
                    "notice_period_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Notice period in days"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Main contract record with expiry tracking",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_employments",
                        to="hospital.contract",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment_contracts",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Employment Contract",
                "verbose_name_plural": "Staff Employment Contracts",
                "ordering": ["-is_current", "-created"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceCalendar",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("attendance_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                            ("off_duty", "Off Duty"),
                            ("public_holiday", "Public Holiday"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                ("is_late", models.BooleanField(default=False)),
                ("late_by_minutes", models.PositiveIntegerField(default=0)),
                ("is_early_departure", models.BooleanField(default=False)),
                ("early_by_minutes", models.PositiveIntegerField(default=0)),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=4
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=4
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="marked_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_calendar",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Calendar",
                "ordering": ["-attendance_date", "staff"],
                "indexes": [
                    models.Index(
                        fields=["staff", "attendance_date"],
                        name="hospital_at_staff_i_9fcc66_idx",
                    ),
                    models.Index(
                        fields=["attendance_date", "status"],
                        name="hospital_at_attenda_462917_idx",
                    ),
                ],
                "unique_together": {("staff", "attendance_date")},
            },
        ),
    ]
