# Generated by Django 4.2.7 on 2025-11-08 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "0041_add_worldclass_hr_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLeaveCounter",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "annual_leave_total",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "annual_leave_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "annual_leave_pending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sick_leave_total",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "sick_leave_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "sick_leave_pending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "casual_leave_total",
                    models.DecimalField(decimal_places=2, default=5, max_digits=5),
                ),
                (
                    "casual_leave_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "casual_leave_pending",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "last_reset_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("next_reset_date", models.DateField(blank=True, null=True)),
                ("enable_sms_alerts", models.BooleanField(default=True)),
                (
                    "low_balance_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Send alert when balance falls below this",
                        max_digits=5,
                    ),
                ),
                (
                    "critical_balance_threshold",
                    models.DecimalField(decimal_places=2, default=2, max_digits=5),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_counter",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Leave Counter",
                "verbose_name_plural": "Staff Leave Counters",
            },
        ),
        migrations.CreateModel(
            name="LeaveBalanceAlert",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("annual_leave", "Annual Leave"),
                            ("sick_leave", "Sick Leave"),
                            ("casual_leave", "Casual Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low", "Low Balance (< 5 days)"),
                            ("critical", "Critical Balance (< 2 days)"),
                            ("exhausted", "Exhausted (0 days)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "balance_remaining",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("sms_sent", models.BooleanField(default=False)),
                ("sms_sent_at", models.DateTimeField(blank=True, null=True)),
                ("sms_message", models.TextField(blank=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balance_alerts",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance Alert",
                "verbose_name_plural": "Leave Balance Alerts",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="StaffActivity",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("training", "Training Session"),
                            ("meeting", "Meeting"),
                            ("event", "Hospital Event"),
                            ("deadline", "Deadline"),
                            ("birthday", "Birthday"),
                            ("anniversary", "Work Anniversary"),
                            ("holiday", "Public Holiday"),
                            ("review", "Performance Review"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "all_staff",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, all staff can see this activity",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("medium", "Medium Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=False)),
                ("send_reminder", models.BooleanField(default=True)),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=1, help_text="Days before to send reminder"
                    ),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_staff",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific staff assigned to this activity",
                        related_name="activities",
                        to="hospital.staff",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True, related_name="activities", to="hospital.department"
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Activity",
                "verbose_name_plural": "Staff Activities",
                "ordering": ["start_datetime"],
                "indexes": [
                    models.Index(
                        fields=["start_datetime", "end_datetime"],
                        name="hospital_st_start_d_d47828_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "start_datetime"],
                        name="hospital_st_activit_48bd71_idx",
                    ),
                ],
            },
        ),
    ]
