# Generated by Django 4.2.7 on 2025-11-11 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0999_biometric_system"),
    ]

    operations = []
