# Generated by Django 4.2.7 on 2025-11-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1001_legacypatient_accountcategory_accountingauditlog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revenue",
            name="revenue_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
