# Generated by Django 4.2.7 on 2025-11-11 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1002_alter_revenue_revenue_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadOfDepartment",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("can_manage_schedules", models.BooleanField(default=True)),
                ("can_approve_procurement", models.BooleanField(default=True)),
                ("can_approve_leave", models.BooleanField(default=True)),
                ("appointed_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_head",
                        to="hospital.department",
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod_designation",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Head of Department",
                "verbose_name_plural": "Heads of Department",
            },
        ),
    ]
