# Generated by Django 4.2.7 on 2025-11-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1003_headofdepartment"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAttendance",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "login_method",
                    models.CharField(
                        choices=[
                            ("password", "Password Login"),
                            ("biometric", "Biometric (Face Recognition)"),
                            ("biometric_fingerprint", "Biometric (Fingerprint)"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=30,
                    ),
                ),
                ("first_login_time", models.DateTimeField(auto_now_add=True)),
                ("last_login_time", models.DateTimeField(auto_now=True)),
                ("login_count", models.IntegerField(default=1)),
                ("check_in_time", models.TimeField(blank=True, null=True)),
                ("check_out_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("is_late", models.BooleanField(default=False)),
                ("late_minutes", models.IntegerField(default=0)),
                ("check_in_location", models.CharField(blank=True, max_length=200)),
                ("check_in_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance",
                        to="hospital.staffshift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Attendance",
                "verbose_name_plural": "Staff Attendance Records",
                "ordering": ["-date", "staff"],
                "unique_together": {("staff", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("days_present", models.IntegerField(default=0)),
                ("days_absent", models.IntegerField(default=0)),
                ("days_late", models.IntegerField(default=0)),
                ("days_on_leave", models.IntegerField(default=0)),
                (
                    "total_hours_worked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_attendance",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Summary",
                "verbose_name_plural": "Attendance Summaries",
                "ordering": ["-year", "-month", "staff"],
                "unique_together": {("staff", "month", "year")},
            },
        ),
    ]
