# Generated by Django 4.2.7 on 2025-11-11 20:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1004_staffattendance_attendancesummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_revenues",
                to="hospital.department",
            ),
        ),
        migrations.AddField(
            model_name="revenue",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultation", "Consultation"),
                    ("laboratory", "Laboratory Test"),
                    ("pharmacy", "Pharmacy Sale"),
                    ("imaging", "Imaging/Radiology"),
                    ("dental", "Dental Service"),
                    ("gynecology", "Gynecology Service"),
                    ("surgery", "Surgical Procedure"),
                    ("admission", "Admission Fee"),
                    ("emergency", "Emergency Service"),
                    ("outpatient", "Outpatient Service"),
                    ("other", "Other Service"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RevenueStream",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "stream_type",
                    models.CharField(
                        choices=[
                            ("clinical", "Clinical Services"),
                            ("diagnostic", "Diagnostic Services"),
                            ("pharmacy", "Pharmacy Sales"),
                            ("administrative", "Administrative Fees"),
                            ("other", "Other Revenue"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "monthly_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "annual_target",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Stream",
                "verbose_name_plural": "Revenue Streams",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentRevenue",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("transaction_count", models.IntegerField(default=1)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_records",
                        to="hospital.department",
                    ),
                ),
                (
                    "revenue_stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_revenues",
                        to="hospital.revenuestream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Revenue",
                "verbose_name_plural": "Department Revenues",
                "ordering": ["-date", "department"],
            },
        ),
        migrations.AddField(
            model_name="revenue",
            name="revenue_stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revenue_entries",
                to="hospital.revenuestream",
            ),
        ),
    ]
