# Generated by Django 4.2.7 on 2025-11-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1007_alter_staff_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffshift",
            name="assigned_duties",
            field=models.TextField(
                blank=True, help_text="Specific duties for this shift"
            ),
        ),
        migrations.AddField(
            model_name="staffshift",
            name="assigned_location",
            field=models.CharField(
                blank=True,
                help_text="Specific location/unit assignment",
                max_length=200,
            ),
        ),
    ]
