# Generated by Django 4.2.7 on 2025-11-12 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1008_staffshift_assigned_duties_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procurementrequest",
            options={
                "ordering": ["-request_date", "-created"],
                "permissions": [
                    (
                        "can_approve_procurement_admin",
                        "Can approve procurement requests (Admin level)",
                    ),
                    (
                        "can_approve_procurement_accounts",
                        "Can approve procurement requests (Accounts level)",
                    ),
                ],
                "verbose_name": "Procurement Request",
                "verbose_name_plural": "Procurement Requests",
            },
        ),
    ]
