# Generated by Django 4.2.7 on 2025-11-12 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1009_alter_procurementrequest_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("batch_number", models.CharField(db_index=True, max_length=50)),
                (
                    "lot_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("quantity_received", models.PositiveIntegerField()),
                ("quantity_remaining", models.PositiveIntegerField()),
                ("received_date", models.DateField(default=datetime.date.today)),
                ("manufacturing_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, db_index=True, null=True)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("purchase_order_number", models.CharField(blank=True, max_length=50)),
                (
                    "is_quarantined",
                    models.BooleanField(
                        default=False, help_text="Quarantined for quality check"
                    ),
                ),
                ("is_expired", models.BooleanField(db_index=True, default=False)),
                (
                    "is_recalled",
                    models.BooleanField(
                        default=False, help_text="Batch recalled by supplier"
                    ),
                ),
                ("quarantine_reason", models.TextField(blank=True)),
                ("recall_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="hospital.inventoryitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_batches",
                        to="hospital.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Batch",
                "verbose_name_plural": "Inventory Batches",
                "ordering": ["expiry_date", "-received_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCount",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("count_number", models.CharField(max_length=50, unique=True)),
                ("count_date", models.DateField(default=datetime.date.today)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "is_full_count",
                    models.BooleanField(
                        default=True, help_text="Full count vs cycle count"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("total_items_counted", models.PositiveIntegerField(default=0)),
                ("items_with_variance", models.PositiveIntegerField(default=0)),
                (
                    "total_variance_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "category_filter",
                    models.ForeignKey(
                        blank=True,
                        help_text="For partial counts",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.inventorycategory",
                    ),
                ),
                (
                    "conducted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conducted_counts",
                        to="hospital.staff",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_counts",
                        to="hospital.store",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_counts",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Count",
                "verbose_name_plural": "Inventory Counts",
                "ordering": ["-count_date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="InventoryRequisition",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "requisition_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "request_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "required_by_date",
                    models.DateField(
                        blank=True, help_text="When items are needed", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent/Emergency"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("partially_issued", "Partially Issued"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "purpose",
                    models.TextField(help_text="Purpose/justification for requisition"),
                ),
                ("notes", models.TextField(blank=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requisitions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_requisitions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_requisitions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_requisitions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "requested_from_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="hospital.store",
                    ),
                ),
                (
                    "requesting_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_requisitions",
                        to="hospital.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Requisition",
                "verbose_name_plural": "Inventory Requisitions",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="InventoryRequisitionLine",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity_requested", models.PositiveIntegerField()),
                ("quantity_approved", models.PositiveIntegerField(default=0)),
                ("quantity_issued", models.PositiveIntegerField(default=0)),
                ("unit_of_measure", models.CharField(default="units", max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.inventoryitem",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hospital.inventoryrequisition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requisition Line",
                "verbose_name_plural": "Requisition Lines",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCountLine",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "system_quantity",
                    models.PositiveIntegerField(help_text="Quantity per system"),
                ),
                (
                    "counted_quantity",
                    models.PositiveIntegerField(help_text="Actual physical count"),
                ),
                (
                    "variance",
                    models.IntegerField(default=0, help_text="Counted - System"),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "variance_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("has_variance", models.BooleanField(db_index=True, default=False)),
                ("is_reconciled", models.BooleanField(default=False)),
                ("reconciliation_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hospital.inventorycount",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.inventoryitem",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Count Line",
                "verbose_name_plural": "Inventory Count Lines",
                "ordering": ["inventory_item__item_name"],
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("overstock", "Overstock"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("reorder_point", "Reorder Point Reached"),
                            ("batch_recalled", "Batch Recalled"),
                            ("quarantined", "Item Quarantined"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("current_quantity", models.IntegerField()),
                ("recommended_action", models.TextField(blank=True)),
                ("is_acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_stock_alerts",
                        to="hospital.staff",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="hospital.inventorybatch",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="hospital.inventoryitem",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_stock_alerts",
                        to="hospital.staff",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="hospital.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Alert",
                "verbose_name_plural": "Stock Alerts",
                "ordering": ["-created", "severity"],
                "indexes": [
                    models.Index(
                        fields=["-created", "severity"],
                        name="hospital_st_created_c07d89_idx",
                    ),
                    models.Index(
                        fields=["is_acknowledged", "is_resolved"],
                        name="hospital_st_is_ackn_b4844c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "transaction_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt (Goods Received)"),
                            ("issue", "Issue (Goods Issued)"),
                            ("transfer_out", "Transfer Out"),
                            ("transfer_in", "Transfer In"),
                            ("adjustment", "Stock Adjustment"),
                            ("return", "Return to Supplier"),
                            ("return_from_dept", "Return from Department"),
                            ("disposal", "Disposal/Wastage"),
                            ("damaged", "Damaged"),
                            ("expired", "Expired"),
                            ("theft", "Theft/Loss"),
                            ("found", "Found (Unrecorded Stock)"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Positive for additions, negative for deductions"
                    ),
                ),
                (
                    "quantity_before",
                    models.PositiveIntegerField(
                        help_text="Stock level before transaction"
                    ),
                ),
                (
                    "quantity_after",
                    models.PositiveIntegerField(
                        help_text="Stock level after transaction"
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="PO, Transfer, or other ref",
                        max_length=100,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "lot_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for adjustment/disposal/etc"
                    ),
                ),
                ("from_location", models.CharField(blank=True, max_length=200)),
                ("to_location", models.CharField(blank=True, max_length=200)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_inventory_transactions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="hospital.inventoryitem",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "procurement_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.procurementrequest",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="hospital.store",
                    ),
                ),
                (
                    "store_transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.storetransfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
                "ordering": ["-transaction_date", "-created"],
                "indexes": [
                    models.Index(
                        fields=["-transaction_date", "store"],
                        name="hospital_in_transac_b92029_idx",
                    ),
                    models.Index(
                        fields=["inventory_item", "-transaction_date"],
                        name="hospital_in_invento_88d3a7_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "-transaction_date"],
                        name="hospital_in_transac_bd0460_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryrequisition",
            index=models.Index(
                fields=["-request_date", "status"],
                name="hospital_in_request_350aee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryrequisition",
            index=models.Index(
                fields=["requesting_department", "-request_date"],
                name="hospital_in_request_da8ff3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(
                fields=["expiry_date", "is_expired"],
                name="hospital_in_expiry__4e8fee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(
                fields=["batch_number"], name="hospital_in_batch_n_e55d33_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventorybatch",
            unique_together={("inventory_item", "batch_number", "store")},
        ),
    ]
