# Generated by Django 4.2.7 on 2025-11-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "hospital",
            "1010_inventorybatch_inventorycount_inventoryrequisition_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="imagingstudy",
            name="assigned_radiologist",
            field=models.ForeignKey(
                blank=True,
                help_text="Radiologist assigned to read this study",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_studies",
                to="hospital.staff",
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="compared_with_prior",
            field=models.BooleanField(
                default=False, help_text="Compared with prior studies"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="contrast_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="contrast_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="contrast_volume",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="critical_findings",
            field=models.TextField(
                blank=True, help_text="Description of critical findings"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="has_critical_findings",
            field=models.BooleanField(
                default=False, help_text="Flag for critical/urgent findings"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="image_quality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("adequate", "Adequate"),
                    ("poor", "Poor"),
                    ("unacceptable", "Unacceptable"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="is_paid",
            field=models.BooleanField(
                default=False, help_text="Whether payment has been received"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="measurements",
            field=models.TextField(
                blank=True, help_text="Key measurements from the study"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="notification_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="payment_receipt_number",
            field=models.CharField(
                blank=True, help_text="Receipt number for payment", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="prior_study_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="quality_notes",
            field=models.TextField(blank=True, help_text="Notes about image quality"),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="referring_physician_notified",
            field=models.BooleanField(
                default=False,
                help_text="Referring physician notified of critical findings",
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason if study was rejected"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="repeat_reason",
            field=models.TextField(
                blank=True, help_text="Reason if study needed to be repeated"
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="report_started_at",
            field=models.DateTimeField(
                blank=True, help_text="When reporting started", null=True
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="When study acquisition started", null=True
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                help_text="Technician who performed the study",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_studies",
                to="hospital.staff",
            ),
        ),
        migrations.AddField(
            model_name="imagingstudy",
            name="turnaround_time_minutes",
            field=models.IntegerField(
                blank=True, help_text="Time from completion to report", null=True
            ),
        ),
        migrations.AlterField(
            model_name="imagingstudy",
            name="modality",
            field=models.CharField(
                choices=[
                    ("xray", "X-Ray"),
                    ("ct", "CT Scan"),
                    ("mri", "MRI"),
                    ("ultrasound", "Ultrasound"),
                    ("mammography", "Mammography"),
                    ("fluoroscopy", "Fluoroscopy"),
                    ("nuclear", "Nuclear Medicine"),
                    ("pet", "PET Scan"),
                    ("dexa", "DEXA Scan"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="imagingstudy",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("arrived", "Patient Arrived"),
                    ("in_progress", "Scan In Progress"),
                    ("completed", "Scan Completed"),
                    ("quality_check", "Quality Check"),
                    ("awaiting_report", "Awaiting Report"),
                    ("reporting", "Being Reported"),
                    ("reported", "Report Complete"),
                    ("verified", "Report Verified"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
    ]
