# Generated by Django 4.2.7 on 2025-11-12 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1011_imagingstudy_assigned_radiologist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="is_verified",
            field=models.BooleanField(
                default=False, help_text="Receipt has been verified"
            ),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentreceipt",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_receipts",
                to="hospital.staff",
            ),
        ),
    ]
