# Generated by Django 4.2.7 on 2025-11-12 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1012_paymentreceipt_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationLog",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "batch_id",
                    models.CharField(
                        help_text="Unique batch identifier", max_length=50, unique=True
                    ),
                ),
                (
                    "migration_type",
                    models.CharField(
                        help_text="Type of migration (patients, users, drugs, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_records", models.IntegerField(default=0)),
                ("successful_records", models.IntegerField(default=0)),
                ("failed_records", models.IntegerField(default=0)),
                ("skipped_records", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_log",
                    models.TextField(blank=True, help_text="Detailed error messages"),
                ),
                (
                    "success_log",
                    models.TextField(
                        blank=True, help_text="Success messages and warnings"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Migration Log",
                "verbose_name_plural": "Migration Logs",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="LegacyIDMapping",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "legacy_table",
                    models.CharField(
                        help_text="Name of the legacy table (e.g., patient_data, users, drugs)",
                        max_length=100,
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        help_text="ID in the legacy system", max_length=50
                    ),
                ),
                (
                    "new_model",
                    models.CharField(
                        help_text="Django model name (e.g., Patient, CustomUser, Drug)",
                        max_length=100,
                    ),
                ),
                ("new_id", models.UUIDField(help_text="UUID in the new system")),
                ("migrated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "migration_batch",
                    models.CharField(
                        blank=True,
                        help_text="Migration batch identifier",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Legacy ID Mapping",
                "verbose_name_plural": "Legacy ID Mappings",
                "indexes": [
                    models.Index(
                        fields=["legacy_table", "legacy_id"],
                        name="hospital_le_legacy__5594a6_idx",
                    ),
                    models.Index(
                        fields=["new_model", "new_id"],
                        name="hospital_le_new_mod_e0e6c2_idx",
                    ),
                ],
                "unique_together": {("legacy_table", "legacy_id")},
            },
        ),
    ]
