# Generated by Django 4.2.7 on 2025-11-12 15:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1013_migrationlog_legacyidmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbulanceBilling",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("base_charge", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "miles_traveled",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "mileage_charge",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "emergency_surcharge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "equipment_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "oxygen_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "iv_fluids_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "medical_supplies_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "wait_time_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("billed", "Billed"),
                            ("paid", "Paid"),
                            ("insurance_pending", "Insurance Pending"),
                            ("written_off", "Written Off"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("insurance_claim_filed", models.BooleanField(default=False)),
                (
                    "insurance_approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("invoice_date", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("billing_notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambulance Billing",
                "verbose_name_plural": "Ambulance Billings",
                "db_table": "hospital_ambulance_billing",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="AmbulanceServiceCharge",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("charge_code", models.CharField(max_length=20, unique=True)),
                ("charge_name", models.CharField(max_length=100)),
                (
                    "charge_type",
                    models.CharField(
                        choices=[
                            ("oxygen", "Oxygen Therapy"),
                            ("iv_fluids", "IV Fluids Administration"),
                            ("medications", "Medications"),
                            ("medical_supplies", "Medical Supplies"),
                            ("wait_time", "Wait Time"),
                            ("specialty_equipment", "Specialty Equipment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_of_measure", models.CharField(default="each", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_documentation", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ambulance Service Charge",
                "verbose_name_plural": "Ambulance Service Charges",
                "db_table": "hospital_ambulance_service_charge",
                "ordering": ["charge_name"],
            },
        ),
        migrations.CreateModel(
            name="AmbulanceServiceType",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("service_code", models.CharField(max_length=20, unique=True)),
                ("service_name", models.CharField(max_length=100)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("bls", "Basic Life Support (BLS)"),
                            ("als", "Advanced Life Support (ALS)"),
                            ("cct", "Critical Care Transport (CCT)"),
                            ("neonatal", "Neonatal/Pediatric Transport"),
                            ("transfer", "Inter-Hospital Transfer"),
                            ("mobile_icu", "Mobile ICU"),
                            ("air_ambulance", "Air Ambulance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "base_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "per_mile_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "emergency_surcharge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "equipment_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("equipment_description", models.TextField(blank=True)),
                ("crew_size", models.IntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ambulance Service Type",
                "verbose_name_plural": "Ambulance Service Types",
                "db_table": "hospital_ambulance_service_type",
                "ordering": ["service_name"],
            },
        ),
        migrations.CreateModel(
            name="AmbulanceUnit",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("unit_number", models.CharField(max_length=20, unique=True)),
                ("vehicle_make", models.CharField(blank=True, max_length=50)),
                ("vehicle_model", models.CharField(blank=True, max_length=50)),
                ("license_plate", models.CharField(blank=True, max_length=20)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("en_route", "En Route to Scene"),
                            ("on_scene", "On Scene"),
                            ("transporting", "Transporting Patient"),
                            ("returning", "Returning to Station"),
                            ("out_of_service", "Out of Service"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("current_location", models.CharField(blank=True, max_length=200)),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("last_maintenance", models.DateTimeField(blank=True, null=True)),
                ("next_maintenance_due", models.DateField(blank=True, null=True)),
                (
                    "mileage",
                    models.IntegerField(default=0, help_text="Total miles/kilometers"),
                ),
                ("home_station", models.CharField(blank=True, max_length=100)),
                (
                    "primary_emt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulance_emt",
                        to="hospital.staff",
                    ),
                ),
                (
                    "primary_paramedic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulance_paramedic",
                        to="hospital.staff",
                    ),
                ),
                (
                    "service_capabilities",
                    models.ManyToManyField(
                        related_name="capable_units", to="hospital.ambulanceservicetype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambulance Unit",
                "verbose_name_plural": "Ambulance Units",
                "db_table": "hospital_ambulance_unit",
                "ordering": ["unit_number"],
            },
        ),
        migrations.CreateModel(
            name="AmbulanceDispatch",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("dispatch_number", models.CharField(max_length=50, unique=True)),
                (
                    "call_received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("dispatch_time", models.DateTimeField(blank=True, null=True)),
                ("arrival_time", models.DateTimeField(blank=True, null=True)),
                ("transport_start_time", models.DateTimeField(blank=True, null=True)),
                ("hospital_arrival_time", models.DateTimeField(blank=True, null=True)),
                ("call_completed_time", models.DateTimeField(blank=True, null=True)),
                ("pickup_address", models.TextField()),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("destination_address", models.TextField(blank=True)),
                (
                    "destination_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "destination_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "miles_traveled",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("trauma", "Trauma"),
                            ("cardiac", "Cardiac Arrest"),
                            ("respiratory", "Respiratory Distress"),
                            ("stroke", "Stroke Alert"),
                            ("overdose", "Overdose"),
                            ("psychiatric", "Psychiatric Emergency"),
                            ("transfer", "Inter-Facility Transfer"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("code_3", "Code 3 - Lights & Sirens"),
                            ("code_2", "Code 2 - Urgent"),
                            ("code_1", "Code 1 - Non-Emergency"),
                        ],
                        default="code_2",
                        max_length=10,
                    ),
                ),
                ("chief_complaint", models.TextField(blank=True)),
                ("pre_hospital_report", models.TextField(blank=True)),
                ("vital_signs_on_scene", models.TextField(blank=True)),
                ("treatments_administered", models.TextField(blank=True)),
                ("patient_transported", models.BooleanField(default=True)),
                ("transport_refused", models.BooleanField(default=False)),
                ("patient_deceased_on_scene", models.BooleanField(default=False)),
                (
                    "pcr_completed",
                    models.BooleanField(default=False, help_text="Patient Care Report"),
                ),
                ("run_report_notes", models.TextField(blank=True)),
                (
                    "ambulance_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispatches",
                        to="hospital.ambulanceunit",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulance_transport",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulance_transports",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambulance Dispatch",
                "verbose_name_plural": "Ambulance Dispatches",
                "db_table": "hospital_ambulance_dispatch",
                "ordering": ["-call_received_at"],
            },
        ),
        migrations.CreateModel(
            name="AmbulanceBillingItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.00"), max_digits=10
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="hospital.ambulancebilling",
                    ),
                ),
                (
                    "service_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.ambulanceservicecharge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ambulance Billing Item",
                "verbose_name_plural": "Ambulance Billing Items",
                "db_table": "hospital_ambulance_billing_item",
            },
        ),
        migrations.AddField(
            model_name="ambulancebilling",
            name="dispatch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing",
                to="hospital.ambulancedispatch",
            ),
        ),
        migrations.AddField(
            model_name="ambulancebilling",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.encounter",
            ),
        ),
        migrations.AddField(
            model_name="ambulancebilling",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.patient",
            ),
        ),
        migrations.AddField(
            model_name="ambulancebilling",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="hospital.ambulanceservicetype",
            ),
        ),
    ]
