# Generated by Django 4.2.7 on 2025-11-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1014_ambulancebilling_ambulanceservicecharge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revenue",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="revenue",
            name="recurrence_period",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="revenue",
            name="reference_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="revenue",
            name="reference_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.department",
            ),
        ),
        migrations.AlterField(
            model_name="revenue",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("consultation", "Consultation"),
                    ("laboratory", "Laboratory"),
                    ("pharmacy", "Pharmacy"),
                    ("imaging", "Imaging/Radiology"),
                    ("dental", "Dental"),
                    ("gynecology", "Gynecology"),
                    ("surgery", "Surgery"),
                    ("emergency", "Emergency"),
                    ("ambulance", "Ambulance/EMS"),
                    ("admission", "Admission/Inpatient"),
                    ("other", "Other Services"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
