# Generated by Django 4.2.7 on 2025-11-13 18:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1015_revenue_is_recurring_revenue_recurrence_period_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetLineItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personnel", "Personnel"),
                            ("operational", "Operational"),
                            ("supplies", "Supplies & Equipment"),
                            ("capital", "Capital Expenditure"),
                            ("utilities", "Utilities"),
                            ("maintenance", "Maintenance"),
                            ("training", "Training & Development"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "budgeted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "account_code",
                    models.CharField(
                        blank=True, help_text="GL account code", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["category", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetPeriod",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., FY 2025, Q1 2025, January 2025", max_length=100
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("quarterly", "Quarterly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budget_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budget_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("period_type", "start_date")},
            },
        ),
        migrations.CreateModel(
            name="DepartmentBudget",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "personnel_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salaries, benefits",
                        max_digits=15,
                    ),
                ),
                (
                    "operational_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Day-to-day operations",
                        max_digits=15,
                    ),
                ),
                (
                    "supplies_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Medical supplies, equipment",
                        max_digits=15,
                    ),
                ),
                (
                    "capital_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Major purchases, infrastructure",
                        max_digits=15,
                    ),
                ),
                (
                    "spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Committed but not spent",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("active", "Active"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="Budget justification/rationale"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_dept_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_budgets",
                        to="hospital.budgetperiod",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="hospital.department",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_budgets",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["-budget_period__start_date", "department__name"],
                "unique_together": {("budget_period", "department")},
            },
        ),
        migrations.CreateModel(
            name="BudgetVariance",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("variance_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "variance_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "variance_type",
                    models.CharField(
                        choices=[
                            ("favorable", "Favorable"),
                            ("unfavorable", "Unfavorable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(help_text="Explain reason for variance"),
                ),
                (
                    "corrective_action",
                    models.TextField(
                        blank=True, help_text="Actions to address variance"
                    ),
                ),
                (
                    "department_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variances",
                        to="hospital.departmentbudget",
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.budgetlineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-variance_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetTransfer",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("transfer_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budget_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_department_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="hospital.departmentbudget",
                    ),
                ),
                (
                    "from_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_out",
                        to="hospital.budgetlineitem",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_transfer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_department_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="hospital.departmentbudget",
                    ),
                ),
                (
                    "to_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_in",
                        to="hospital.budgetlineitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetRevision",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("revision_date", models.DateField(default=django.utils.timezone.now)),
                ("revision_number", models.IntegerField()),
                (
                    "old_allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "new_allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("change_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reason", models.TextField()),
                ("justification", models.TextField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budget_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="hospital.departmentbudget",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_revision_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-revision_date", "-revision_number"],
            },
        ),
        migrations.CreateModel(
            name="BudgetReport",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Budget Report"),
                            ("quarterly", "Quarterly Budget Report"),
                            ("annual", "Annual Budget Report"),
                            ("variance", "Variance Analysis"),
                            ("department", "Department Budget Summary"),
                            ("comparative", "Comparative Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("report_date", models.DateField(default=django.utils.timezone.now)),
                ("report_data", models.JSONField(default=dict)),
                (
                    "total_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_spent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "utilization_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_reports",
                        to="hospital.department",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="hospital.budgetperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.AddField(
            model_name="budgetlineitem",
            name="department_budget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="hospital.departmentbudget",
            ),
        ),
        migrations.CreateModel(
            name="BudgetExpense",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=500)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("expense_category", models.CharField(max_length=50)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="hospital.departmentbudget",
                    ),
                ),
                (
                    "line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="hospital.budgetlineitem",
                    ),
                ),
                (
                    "payment_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_expenses",
                        to="hospital.paymentvoucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="BudgetAlert",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Reached"),
                            ("overbudget", "Over Budget"),
                            ("underutilized", "Under-Utilized"),
                            ("variance", "Significant Variance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "threshold_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "current_utilization",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="hospital.departmentbudget",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
