# Generated by Django 4.2.7 on 2025-11-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1017_create_missing_hr_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(blank=True, upload_to="candidate_resumes/"),
        ),
    ]
