# Generated by Django 4.2.7 on 2025-11-15 11:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1018_alter_candidate_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyDispenseHistory",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("patient_name", models.CharField(blank=True, max_length=255)),
                ("drug_name", models.CharField(max_length=255)),
                ("quantity_dispensed", models.PositiveIntegerField()),
                ("instructions", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("counselling_given", models.BooleanField(default=False)),
                ("dispensed_by_name", models.CharField(blank=True, max_length=255)),
                ("dispensed_at", models.DateTimeField()),
                (
                    "dispensed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_dispense_actions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "dispensing_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="hospital.pharmacydispensing",
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_dispense_history_records",
                        to="hospital.drug",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_dispense_history_records",
                        to="hospital.patient",
                    ),
                ),
                (
                    "payment_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_dispense_history_entries",
                        to="hospital.paymentreceipt",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispense_history",
                        to="hospital.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-dispensed_at", "-created"],
            },
        ),
    ]
