# Generated by Django 4.2.7 on 2025-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1019_pharmacydispensehistory"),
    ]

    def ensure_walkin_tables(apps, schema_editor):
        connection = schema_editor.connection
        existing_tables = connection.introspection.table_names()
        sale_model = apps.get_model("hospital", "WalkInPharmacySale")
        sale_item_model = apps.get_model("hospital", "WalkInPharmacySaleItem")
        if sale_model._meta.db_table not in existing_tables:
            schema_editor.create_model(sale_model)
        if sale_item_model._meta.db_table not in existing_tables:
            schema_editor.create_model(sale_item_model)

    def drop_walkin_tables(apps, schema_editor):
        sale_item_model = apps.get_model("hospital", "WalkInPharmacySaleItem")
        sale_model = apps.get_model("hospital", "WalkInPharmacySale")
        schema_editor.delete_model(sale_item_model)
        schema_editor.delete_model(sale_model)

    operations = [
        migrations.RunPython(ensure_walkin_tables, drop_walkin_tables),
        migrations.AlterField(
            model_name="paymentreceipt",
            name="service_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lab", "Laboratory Test"),
                    ("pharmacy", "Pharmacy/Medication"),
                    ("pharmacy_prescription", "Pharmacy Prescription"),
                    ("pharmacy_walkin", "Walk-in Pharmacy Sale"),
                    ("medication", "Medication Sale"),
                    ("imaging", "Imaging/Radiology"),
                    ("imaging_study", "Imaging Study"),
                    ("consultation", "Consultation"),
                    ("admission", "Admission"),
                    ("procedure", "Procedure"),
                    ("combined", "Combined Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
