# Generated by Django 4.2.7 on 2025-11-15 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1020_ensure_walkin_sales_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="labresultrelease",
            name="sent_to_cashier_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labresultrelease",
            name="sent_to_cashier_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_cashier_tickets_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
