# Generated by Django 4.2.7 on 2025-11-17 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1022_usersession"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientQRCode",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("qr_token", models.CharField(blank=True, max_length=64, unique=True)),
                (
                    "qr_code_data",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="patient_qr_codes/"
                    ),
                ),
                ("scan_count", models.PositiveIntegerField(default=0)),
                ("last_generated_at", models.DateTimeField(blank=True, null=True)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_qr_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_profile",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient QR Code",
                "verbose_name_plural": "Patient QR Codes",
                "ordering": ["-created"],
            },
        ),
    ]
