# Generated by Django 4.2.7 on 2025-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1023_patientqrcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientqrcode",
            name="qr_code_data",
            field=models.TextField(blank=True),
        ),
    ]
