# Generated by Django 4.2.7 on 2025-11-18 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1025_add_login_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('print', 'Print'), ('access', 'Access'), ('modify', 'Modify'), ('system', 'System Event')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('model_name', models.CharField(blank=True, help_text="Django model name (e.g., 'Patient', 'Encounter')", max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the affected object', max_length=100)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=255)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON of what changed (field: {old: x, new: y})')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (IP, user agent, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the action succeeded')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='hospital_au_created_a1dd00_idx'), models.Index(fields=['user', '-created'], name='hospital_au_user_id_0bb809_idx'), models.Index(fields=['action_type', '-created'], name='hospital_au_action__a7355a_idx'), models.Index(fields=['model_name', '-created'], name='hospital_au_model_n_ea1c73_idx'), models.Index(fields=['severity', '-created'], name='hospital_au_severit_6858c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['user', '-created'], name='hospital_ac_user_id_7bd517_idx'), models.Index(fields=['activity_type', '-created'], name='hospital_ac_activit_b00c27_idx'), models.Index(fields=['-created'], name='hospital_ac_created_d71773_idx')],
            },
        ),
    ]
