# Generated by Django 4.2.7 on 2025-11-19 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1026_add_audit_logging"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="insurance_enforcement_action",
            field=models.CharField(
                blank=True,
                help_text="What the insurer expects us to do (block/patient_pay/warn)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="insurance_exclusion_reason",
            field=models.CharField(
                blank=True,
                help_text="Friendly explanation for frontdesk/pharmacy users",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="is_insurance_excluded",
            field=models.BooleanField(
                default=False,
                help_text="If True, this line will never be sent to insurance claims",
            ),
        ),
        migrations.CreateModel(
            name="InsuranceExclusionRule",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "apply_to_all_plans",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this rule applies to every plan for the insurance company",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("service_code", "Specific Service Code"),
                            ("service_category", "Service Category"),
                            ("drug", "Specific Drug"),
                            ("drug_generic", "Drug Generic Name"),
                            ("drug_category", "Drug Category"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        help_text="Category name to match ServiceCode.category (case-insensitive)",
                        max_length=100,
                    ),
                ),
                (
                    "drug_generic_name",
                    models.CharField(
                        blank=True,
                        help_text="Matches Drug.generic_name (case-insensitive)",
                        max_length=200,
                    ),
                ),
                (
                    "drug_category",
                    models.CharField(
                        blank=True,
                        help_text="Custom grouping for drugs (e.g., antibiotics, antimalarials)",
                        max_length=100,
                    ),
                ),
                (
                    "enforcement_action",
                    models.CharField(
                        choices=[
                            ("block", "Block billing"),
                            ("patient_pay", "Charge patient/self-pay"),
                            ("warn", "Warn only"),
                        ],
                        default="block",
                        help_text="What the billing team should do when this rule hits",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Short reason the front desk sees",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_exclusion_rules",
                        to="hospital.drug",
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        help_text="Which insurance company provided this exclusion list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusion_rules",
                        to="hospital.insurancecompany",
                    ),
                ),
                (
                    "insurance_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Limit rule to a specific plan (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusion_rules",
                        to="hospital.insuranceplan",
                    ),
                ),
                (
                    "service_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_exclusion_rules",
                        to="hospital.servicecode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance Exclusion Rule",
                "verbose_name_plural": "Insurance Exclusion Rules",
                "ordering": ["insurance_company", "rule_type", "created"],
            },
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="insurance_exclusion_rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the exclusion rule that matched (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="hospital.insuranceexclusionrule",
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceexclusionrule",
            index=models.Index(
                fields=["insurance_company", "rule_type"],
                name="hospital_in_insuran_dfbd8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insuranceexclusionrule",
            index=models.Index(
                fields=["rule_type", "enforcement_action"],
                name="hospital_in_rule_ty_e39095_idx",
            ),
        ),
    ]
