# Generated by Django 4.2.7 on 2025-11-19 10:19

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1027_invoiceline_insurance_enforcement_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthTip",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("opd", "Outpatient"),
                            ("pediatrics", "Pediatrics"),
                            ("maternity", "Maternity"),
                            ("wellness", "Wellness"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional emoji or icon class",
                        max_length=50,
                    ),
                ),
                ("accent_color", models.CharField(default="#10B981", max_length=20)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Health Tip",
                "verbose_name_plural": "Health Tips",
                "ordering": ["display_order", "title"],
            },
        ),
    ]
