# Generated by Django 4.2.7 on 2025-11-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1028_healthtip"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginattempt",
            name="block_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional automatic unblock time for manual blocks",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="block_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="blocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocked_login_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="manually_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Set when an administrator blocks this account manually",
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="unblock_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="unblocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="unblocked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="unblocked_login_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
