# Generated by Django 4.2.7 on 2025-11-20 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1030_staffperformancesnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffperformancesnapshot",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="staffperformancesnapshot",
            name="modified",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="modified",
            ),
        ),
        migrations.CreateModel(
            name="LocumDoctorService",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("service_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "service_type",
                    models.CharField(
                        help_text="e.g., Consultation, Specialist Service",
                        max_length=100,
                    ),
                ),
                ("service_description", models.TextField(blank=True)),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total charge for the service",
                        max_digits=12,
                    ),
                ),
                (
                    "doctor_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="50% of service charge - payment to doctor",
                        max_digits=12,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tax on cash payments above 2000 GHS",
                        max_digits=12,
                    ),
                ),
                (
                    "net_payment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net payment after tax",
                        max_digits=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("processed", "Payment Processed"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"profession__in": ["doctor", "specialist"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locum_services",
                        to="hospital.staff",
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locum_services",
                        to="hospital.encounter",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locum_payments_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locum_services",
                        to="hospital.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Locum Doctor Service",
                "verbose_name_plural": "Locum Doctor Services",
                "ordering": ["-service_date", "doctor"],
            },
        ),
        migrations.CreateModel(
            name="LocumDoctorPaymentBatch",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_services", models.PositiveIntegerField(default=0)),
                (
                    "total_service_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_doctor_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_net_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                        ],
                        default="bank_transfer",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("paid", "Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locum_payment_batches",
                        to="hospital.staff",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locum_batches_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        related_name="payment_batches", to="hospital.locumdoctorservice"
                    ),
                ),
            ],
            options={
                "verbose_name": "Locum Doctor Payment Batch",
                "verbose_name_plural": "Locum Doctor Payment Batches",
                "ordering": ["-period_end", "doctor"],
            },
        ),
    ]
