# Generated by Django 4.2.7 on 2025-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1032_staff_locum_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="is_locum",
            field=models.BooleanField(
                default=False,
                help_text="Mark as locum/visiting staff for payment tracking",
            ),
        ),
    ]
