# Generated by Django 4.2.7 on 2025-11-21 12:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1033_usersession_is_locum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvoucher",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                    ("mobile_money", "Mobile Money"),
                    ("card", "Card"),
                    ("other", "Other"),
                ],
                default="bank_transfer",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "cheque_number",
                    models.CharField(
                        help_text="Cheque number from cheque book",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("payee_name", models.CharField(max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date cheque was issued",
                    ),
                ),
                (
                    "cheque_date",
                    models.DateField(
                        help_text="Date written on cheque (may be post-dated)"
                    ),
                ),
                (
                    "clear_date",
                    models.DateField(
                        blank=True, help_text="Date cheque cleared the bank", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("cleared", "Cleared"),
                            ("bounced", "Bounced"),
                            ("void", "Void"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "memo",
                    models.CharField(
                        blank=True, help_text="Memo line on cheque", max_length=200
                    ),
                ),
                (
                    "bank_statement_reference",
                    models.CharField(blank=True, max_length=100),
                ),
                ("reconciliation_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cheques",
                        to="hospital.bankaccount",
                    ),
                ),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheques_cleared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheques_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "payment_voucher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cheques",
                        to="hospital.paymentvoucher",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-cheque_number"],
            },
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="cheque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_vouchers",
                to="hospital.cheque",
            ),
        ),
        migrations.AddIndex(
            model_name="cheque",
            index=models.Index(
                fields=["cheque_number"], name="hospital_ch_cheque__5fd387_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cheque",
            index=models.Index(
                fields=["status", "cheque_date"], name="hospital_ch_status_6df315_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cheque",
            index=models.Index(
                fields=["bank_account", "status"], name="hospital_ch_bank_ac_e28574_idx"
            ),
        ),
    ]
