# Generated by Django 4.2.7 on 2025-11-21 18:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1034_add_cheque_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPayroll",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("payroll_number", models.CharField(max_length=50, unique=True)),
                ("payroll_period_start", models.DateField()),
                ("payroll_period_end", models.DateField()),
                ("pay_date", models.DateField()),
                (
                    "total_gross_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("calculated", "Calculated"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_payrolls_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_payrolls_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-payroll_period_end", "-payroll_number"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("reconciliation_number", models.CharField(max_length=50, unique=True)),
                (
                    "statement_date",
                    models.DateField(help_text="Date of bank statement"),
                ),
                (
                    "statement_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ending balance per bank statement",
                        max_digits=15,
                    ),
                ),
                (
                    "book_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ending balance per books",
                        max_digits=15,
                    ),
                ),
                (
                    "deposits_in_transit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "outstanding_cheques",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "bank_charges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "interest_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "other_adjustments",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "adjusted_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("reconciled", "Fully Reconciled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="hospital.bankaccount",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-statement_date", "-reconciliation_number"],
            },
        ),
        migrations.CreateModel(
            name="WithholdingReceivable",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("withholding_number", models.CharField(max_length=50, unique=True)),
                (
                    "withholding_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "payer",
                    models.CharField(
                        help_text="Entity that withheld the amount", max_length=200
                    ),
                ),
                ("description", models.TextField()),
                (
                    "amount_withheld",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "amount_recovered",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("expected_recovery_date", models.DateField(blank=True, null=True)),
                ("recovered_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "receivable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withholding_receivables",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-withholding_date", "-withholding_number"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationFee",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("fee_number", models.CharField(max_length=50, unique=True)),
                (
                    "registration_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_fees",
                        to="hospital.patient",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_fees",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-registration_date", "-fee_number"],
            },
        ),
        migrations.CreateModel(
            name="ProfitLossReport",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("report_number", models.CharField(max_length=50, unique=True)),
                (
                    "report_period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("revenue_by_category", models.JSONField(blank=True, default=dict)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("expenses_by_category", models.JSONField(blank=True, default=dict)),
                (
                    "gross_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net profit as percentage of revenue",
                        max_digits=5,
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hospital.fiscalyear",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-report_number"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementPurchase",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("purchase_number", models.CharField(max_length=50, unique=True)),
                (
                    "purchase_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash Purchase"),
                            ("credit", "Credit Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(default=django.utils.timezone.now)),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_invoice", models.CharField(blank=True, max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("received", "Goods Received"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        help_text="Purchase classification/category",
                        max_length=100,
                    ),
                ),
                (
                    "accounts_payable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procurement_purchases",
                        to="hospital.accountspayable",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="procurement_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_purchases",
                        to="hospital.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "liability_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Accounts Payable account for credit purchases",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_liabilities",
                        to="hospital.account",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cash/Bank account for cash purchases",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procurement_payments",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date", "-purchase_number"],
            },
        ),
        migrations.CreateModel(
            name="InitialRevaluation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("revaluation_number", models.CharField(max_length=50, unique=True)),
                (
                    "revaluation_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date when revaluation takes effect"),
                ),
                ("asset_description", models.CharField(max_length=500)),
                (
                    "previous_value",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("new_value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "revaluation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Difference (new - previous)",
                        max_digits=15,
                    ),
                ),
                (
                    "revaluation_type",
                    models.CharField(
                        choices=[
                            ("appreciation", "Appreciation"),
                            ("depreciation", "Depreciation"),
                            ("write_up", "Write Up"),
                            ("write_down", "Write Down"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revaluations",
                        to="hospital.account",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-revaluation_date", "-revaluation_number"],
            },
        ),
        migrations.CreateModel(
            name="IncomeGroup",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="income_groups",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DoctorCommission",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("commission_number", models.CharField(max_length=50, unique=True)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("surgery", "Surgery"),
                            ("procedure", "Procedure"),
                        ],
                        max_length=50,
                    ),
                ),
                ("service_date", models.DateField()),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "doctor_share",
                    models.DecimalField(
                        decimal_places=2, help_text="30% of total fee", max_digits=15
                    ),
                ),
                (
                    "operational_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="10% for operational items",
                        max_digits=15,
                    ),
                ),
                (
                    "hospital_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining amount to hospital",
                        max_digits=15,
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="hospital.staff",
                    ),
                ),
                (
                    "doctor_receivable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_commissions",
                        to="hospital.account",
                    ),
                ),
                (
                    "hospital_revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hospital_commissions",
                        to="hospital.account",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_commissions",
                        to="hospital.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "operational_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operational_commissions",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "-commission_number"],
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deposit_number", models.CharField(max_length=50, unique=True)),
                (
                    "deposit_type",
                    models.CharField(
                        choices=[("from", "Deposit From"), ("to", "Deposit To")],
                        max_length=10,
                    ),
                ),
                ("deposit_date", models.DateField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits_from",
                        to="hospital.account",
                    ),
                ),
                (
                    "from_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits_from",
                        to="hospital.bankaccount",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits_to",
                        to="hospital.account",
                    ),
                ),
                (
                    "to_bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits_to",
                        to="hospital.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-deposit_date", "-deposit_number"],
            },
        ),
        migrations.CreateModel(
            name="CashSale",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("sale_number", models.CharField(max_length=50, unique=True)),
                ("sale_date", models.DateField(default=django.utils.timezone.now)),
                ("customer_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sale_payments",
                        to="hospital.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_sales",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date", "-sale_number"],
            },
        ),
        migrations.CreateModel(
            name="BankReconciliationItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("is_matched", models.BooleanField(default=False)),
                (
                    "cheque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.cheque",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "reconciliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hospital.bankreconciliation",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hospital.banktransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["reconciliation", "created"],
            },
        ),
        migrations.CreateModel(
            name="AccountingCorporateAccount",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "account_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "receivable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corporate_accounts",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceReceivable",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("receivable_number", models.CharField(max_length=50, unique=True)),
                (
                    "claim_number",
                    models.CharField(
                        blank=True, help_text="Insurance claim number", max_length=100
                    ),
                ),
                ("claim_date", models.DateField(default=django.utils.timezone.now)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("balance_due", models.DecimalField(decimal_places=2, max_digits=15)),
                ("due_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Submission"),
                            ("submitted", "Submitted to Insurance"),
                            ("approved", "Approved by Insurance"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                            ("partial", "Partially Paid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_date", models.DateField(blank=True, null=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "insurance_company",
                    models.ForeignKey(
                        limit_choices_to={"payer_type": "insurance"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivables",
                        to="hospital.payer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_receivables",
                        to="hospital.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_receivables",
                        to="hospital.patient",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insurance_receivables",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-claim_date", "-receivable_number"],
                "indexes": [
                    models.Index(
                        fields=["insurance_company", "status"],
                        name="hospital_in_insuran_6e0344_idx",
                    ),
                    models.Index(
                        fields=["due_date", "status"],
                        name="hospital_in_due_dat_ea6b34_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Cashbook",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("entry_number", models.CharField(max_length=50, unique=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("receipt", "Receipt"), ("payment", "Payment")],
                        max_length=20,
                    ),
                ),
                ("entry_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payee_or_payer",
                    models.CharField(
                        help_text="Name of person/entity receiving or making payment",
                        max_length=200,
                    ),
                ),
                ("description", models.TextField()),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("mobile_money", "Mobile Money"),
                            ("card", "Card"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (Held)"),
                            ("classified", "Classified to Revenue"),
                            ("void", "Void"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "held_until",
                    models.DateField(
                        help_text="Date when entry can be classified to revenue (next day after entry date)"
                    ),
                ),
                ("classified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cash_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cashbook_entries",
                        to="hospital.account",
                    ),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_entries",
                        to="hospital.cheque",
                    ),
                ),
                (
                    "classified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_classified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_entries_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_expenses",
                        to="hospital.account",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.patient",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cashbook_revenues",
                        to="hospital.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_date", "-entry_number"],
                "indexes": [
                    models.Index(
                        fields=["entry_date", "status"],
                        name="hospital_ca_entry_d_5e9387_idx",
                    ),
                    models.Index(
                        fields=["held_until", "status"],
                        name="hospital_ca_held_un_4acfe2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountingPayrollEntry",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("gross_pay", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "consultation_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="30% of consultation fees",
                        max_digits=15,
                    ),
                ),
                (
                    "surgery_commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="30% of surgery fees",
                        max_digits=15,
                    ),
                ),
                (
                    "operational_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="10% for operational items",
                        max_digits=15,
                    ),
                ),
                (
                    "hospital_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Remaining share to hospital",
                        max_digits=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="hospital.accountingpayroll",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_entries",
                        to="hospital.staff",
                    ),
                ),
            ],
            options={
                "ordering": ["payroll", "staff"],
                "unique_together": {("payroll", "staff")},
            },
        ),
    ]
