# Generated by Django 4.2.7 on 2025-11-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1035_accountingpayroll_bankreconciliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorcommission",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"profession": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commissions",
                to="hospital.staff",
            ),
        ),
    ]
