# Generated by Django 4.2.7 on 2025-11-24 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1036_alter_doctorcommission_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndepositedFunds',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('laboratory_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pharmacy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('surgeries_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('admissions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('radiology_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dental_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('physiotherapy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending (Not Deposited)'), ('deposited', 'Deposited to Bank'), ('matched', 'Matched to Revenue')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('deposit_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='hospital.bankaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.advancedjournalentry')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_undeposited_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Undeposited Funds',
                'ordering': ['-entry_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceReceivableEntry',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('registration_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('laboratory_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pharmacy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('surgeries_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('admissions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('radiology_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dental_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('physiotherapy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending (Not Matched)'), ('matched', 'Matched to Revenue'), ('partially_paid', 'Partially Paid'), ('paid', 'Fully Paid')], default='pending', max_length=20)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.advancedjournalentry')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_receivables', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_entries', to='hospital.payer')),
            ],
            options={
                'verbose_name_plural': 'Insurance Receivable Entries',
                'ordering': ['-entry_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePaymentReceived',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entry_number', models.CharField(max_length=50, unique=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='WHT rate as percentage', max_digits=5)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_payments', to='hospital.bankaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.advancedjournalentry')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='hospital.payer')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_insurance_payments', to=settings.AUTH_USER_MODEL)),
                ('receivable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospital.insurancereceivableentry')),
            ],
            options={
                'verbose_name_plural': 'Insurance Payments Received',
                'ordering': ['-entry_date', '-created'],
            },
        ),
    ]
