# Generated by Django 4.2.7 on 2025-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1037_primecare_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='held_until',
            field=models.DateField(blank=True, help_text='Date when entry can be classified to revenue (next day after entry date)', null=True),
        ),
    ]
