# Generated by Django 4.2.7 on 2025-11-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1038_fix_cashbook_held_until_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='daily_cash_notes',
            field=models.TextField(blank=True, help_text='Notes to match cash sales - updated throughout the day'),
        ),
        migrations.AlterField(
            model_name='cashiersession',
            name='notes',
            field=models.TextField(blank=True, help_text='General session notes'),
        ),
    ]
