# Generated by Django 4.2.7 on 2025-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1040_add_procurement_enhanced_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('procurement_manager', 'Procurement Manager'), ('store_manager', 'Store Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffperformancesnapshot',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('procurement_manager', 'Procurement Manager'), ('store_manager', 'Store Manager')], max_length=30),
        ),
    ]
