# Generated by Django 4.2.7 on 2025-11-28 11:31
# FIXED: Safe migration that only removes fields from existing tables

import django.core.validators
from django.db import migrations, models, connection


def safe_remove_all_fields(apps, schema_editor):
    """Safely remove fields only if tables and columns exist"""
    db_alias = schema_editor.connection.alias
    with connection.cursor() as cursor:
        # List of (table_name, column_name) tuples to safely remove
        # Only includes fields that might need removal - skips non-existent tables
        fields_to_remove = []
        
        # Check which tables exist first
        cursor.execute("""
            SELECT table_name FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name LIKE 'hospital_%'
            ORDER BY table_name;
        """)
        existing_tables = {row[0] for row in cursor.fetchall()}
        
        # Only try to remove fields from tables that exist
        potential_removals = [
            ('hospital_undepositedfunds', 'bank_account_id'),
            ('hospital_undepositedfunds', 'journal_entry_id'),
            ('hospital_undepositedfunds', 'matched_by_id'),
        ]
        
        for table_name, column_name in potential_removals:
            if table_name in existing_tables:
                # Check if column exists
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.columns 
                        WHERE table_schema = 'public' 
                        AND table_name = %s AND column_name = %s
                    );
                """, [table_name, column_name])
                
                if cursor.fetchone()[0]:
                    try:
                        # Drop foreign key constraint first if exists
                        cursor.execute(f"""
                            DO $$
                            BEGIN
                                IF EXISTS (
                                    SELECT 1 FROM information_schema.table_constraints 
                                    WHERE table_schema = 'public' 
                                    AND table_name = '{table_name}'
                                    AND constraint_type = 'FOREIGN KEY'
                                    AND constraint_name LIKE '%{column_name}%'
                                ) THEN
                                    ALTER TABLE {table_name} DROP CONSTRAINT IF EXISTS {table_name}_{column_name}_fkey;
                                END IF;
                            END $$;
                        """)
                        cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name} CASCADE;")
                        print(f"✅ Removed {table_name}.{column_name}")
                    except Exception as e:
                        print(f"⚠️  Skipped {table_name}.{column_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1041_add_procurement_manager_profession'),
    ]

    operations = [
        # Use RunPython to safely remove fields only from existing tables
        migrations.RunPython(safe_remove_all_fields, migrations.RunPython.noop),
        
        # Patient phone number validation updates (safe - table exists)
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, default='', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233241234567' or '0241234567'. Up to 15 digits allowed.", regex='^(\\+?233|0)?[0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+233241234567' or '0241234567'. Up to 15 digits allowed.", regex='^(\\+?233|0)?[0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
