# Generated by Django 4.2.7 on 2025-11-30 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1043_add_patient_duplicate_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithholdingTaxPayable",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("withholding_number", models.CharField(max_length=50, unique=True)),
                (
                    "withholding_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "supplier_name",
                    models.CharField(help_text="Supplier/vendor name", max_length=200),
                ),
                (
                    "supplier_tin",
                    models.CharField(
                        blank=True, help_text="Supplier TIN number", max_length=50
                    ),
                ),
                (
                    "is_exempted",
                    models.BooleanField(
                        default=False, help_text="Whether supplier is exempted from WHT"
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gross amount before WHT",
                        max_digits=15,
                    ),
                ),
                (
                    "withholding_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="WHT rate as percentage (3, 5, 7.5, or 20)",
                        max_digits=5,
                    ),
                ),
                (
                    "withholding_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount withheld", max_digits=15
                    ),
                ),
                (
                    "net_amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Net amount paid to supplier (gross - WHT)",
                        max_digits=15,
                    ),
                ),
                (
                    "supply_type",
                    models.CharField(
                        choices=[
                            ("goods", "Goods (3%)"),
                            ("works", "Works (5%)"),
                            ("local_services", "Local Services (7.5%)"),
                            ("foreign_services", "Foreign Services (20%)"),
                        ],
                        default="goods",
                        max_length=20,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount of WHT paid to GRA",
                        max_digits=15,
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2, help_text="Balance due to GRA", max_digits=15
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for WHT payment to GRA",
                        null=True,
                    ),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Withholding Tax Payable",
                "ordering": ["-withholding_date", "-withholding_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="drug",
            options={
                "ordering": ["name"],
                "verbose_name": "Drug",
                "verbose_name_plural": "Drugs",
            },
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="grn_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount from Goods Received Note",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="grn_number",
            field=models.CharField(
                blank=True, help_text="Goods Received Note number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="invoice_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount from supplier invoice",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="is_matched",
            field=models.BooleanField(
                default=False,
                help_text="Whether 3-way matching is complete (PO, Invoice, GRN)",
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="purchase_order_number",
            field=models.CharField(
                blank=True, help_text="Purchase Order number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="supplier_is_exempted",
            field=models.BooleanField(
                default=False, help_text="Whether supplier is exempted from WHT"
            ),
        ),
        migrations.AddField(
            model_name="accountspayable",
            name="supply_type",
            field=models.CharField(
                choices=[
                    ("goods", "Goods (3% WHT)"),
                    ("works", "Works (5% WHT)"),
                    ("local_services", "Local Services (7.5% WHT)"),
                    ("foreign_services", "Foreign Services (20% WHT)"),
                ],
                default="goods",
                help_text="Type of supply for WHT calculation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="drug",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "analgesic_non_narcotic",
                        "Analgesics (Non-Narcotic) - For mild pain",
                    ),
                    ("analgesic_narcotic", "Analgesics (Narcotic) - For severe pain"),
                    ("antipyretic", "Antipyretics - Drugs that reduce fever"),
                    (
                        "antihypertensive",
                        "Antihypertensives - Drugs that lower blood pressure",
                    ),
                    (
                        "antiarrhythmic",
                        "Antiarrhythmics - Control heartbeat irregularities",
                    ),
                    (
                        "beta_blocker",
                        "Beta-Blockers - Reduce heart rate and oxygen needs",
                    ),
                    ("anticoagulant", "Anticoagulants - Prevent blood clotting"),
                    (
                        "thrombolytic",
                        "Thrombolytics - Dissolve and disperse blood clots",
                    ),
                    ("antibiotic", "Antibiotics - Combat bacterial infections"),
                    ("antibacterial", "Antibacterials - Treat infections"),
                    ("antifungal", "Antifungals - Treat fungal infections"),
                    ("antiviral", "Antivirals - Treat viral infections"),
                    ("anticonvulsant", "Anticonvulsants - Prevent epileptic seizures"),
                    (
                        "antipsychotic",
                        "Antipsychotics - Treat severe psychiatric disorders",
                    ),
                    (
                        "antianxiety",
                        "Antianxiety Drugs - Suppress anxiety, relax muscles",
                    ),
                    ("antidepressant", "Antidepressants - Mood-lifting medications"),
                    ("sedative", "Sedatives - Calming or sedative effect"),
                    ("sleeping_drug", "Sleeping Drugs - Induce sleep"),
                    ("bronchodilator", "Bronchodilators - Open bronchial tubes"),
                    ("cough_suppressant", "Cough Suppressants - Suppress coughing"),
                    ("expectorant", "Expectorants - Stimulate phlegm elimination"),
                    ("decongestant", "Decongestants - Relieve nasal stuffiness"),
                    ("cold_cure", "Cold Cures - Relieve cold symptoms"),
                    ("antacid", "Antacids - Relieve indigestion and heartburn"),
                    ("antidiarrheal", "Antidiarrheals - Relief of diarrhea"),
                    ("antiemetic", "Antiemetics - Treat nausea and vomiting"),
                    ("laxative", "Laxatives - Increase bowel movements"),
                    ("anti_inflammatory", "Anti-Inflammatories - Reduce inflammation"),
                    ("corticosteroid", "Corticosteroids - Anti-inflammatory hormones"),
                    (
                        "immunosuppressive",
                        "Immunosuppressives - Prevent immune reactions",
                    ),
                    ("antineoplastic", "Antineoplastics - Treat cancer"),
                    ("cytotoxic", "Cytotoxics - Kill or damage cells"),
                    ("hormone", "Hormones - Hormone replacement therapy"),
                    (
                        "female_sex_hormone",
                        "Female Sex Hormones - Estrogens and progesterone",
                    ),
                    ("male_sex_hormone", "Male Sex Hormones - Androgenic hormones"),
                    ("oral_hypoglycemic", "Oral Hypoglycemics - Lower blood glucose"),
                    ("muscle_relaxant", "Muscle Relaxants - Relieve muscle spasm"),
                    ("antihistamine", "Antihistamines - Counteract histamine effects"),
                    ("vitamin", "Vitamins - Essential chemicals for health"),
                    ("other", "Other - Miscellaneous drugs"),
                ],
                default="other",
                help_text="Drug category classification",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank account used for payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_vouchers",
                to="hospital.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="memo",
            field=models.TextField(
                blank=True, help_text="Memo/details for the payment"
            ),
        ),
        migrations.AlterField(
            model_name="accountspayable",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, help_text="Gross amount from invoice", max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="form",
            field=models.CharField(
                help_text="tablet, capsule, injection, etc.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="drug",
            name="is_controlled",
            field=models.BooleanField(
                default=False,
                help_text="Controlled substance requiring special handling",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="account_number",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use bank_account instead",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use bank_account instead",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["category"], name="hospital_dr_categor_5a8181_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(fields=["name"], name="hospital_dr_name_5e3522_idx"),
        ),
        migrations.AddIndex(
            model_name="drug",
            index=models.Index(
                fields=["is_active", "category"], name="hospital_dr_is_acti_6bd940_idx"
            ),
        ),
        migrations.AddField(
            model_name="withholdingtaxpayable",
            name="accounts_payable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withholding_taxes",
                to="hospital.accountspayable",
            ),
        ),
        migrations.AddField(
            model_name="withholdingtaxpayable",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital.advancedjournalentry",
            ),
        ),
        migrations.AddField(
            model_name="withholdingtaxpayable",
            name="payable_account",
            field=models.ForeignKey(
                help_text="WHT Payable account (Current Liability)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withholding_tax_payables",
                to="hospital.account",
            ),
        ),
        migrations.AddField(
            model_name="withholdingtaxpayable",
            name="payment_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="withholding_taxes",
                to="hospital.paymentvoucher",
            ),
        ),
    ]
