# Generated by Django 4.2.7 on 2025-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "1044_add_comprehensive_drug_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "analgesic",
                        "Analgesics - Relieve pain (non-narcotic for mild pain, narcotic for severe pain)",
                    ),
                    ("antipyretic", "Antipyretics - Drugs that reduce fever"),
                    (
                        "antihypertensive",
                        "Antihypertensives - Lower blood pressure (includes diuretics, beta-blockers, calcium channel blockers, ACE inhibitors)",
                    ),
                    (
                        "antiarrhythmic",
                        "Antiarrhythmics - Control irregularities of heartbeat",
                    ),
                    (
                        "beta_blocker",
                        "Beta-Blockers - Reduce oxygen needs of heart by reducing heartbeat rate",
                    ),
                    ("anticoagulant", "Anticoagulants - Prevent blood from clotting"),
                    (
                        "thrombolytic",
                        "Thrombolytics - Dissolve and disperse blood clots",
                    ),
                    (
                        "diuretic",
                        "Diuretics - Increase urine production, rid body of excess fluid",
                    ),
                    (
                        "antibiotic",
                        "Antibiotics - Combat bacterial infections (naturally occurring and synthetic substances)",
                    ),
                    (
                        "antibacterial",
                        "Antibacterials - Drugs used to treat infections",
                    ),
                    (
                        "antiviral",
                        "Antivirals - Treat viral infections or provide temporary protection (e.g., influenza)",
                    ),
                    (
                        "antifungal",
                        "Antifungals - Treat fungal infections (hair, skin, nails, mucous membranes)",
                    ),
                    ("anticonvulsant", "Anticonvulsants - Prevent epileptic seizures"),
                    (
                        "antipsychotic",
                        "Antipsychotics - Treat symptoms of severe psychiatric disorders (major tranquilizers)",
                    ),
                    (
                        "antidepressant",
                        "Antidepressants - Mood-lifting medications (tricyclics, MAOIs, SSRIs)",
                    ),
                    (
                        "antianxiety",
                        "Antianxiety Drugs - Suppress anxiety and relax muscles (anxiolytics, sedatives, minor tranquilizers)",
                    ),
                    (
                        "tranquilizer",
                        "Tranquilizers - Drugs with calming or sedative effect (minor = antianxiety, major = antipsychotic)",
                    ),
                    (
                        "sedative",
                        "Sedatives - Calming or sedative effect (same as antianxiety drugs)",
                    ),
                    (
                        "sleeping_drug",
                        "Sleeping Drugs - Induce sleep (benzodiazepines and barbiturates)",
                    ),
                    (
                        "bronchodilator",
                        "Bronchodilators - Open bronchial tubes in lungs (e.g., for asthma)",
                    ),
                    (
                        "cough_suppressant",
                        "Cough Suppressants - Suppress coughing reflex or alter phlegm consistency (includes expectorants, mucolytics)",
                    ),
                    (
                        "expectorant",
                        "Expectorants - Stimulate flow of saliva and promote coughing to eliminate phlegm",
                    ),
                    (
                        "decongestant",
                        "Decongestants - Reduce swelling of nasal mucous membranes, relieve nasal stuffiness",
                    ),
                    (
                        "cold_cure",
                        "Cold Cures - Relieve aches, pains, and fever accompanying colds (aspirin, acetaminophen with decongestant/antihistamine)",
                    ),
                    (
                        "antacid",
                        "Antacids - Relieve indigestion and heartburn by neutralizing stomach acid",
                    ),
                    (
                        "antidiarrheal",
                        "Antidiarrheals - Relief of diarrhea (adsorbent substances or drugs that slow bowel contractions)",
                    ),
                    ("antiemetic", "Antiemetics - Treat nausea and vomiting"),
                    (
                        "laxative",
                        "Laxatives - Increase frequency and ease of bowel movements (stimulant, bulk, or lubricating)",
                    ),
                    (
                        "anti_inflammatory",
                        "Anti-Inflammatories - Reduce inflammation (redness, heat, swelling in infections and chronic diseases)",
                    ),
                    (
                        "corticosteroid",
                        "Corticosteroids - Hormonal preparations used as anti-inflammatories (arthritis, asthma) or immunosuppressives",
                    ),
                    (
                        "immunosuppressive",
                        "Immunosuppressives - Prevent or reduce body's reaction to disease or foreign tissues (autoimmune diseases, organ transplants)",
                    ),
                    (
                        "antihistamine",
                        "Antihistamines - Counteract effects of histamine (chemical involved in allergic reactions)",
                    ),
                    ("antineoplastic", "Antineoplastics - Drugs used to treat cancer"),
                    (
                        "cytotoxic",
                        "Cytotoxics - Kill or damage cells (used as antineoplastics for cancer and as immunosuppressives)",
                    ),
                    (
                        "hormone",
                        "Hormones - Chemicals from endocrine glands, used in hormone replacement therapy",
                    ),
                    (
                        "female_sex_hormone",
                        "Female Sex Hormones - Estrogens and progesterone (treat menstrual/menopausal disorders, oral contraceptives)",
                    ),
                    (
                        "male_sex_hormone",
                        "Male Sex Hormones - Androgenic hormones like testosterone (compensate deficiency, treat breast cancer)",
                    ),
                    (
                        "oral_hypoglycemic",
                        "Oral Hypoglycemics - Lower blood glucose levels (used in diabetes mellitus)",
                    ),
                    (
                        "muscle_relaxant",
                        "Muscle Relaxants - Relieve muscle spasm (e.g., backache, often antianxiety drugs with muscle-relaxant action)",
                    ),
                    (
                        "vitamin",
                        "Vitamins - Essential chemicals for good health (not manufactured by body, needed in diet or supplements)",
                    ),
                    (
                        "other",
                        "Other - Miscellaneous drugs not fitting above categories",
                    ),
                ],
                default="other",
                help_text="Drug category classification",
                max_length=50,
            ),
        ),
    ]
