# Generated by Django 4.2.7 on 2025-12-14 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hospital", "1045_reorganize_drug_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="category",
            field=models.CharField(
                choices=[
                    (
                        "analgesic",
                        "Analgesics - Relieve pain (non-narcotic for mild pain, narcotic for severe pain)",
                    ),
                    ("antipyretic", "Antipyretics - Drugs that reduce fever"),
                    (
                        "barbiturate",
                        "Barbiturates - Sleeping drugs (used less commonly than benzodiazepines)",
                    ),
                    (
                        "antihypertensive",
                        "Antihypertensives - Lower blood pressure (includes diuretics, beta-blockers, calcium channel blockers, ACE inhibitors)",
                    ),
                    (
                        "antiarrhythmic",
                        "Antiarrhythmics - Control irregularities of heartbeat",
                    ),
                    (
                        "beta_blocker",
                        "Beta-Blockers - Reduce oxygen needs of heart by reducing heartbeat rate",
                    ),
                    ("anticoagulant", "Anticoagulants - Prevent blood from clotting"),
                    (
                        "thrombolytic",
                        "Thrombolytics - Dissolve and disperse blood clots",
                    ),
                    (
                        "diuretic",
                        "Diuretics - Increase urine production, rid body of excess fluid",
                    ),
                    (
                        "antibiotic",
                        "Antibiotics - Combat bacterial infections (naturally occurring and synthetic substances)",
                    ),
                    (
                        "antibacterial",
                        "Antibacterials - Drugs used to treat infections",
                    ),
                    (
                        "antiviral",
                        "Antivirals - Treat viral infections or provide temporary protection (e.g., influenza)",
                    ),
                    (
                        "antifungal",
                        "Antifungals - Treat fungal infections (hair, skin, nails, mucous membranes)",
                    ),
                    ("anticonvulsant", "Anticonvulsants - Prevent epileptic seizures"),
                    (
                        "antipsychotic",
                        "Antipsychotics - Treat symptoms of severe psychiatric disorders (major tranquilizers)",
                    ),
                    (
                        "antidepressant",
                        "Antidepressants - Mood-lifting medications (tricyclics, MAOIs, SSRIs)",
                    ),
                    (
                        "antianxiety",
                        "Antianxiety Drugs - Suppress anxiety and relax muscles (anxiolytics, sedatives, minor tranquilizers)",
                    ),
                    (
                        "tranquilizer",
                        "Tranquilizers - Drugs with calming or sedative effect (minor = antianxiety, major = antipsychotic)",
                    ),
                    (
                        "sedative",
                        "Sedatives - Calming or sedative effect (same as antianxiety drugs)",
                    ),
                    (
                        "sleeping_drug",
                        "Sleeping Drugs - Induce sleep (benzodiazepines and barbiturates)",
                    ),
                    (
                        "bronchodilator",
                        "Bronchodilators - Open bronchial tubes in lungs (e.g., for asthma)",
                    ),
                    (
                        "cough_suppressant",
                        "Cough Suppressants - Suppress coughing reflex or alter phlegm consistency (includes expectorants, mucolytics)",
                    ),
                    (
                        "expectorant",
                        "Expectorants - Stimulate flow of saliva and promote coughing to eliminate phlegm",
                    ),
                    (
                        "decongestant",
                        "Decongestants - Reduce swelling of nasal mucous membranes, relieve nasal stuffiness",
                    ),
                    (
                        "cold_cure",
                        "Cold Cures - Relieve aches, pains, and fever accompanying colds (aspirin, acetaminophen with decongestant/antihistamine)",
                    ),
                    (
                        "antacid",
                        "Antacids - Relieve indigestion and heartburn by neutralizing stomach acid",
                    ),
                    (
                        "antidiarrheal",
                        "Antidiarrheals - Relief of diarrhea (adsorbent substances or drugs that slow bowel contractions)",
                    ),
                    ("antiemetic", "Antiemetics - Treat nausea and vomiting"),
                    (
                        "laxative",
                        "Laxatives - Increase frequency and ease of bowel movements (stimulant, bulk, or lubricating)",
                    ),
                    (
                        "anti_inflammatory",
                        "Anti-Inflammatories - Reduce inflammation (redness, heat, swelling in infections and chronic diseases)",
                    ),
                    (
                        "corticosteroid",
                        "Corticosteroids - Hormonal preparations used as anti-inflammatories (arthritis, asthma) or immunosuppressives",
                    ),
                    (
                        "immunosuppressive",
                        "Immunosuppressives - Prevent or reduce body's reaction to disease or foreign tissues (autoimmune diseases, organ transplants)",
                    ),
                    (
                        "antihistamine",
                        "Antihistamines - Counteract effects of histamine (chemical involved in allergic reactions)",
                    ),
                    ("antineoplastic", "Antineoplastics - Drugs used to treat cancer"),
                    (
                        "cytotoxic",
                        "Cytotoxics - Kill or damage cells (used as antineoplastics for cancer and as immunosuppressives)",
                    ),
                    (
                        "hormone",
                        "Hormones - Chemicals from endocrine glands, used in hormone replacement therapy",
                    ),
                    (
                        "female_sex_hormone",
                        "Female Sex Hormones - Estrogens and progesterone (treat menstrual/menopausal disorders, oral contraceptives)",
                    ),
                    (
                        "male_sex_hormone",
                        "Male Sex Hormones - Androgenic hormones like testosterone (compensate deficiency, treat breast cancer)",
                    ),
                    (
                        "oral_hypoglycemic",
                        "Oral Hypoglycemics - Lower blood glucose levels (used in diabetes mellitus)",
                    ),
                    (
                        "muscle_relaxant",
                        "Muscle Relaxants - Relieve muscle spasm (e.g., backache, often antianxiety drugs with muscle-relaxant action)",
                    ),
                    (
                        "vitamin",
                        "Vitamins - Essential chemicals for good health (not manufactured by body, needed in diet or supplements)",
                    ),
                    (
                        "other",
                        "Other - Miscellaneous drugs not fitting above categories",
                    ),
                ],
                default="other",
                help_text="Drug category classification",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="profession",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("pharmacist", "Pharmacist"),
                    ("lab_technician", "Lab Technician"),
                    ("radiologist", "Radiologist"),
                    ("admin", "Administrator"),
                    ("receptionist", "Receptionist"),
                    ("cashier", "Cashier"),
                    ("hr_manager", "HR Manager"),
                    ("accountant", "Accountant"),
                    ("account_personnel", "Account Personnel"),
                    ("account_officer", "Account Officer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staffperformancesnapshot",
            name="role",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("nurse", "Nurse"),
                    ("pharmacist", "Pharmacist"),
                    ("lab_technician", "Lab Technician"),
                    ("radiologist", "Radiologist"),
                    ("admin", "Administrator"),
                    ("receptionist", "Receptionist"),
                    ("cashier", "Cashier"),
                    ("hr_manager", "HR Manager"),
                    ("accountant", "Accountant"),
                    ("account_personnel", "Account Personnel"),
                    ("account_officer", "Account Officer"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PettyCashTransaction",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("transaction_number", models.CharField(max_length=50, unique=True)),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.TextField(help_text="Purpose of the petty cash transaction"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(
                        help_text="Name of person receiving payment", max_length=200
                    ),
                ),
                (
                    "payee_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Staff, Vendor, Supplier",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Account Officer Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("rejected_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection if applicable"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, help_text="Date payment was made", null=True
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Receipt number if available",
                        max_length=100,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or comments"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Account Officer who approved this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Account Personnel who created this transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="Expense account to debit",
                        limit_choices_to={"account_type": "expense"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="petty_cash_transactions",
                        to="hospital.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.advancedjournalentry",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="petty_cash_rejected",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Petty Cash Transaction",
                "verbose_name_plural": "Petty Cash Transactions",
                "ordering": ["-transaction_date", "-created"],
            },
        ),
    ]
