# Generated by Django 4.2.7 on 2025-12-15 14:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1046_alter_drug_category_alter_staff_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('account_personnel', 'Account Personnel'), ('account_officer', 'Account Officer'), ('inventory_manager', 'Inventory Manager'), ('store_manager', 'Store Manager'), ('procurement_officer', 'Procurement Officer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffperformancesnapshot',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('account_personnel', 'Account Personnel'), ('account_officer', 'Account Officer'), ('inventory_manager', 'Inventory Manager'), ('store_manager', 'Store Manager'), ('procurement_officer', 'Procurement Officer')], max_length=30),
        ),
        migrations.CreateModel(
            name='PatientDeposit',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deposit_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('deposit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Total amount deposited', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining balance available for use', max_digits=15)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already applied to invoices', max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference/transaction ID', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active (Available)'), ('fully_used', 'Fully Used'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the deposit')),
                ('bank_account', models.ForeignKey(blank=True, help_text='Bank account if payment was via bank transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.bankaccount')),
                ('created_by', models.ForeignKey(help_text='User who created this deposit record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry for accounting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_deposits', to='hospital.advancedjournalentry')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='hospital.patient')),
                ('received_by', models.ForeignKey(help_text='Staff member who received the deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_received', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Accounting transaction for this deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_deposits', to='hospital.transaction')),
            ],
            options={
                'verbose_name': 'Patient Deposit',
                'verbose_name_plural': 'Patient Deposits',
                'ordering': ['-deposit_date', '-deposit_number'],
            },
        ),
        migrations.CreateModel(
            name='DepositApplication',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('applied_by', models.ForeignKey(help_text='User who applied this deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_applications', to=settings.AUTH_USER_MODEL)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hospital.patientdeposit')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_applications', to='hospital.invoice')),
            ],
            options={
                'verbose_name': 'Deposit Application',
                'verbose_name_plural': 'Deposit Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.AddIndex(
            model_name='patientdeposit',
            index=models.Index(fields=['patient', 'status'], name='hospital_pa_patient_4f2e77_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdeposit',
            index=models.Index(fields=['deposit_date'], name='hospital_pa_deposit_deda91_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdeposit',
            index=models.Index(fields=['deposit_number'], name='hospital_pa_deposit_801d33_idx'),
        ),
        migrations.AddIndex(
            model_name='depositapplication',
            index=models.Index(fields=['deposit', 'invoice'], name='hospital_de_deposit_89f98e_idx'),
        ),
        migrations.AddIndex(
            model_name='depositapplication',
            index=models.Index(fields=['applied_date'], name='hospital_de_applied_7730af_idx'),
        ),
    ]
