# Generated by Django 4.2.7 on 2025-12-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1049_harden_password_reset_otp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetotp',
            new_name='hospital_pa_user_id_7a9317_idx',
            old_name='hospital_pa_user_id_3f1e15_idx',
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('account_personnel', 'Account Personnel'), ('account_officer', 'Account Officer'), ('inventory_manager', 'Inventory Manager'), ('store_manager', 'Store Manager'), ('procurement_officer', 'Procurement Officer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffperformancesnapshot',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('account_personnel', 'Account Personnel'), ('account_officer', 'Account Officer'), ('inventory_manager', 'Inventory Manager'), ('store_manager', 'Store Manager'), ('procurement_officer', 'Procurement Officer')], max_length=30),
        ),
        # Note: UniqueConstraint added in a separate migration after fixing duplicates
        # migrations.AddConstraint(
        #     model_name='patient',
        #     constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('date_of_birth', '2000-01-01'), _negated=True)), fields=('first_name', 'last_name', 'phone_number', 'date_of_birth'), name='uniq_patient_name_phone_dob_active'),
        # ),
    ]
