# Generated by Django 4.2.7 on 2025-12-18 18:36

from django.db import migrations, models


def handle_duplicate_patients(apps, schema_editor):
    """Handle duplicate patients before creating unique constraint"""
    Patient = apps.get_model('hospital', 'Patient')
    
    # Find duplicates based on name, phone, and DOB (excluding deleted and default DOB)
    from django.db.models import Count, Q
    from django.utils import timezone
    
    duplicates = Patient.objects.filter(
        is_deleted=False
    ).exclude(
        date_of_birth='2000-01-01'
    ).values(
        'first_name', 'last_name', 'phone_number', 'date_of_birth'
    ).annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    # For each duplicate group, keep the oldest record and mark others as deleted
    for dup in duplicates:
        patients = Patient.objects.filter(
            first_name=dup['first_name'],
            last_name=dup['last_name'],
            phone_number=dup['phone_number'],
            date_of_birth=dup['date_of_birth'],
            is_deleted=False
        ).exclude(
            date_of_birth='2000-01-01'
        ).order_by('created')
        
        # Keep the first one, mark others as deleted
        if patients.count() > 1:
            keep_patient = patients.first()
            for patient in patients[1:]:
                patient.is_deleted = True
                patient.save(update_fields=['is_deleted'])


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1050_add_midwife_profession'),
    ]

    operations = [
        migrations.RunPython(handle_duplicate_patients, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('date_of_birth', '2000-01-01'), _negated=True)), fields=('first_name', 'last_name', 'phone_number', 'date_of_birth'), name='uniq_patient_name_phone_dob_active'),
        ),
    ]
