# Generated by Django 4.2.7 on 2025-12-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1052_add_chat_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporatePartnership',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=200)),
                ('partnership_type', models.CharField(choices=[('insurance', 'Insurance Provider'), ('corporate_wellness', 'Corporate Wellness Program'), ('referral_network', 'Referral Network'), ('sponsorship', 'Sponsorship Agreement'), ('joint_venture', 'Joint Venture'), ('supplier', 'Preferred Supplier'), ('other', 'Other')], max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('negotiating', 'Negotiating'), ('active', 'Active'), ('renewal', 'Renewal Pending'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='prospect', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Partnership value/revenue', max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Corporate Partnership',
                'verbose_name_plural': 'Corporate Partnerships',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('digital', 'Digital Campaign'), ('print', 'Print Media'), ('radio', 'Radio'), ('tv', 'Television'), ('event', 'Event-Based'), ('social_media', 'Social Media'), ('email', 'Email Marketing'), ('referral', 'Referral Program'), ('corporate', 'Corporate Partnership')], max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_reach', models.IntegerField(blank=True, help_text='Target audience reach', null=True)),
                ('actual_reach', models.IntegerField(default=0)),
                ('target_conversions', models.IntegerField(blank=True, help_text='Target conversions (e.g., appointments)', null=True)),
                ('actual_conversions', models.IntegerField(default=0)),
                ('target_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Return on Investment %', max_digits=8)),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketingMetric',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metric_type', models.CharField(choices=[('new_patients', 'New Patients Acquired'), ('website_visits', 'Website Visits'), ('social_media_followers', 'Social Media Followers'), ('email_subscribers', 'Email Subscribers'), ('referrals', 'Referrals Generated'), ('appointment_bookings', 'Appointment Bookings'), ('revenue', 'Revenue Generated'), ('brand_mentions', 'Brand Mentions'), ('lead_generation', 'Leads Generated'), ('conversion_rate', 'Conversion Rate')], max_length=50)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(blank=True, help_text="e.g., 'Google Ads', 'Facebook', 'Referral Program'", max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Marketing Metric',
                'verbose_name_plural': 'Marketing Metrics',
                'ordering': ['-date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='MarketingObjective',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('objective_type', models.CharField(choices=[('brand_awareness', 'Brand Awareness & Recognition'), ('patient_acquisition', 'Patient Acquisition & Growth'), ('corporate_partnerships', 'Corporate Partnerships'), ('digital_marketing', 'Digital Marketing & Online Presence'), ('community_outreach', 'Community Outreach & Engagement'), ('referral_programs', 'Referral Programs'), ('service_promotion', 'Service Promotion & Campaigns'), ('reputation_management', 'Reputation & Review Management')], max_length=50)),
                ('description', models.TextField()),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('target_metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_metric_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metric_type', models.CharField(blank=True, help_text="e.g., 'new_patients', 'revenue', 'website_visits'", max_length=50)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Marketing Objective',
                'verbose_name_plural': 'Marketing Objectives',
                'ordering': ['-priority', '-created'],
            },
        ),
        migrations.CreateModel(
            name='MarketingTask',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('content_creation', 'Content Creation'), ('campaign_setup', 'Campaign Setup'), ('event_planning', 'Event Planning'), ('partnership_outreach', 'Partnership Outreach'), ('social_media', 'Social Media Management'), ('seo_optimization', 'SEO Optimization'), ('advertising', 'Advertising & Promotion'), ('analytics_review', 'Analytics & Reporting'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'Under Review'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('budget_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Marketing Task',
                'verbose_name_plural': 'Marketing Tasks',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        # Skip PasswordResetOTP operations if model doesn't exist
        # migrations.RemoveField(
        #     model_name='passwordresetotp',
        #     name='user',
        # ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='hospital_ch_channel_399b3e_idx',
            old_name='hospital_ch_channel_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='hospital_ch_sender__745ec7_idx',
            old_name='hospital_ch_sender_created_idx',
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        # Skip PasswordResetOTP deletion if model doesn't exist
        # migrations.DeleteModel(
        #     name='PasswordResetOTP',
        # ),
        migrations.AddField(
            model_name='marketingtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_marketing_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='hospital.marketingtask'),
        ),
        migrations.AddField(
            model_name='marketingtask',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_tasks', to='hospital.marketingobjective'),
        ),
        migrations.AddField(
            model_name='marketingobjective',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, related_name='marketing_team_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingobjective',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingmetric',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='hospital.marketingcampaign'),
        ),
        migrations.AddField(
            model_name='marketingmetric',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='hospital.marketingobjective'),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='corporatepartnership',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_partnerships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='marketingmetric',
            unique_together={('metric_type', 'date', 'source')},
        ),
    ]
