# Generated by Django 4.2.7 on 2025-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1054_add_lab_management_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreagent',
            name='inventory_item_id',
            field=models.UUIDField(blank=True, help_text='Link to InventoryItem if added via procurement', null=True),
        ),
        migrations.AddField(
            model_name='labreagent',
            name='tests',
            field=models.ManyToManyField(blank=True, help_text='Lab tests that require this reagent', related_name='required_reagents', to='hospital.labtest'),
        ),
    ]
