# Generated by Django 4.2.7 on 2025-12-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1055_add_reagent_inventory_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagenttransaction',
            name='lab_result',
            field=models.ForeignKey(blank=True, help_text='Lab result/test for which reagent was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_transactions', to='hospital.labresult'),
        ),
        migrations.AddField(
            model_name='reagenttransaction',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient for whom reagent was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_usage', to='hospital.patient'),
        ),
        migrations.AddField(
            model_name='reagenttransaction',
            name='purpose',
            field=models.TextField(blank=True, help_text='Purpose/clinical indication for reagent usage'),
        ),
        migrations.AddField(
            model_name='reagenttransaction',
            name='test_name',
            field=models.CharField(blank=True, help_text='Name of test performed (for quick reference)', max_length=200),
        ),
    ]
