# Generated by Django 4.2.7 on 2025-12-23 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1056_add_reagent_accountability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatchannel',
            name='participant1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats_as_participant1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_chats_as_participant2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatchannel',
            name='channel_type',
            field=models.CharField(choices=[('admin', 'Admin Channel'), ('it', 'IT Operations'), ('general', 'General Discussion'), ('urgent', 'Urgent Alerts'), ('direct', 'Direct Message')], default='admin', max_length=20),
        ),
    ]
