# Generated by Django 4.2.7 on 2025-12-30 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1059_add_patient_pay_cash_to_invoiceline'),
    ]

    operations = [
        # Note: PasswordResetOTP operations removed as table doesn't exist
        migrations.RenameIndex(
            model_name='drugadministrationinventory',
            new_name='hospital_dr_adminis_939b57_idx',
            old_name='hospital_dr_administered_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='drugadministrationinventory',
            new_name='hospital_dr_drug_id_e92f32_idx',
            old_name='hospital_dr_drug_id_administered_idx',
        ),
        migrations.RenameIndex(
            model_name='drugadministrationinventory',
            new_name='hospital_dr_batch_n_de03b7_idx',
            old_name='hospital_dr_batch_nu_idx',
        ),
        migrations.RenameIndex(
            model_name='drugreturn',
            new_name='hospital_dr_return__211589_idx',
            old_name='hospital_dr_return_d_status_idx',
        ),
        migrations.RenameIndex(
            model_name='drugreturn',
            new_name='hospital_dr_patient_ec67da_idx',
            old_name='hospital_dr_patient__return_d_idx',
        ),
        migrations.RenameIndex(
            model_name='drugreturn',
            new_name='hospital_dr_drug_id_360e8f_idx',
            old_name='hospital_dr_drug_id_return_d_idx',
        ),
        migrations.RenameIndex(
            model_name='drugreturn',
            new_name='hospital_dr_status_cf3a44_idx',
            old_name='hospital_dr_status_return_d_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryhistorysummary',
            new_name='hospital_in_period__e5a731_idx',
            old_name='hospital_in_period__store_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryhistorysummary',
            new_name='hospital_in_invento_5d57b5_idx',
            old_name='hospital_in_inventor_period__idx',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_code',
            field=models.ForeignKey(blank=True, help_text='Link to DiagnosisCode for proper name display', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_diagnoses', to='hospital.diagnosiscode'),
        ),
        migrations.AddField(
            model_name='diagnosiscode',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who added this diagnosis code to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_codes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosiscode',
            name='is_africa_common',
            field=models.BooleanField(db_index=True, default=False, help_text='Commonly seen in African healthcare settings'),
        ),
        migrations.AddField(
            model_name='diagnosiscode',
            name='is_ghana_common',
            field=models.BooleanField(db_index=True, default=False, help_text='Commonly seen in Ghana healthcare settings'),
        ),
        migrations.AddField(
            model_name='diagnosiscode',
            name='local_name',
            field=models.CharField(blank=True, help_text='Local/Ghanaian name for this condition (if applicable)', max_length=200),
        ),
        migrations.AddField(
            model_name='diagnosiscode',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this diagnosis in Ghana context'),
        ),
        migrations.AddField(
            model_name='diagnosiscode',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this diagnosis code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_codes_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_type', 'direct')), fields=('participant1', 'participant2'), name='unique_direct_chat'),
        ),
        # Note: PasswordResetOTP deletion skipped - table doesn't exist
    ]
