# Generated by Django 4.2.7 on 2025-12-31 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1060_add_diagnosis_tracking_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMedicalChit',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chit_number', models.CharField(help_text='Unique chit identifier (e.g., CHIT-2024-001)', max_length=50, unique=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now, help_text='Date staff applied for medical chit')),
                ('reason', models.TextField(help_text='Reason for requiring medical attention')),
                ('symptoms', models.TextField(blank=True, help_text='Symptoms or medical condition description')),
                ('status', models.CharField(choices=[('pending', 'Pending HR Approval'), ('approved', 'Approved - Ready for Medical Attention'), ('rejected', 'Rejected'), ('used', 'Used - Visit Created'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('hr_approval_date', models.DateTimeField(blank=True, help_text='Date and time HR approved this chit', null=True)),
                ('hr_approval_notes', models.TextField(blank=True, help_text='HR approval notes or comments')),
                ('hr_rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('visit_created_at', models.DateTimeField(blank=True, help_text='When the visit was created at front desk', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Chit validity expiration date (default: 7 days from approval)', null=True)),
                ('sms_sent_approval', models.BooleanField(default=False, help_text='SMS sent to staff when approved')),
                ('sms_sent_visit_ready', models.BooleanField(default=False, help_text='SMS sent when chit is ready for visit')),
                ('authorized_by_name', models.CharField(blank=True, help_text='Name of HR/Admin who authorized (for printing)', max_length=200)),
                ('authorized_by_signature', models.CharField(blank=True, help_text='Signature of authorizing person (for printing)', max_length=200)),
                ('encounter', models.ForeignKey(blank=True, help_text='Visit/encounter created from this chit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_chit', to='hospital.encounter')),
                ('hr_approved_by', models.ForeignKey(blank=True, help_text='HR staff who approved this chit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_medical_chits', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_chits', to='hospital.staff')),
                ('visit_created_by', models.ForeignKey(blank=True, help_text='Front desk staff who created the visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits_from_chits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Medical Chit',
                'verbose_name_plural': 'Staff Medical Chits',
                'ordering': ['-application_date', '-created'],
            },
        ),
        migrations.AddIndex(
            model_name='staffmedicalchit',
            index=models.Index(fields=['chit_number'], name='hospital_st_chit_nu_5c3ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmedicalchit',
            index=models.Index(fields=['status'], name='hospital_st_status_714364_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmedicalchit',
            index=models.Index(fields=['staff', 'status'], name='hospital_st_staff_i_bbe01a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmedicalchit',
            index=models.Index(fields=['application_date'], name='hospital_st_applica_03dd0d_idx'),
        ),
    ]
