# Generated by Django 4.2.7 on 2026-01-03 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1061_staffmedicalchit_delete_passwordresetotp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychiatricChart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chart_date', models.DateField(default=datetime.date.today)),
                ('chief_complaint', models.TextField(blank=True)),
                ('presenting_problem', models.TextField(blank=True)),
                ('duration_of_symptoms', models.CharField(blank=True, max_length=100)),
                ('appearance', models.TextField(blank=True, help_text='General appearance, grooming, dress')),
                ('behavior', models.TextField(blank=True, help_text='Motor activity, eye contact, rapport')),
                ('speech', models.TextField(blank=True, help_text='Rate, rhythm, volume, quality')),
                ('mood', models.CharField(blank=True, help_text="Patient's subjective mood", max_length=100)),
                ('affect', models.CharField(blank=True, help_text='Observed emotional expression', max_length=100)),
                ('thought_process', models.TextField(blank=True, help_text='Form of thought, flow, organization')),
                ('thought_content', models.TextField(blank=True, help_text='Delusions, obsessions, suicidal/homicidal ideation')),
                ('perception', models.TextField(blank=True, help_text='Hallucinations, illusions, depersonalization')),
                ('cognition', models.TextField(blank=True, help_text='Orientation, memory, attention, concentration')),
                ('insight', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=50)),
                ('judgment', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=50)),
                ('phq9_score', models.IntegerField(blank=True, help_text='PHQ-9 Depression Scale (0-27)', null=True)),
                ('gad7_score', models.IntegerField(blank=True, help_text='GAD-7 Anxiety Scale (0-21)', null=True)),
                ('pcl5_score', models.IntegerField(blank=True, help_text='PCL-5 PTSD Scale (0-80)', null=True)),
                ('mmse_score', models.IntegerField(blank=True, help_text='MMSE Cognitive Assessment (0-30)', null=True)),
                ('ybocs_score', models.IntegerField(blank=True, help_text='Y-BOCS OCD Scale (0-40)', null=True)),
                ('suicide_risk', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('imminent', 'Imminent')], max_length=20)),
                ('suicide_ideation', models.TextField(blank=True)),
                ('suicide_plan', models.TextField(blank=True)),
                ('suicide_means', models.TextField(blank=True)),
                ('homicide_risk', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('violence_risk', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('self_harm_risk', models.CharField(blank=True, choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20)),
                ('psychiatric_history', models.TextField(blank=True)),
                ('previous_diagnoses', models.TextField(blank=True)),
                ('previous_treatments', models.TextField(blank=True)),
                ('hospitalizations', models.TextField(blank=True)),
                ('family_psychiatric_history', models.TextField(blank=True)),
                ('substance_use_history', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('medication_compliance', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant')], max_length=50)),
                ('medication_side_effects', models.TextField(blank=True)),
                ('living_situation', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('social_support', models.TextField(blank=True)),
                ('stressors', models.TextField(blank=True)),
                ('coping_mechanisms', models.TextField(blank=True)),
                ('primary_diagnosis', models.CharField(blank=True, max_length=200)),
                ('secondary_diagnosis', models.CharField(blank=True, max_length=200)),
                ('provisional_diagnosis', models.CharField(blank=True, max_length=200)),
                ('differential_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('psychotherapy_plan', models.TextField(blank=True)),
                ('medication_plan', models.TextField(blank=True)),
                ('behavioral_interventions', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('response_to_treatment', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('worsening', 'Worsening')], max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.staff')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psychiatric_charts', to='hospital.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatric_charts', to='hospital.patient')),
            ],
            options={
                'ordering': ['-chart_date'],
            },
        ),
    ]
