# Generated by Django 4.2.7 on 2026-01-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1062_add_psychiatric_chart'),
    ]

    operations = [
        # PasswordResetOTP table doesn't exist, so we skip deletion
        # migrations.DeleteModel(
        #     name='PasswordResetOTP',
        # ),
    ]
