# Generated by Django 4.2.7 on 2026-01-03 18:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1063_delete_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GynecologyChart',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chart_date', models.DateField(default=datetime.date.today)),
                ('chief_complaint', models.TextField(blank=True)),
                ('presenting_problem', models.TextField(blank=True)),
                ('menstrual_history', models.TextField(blank=True, help_text='Menstrual cycle details, LMP, regularity')),
                ('obstetric_history', models.TextField(blank=True, help_text='Gravida, Para, abortions, deliveries')),
                ('gynecological_history', models.TextField(blank=True, help_text='Previous gynecological conditions, surgeries')),
                ('contraceptive_history', models.TextField(blank=True, help_text='Current and past contraceptive methods')),
                ('sexual_history', models.TextField(blank=True, help_text='Sexually active, partners, STI history')),
                ('is_pregnant', models.BooleanField(default=False)),
                ('gestational_age_weeks', models.IntegerField(blank=True, null=True)),
                ('edd', models.DateField(blank=True, help_text='Expected Due Date', null=True)),
                ('pregnancy_complications', models.TextField(blank=True)),
                ('prenatal_care', models.TextField(blank=True)),
                ('general_examination', models.TextField(blank=True)),
                ('abdominal_examination', models.TextField(blank=True)),
                ('pelvic_examination', models.TextField(blank=True, help_text='Inspection, speculum, bimanual findings')),
                ('breast_examination', models.TextField(blank=True)),
                ('cervical_examination', models.TextField(blank=True, help_text='Cervix appearance, discharge, lesions')),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pap_smear_result', models.CharField(blank=True, max_length=100)),
                ('pap_smear_date', models.DateField(blank=True, null=True)),
                ('hiv_status', models.CharField(blank=True, choices=[('negative', 'Negative'), ('positive', 'Positive'), ('not_tested', 'Not Tested'), ('declined', 'Declined')], max_length=50)),
                ('hiv_test_date', models.DateField(blank=True, null=True)),
                ('other_investigations', models.TextField(blank=True, help_text='Ultrasound, lab tests, etc.')),
                ('primary_diagnosis', models.CharField(blank=True, max_length=200)),
                ('secondary_diagnosis', models.CharField(blank=True, max_length=200)),
                ('provisional_diagnosis', models.CharField(blank=True, max_length=200)),
                ('differential_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('medications_prescribed', models.TextField(blank=True)),
                ('procedures_planned', models.TextField(blank=True)),
                ('lifestyle_advice', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('progress_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.staff')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gynecology_charts', to='hospital.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gynecology_charts', to='hospital.patient')),
            ],
            options={
                'ordering': ['-chart_date'],
            },
        ),
    ]
