# Generated by Django 4.2.7 on 2026-01-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1064_add_gynecology_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
