# Generated by Django 4.2.7 on 2026-01-09 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1065_delete_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingRoom',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('room_number', models.CharField(help_text='Room identifier (e.g., Room 1, Room 2, CR-01)', max_length=20, unique=True)),
                ('room_name', models.CharField(blank=True, help_text='Optional room name (e.g., Cardiology, Pediatrics)', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', help_text='Current room status', max_length=20)),
                ('capacity', models.IntegerField(default=1, help_text='Number of doctors that can work in this room simultaneously')),
                ('equipment', models.TextField(blank=True, help_text='Available equipment in the room')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the room')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this room is active and available for use')),
            ],
            options={
                'verbose_name': 'Consulting Room',
                'verbose_name_plural': 'Consulting Rooms',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='DoctorRoomAssignment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignment_date', models.DateField(default=django.utils.timezone.now, help_text='Date of assignment')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, help_text='Time when doctor started using the room')),
                ('end_time', models.TimeField(blank=True, help_text='Time when doctor finished using the room', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this assignment is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this assignment')),
            ],
            options={
                'verbose_name': 'Doctor Room Assignment',
                'verbose_name_plural': 'Doctor Room Assignments',
                'ordering': ['-assignment_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(help_text='Available start time')),
                ('end_time', models.TimeField(help_text='Available end time')),
                ('is_available', models.BooleanField(default=True, help_text='Whether room is available during this time')),
            ],
            options={
                'verbose_name': 'Room Availability',
                'verbose_name_plural': 'Room Availability Schedule',
                'ordering': ['room', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchlottracking',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='batchlottracking',
            name='item',
        ),
        migrations.RemoveField(
            model_name='batchlottracking',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='batchlottracking',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='batchrecall',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='batchrecall',
            name='item',
        ),
        migrations.RemoveField(
            model_name='biomedicalengineerreport',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='biomedicalengineerreport',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='biomedicalengineerreport',
            name='maintenance_schedule',
        ),
        migrations.RemoveField(
            model_name='biometricauthenticationlog',
            name='attendance_record',
        ),
        migrations.RemoveField(
            model_name='biometricauthenticationlog',
            name='biometric',
        ),
        migrations.RemoveField(
            model_name='biometricauthenticationlog',
            name='biometric_type',
        ),
        migrations.RemoveField(
            model_name='biometricauthenticationlog',
            name='login_record',
        ),
        migrations.RemoveField(
            model_name='biometricauthenticationlog',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='biometricdevice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='biometricdevice',
            name='supported_biometrics',
        ),
        migrations.RemoveField(
            model_name='biometricenrollmentsession',
            name='biometric_created',
        ),
        migrations.RemoveField(
            model_name='biometricenrollmentsession',
            name='biometric_type',
        ),
        migrations.RemoveField(
            model_name='biometricenrollmentsession',
            name='device',
        ),
        migrations.RemoveField(
            model_name='biometricenrollmentsession',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='biometricenrollmentsession',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='biometricsecurityalert',
            name='auth_log',
        ),
        migrations.RemoveField(
            model_name='biometricsecurityalert',
            name='device',
        ),
        migrations.RemoveField(
            model_name='biometricsecurityalert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='biometricsecurityalert',
            name='staff',
        ),
        migrations.DeleteModel(
            name='BiometricSystemSettings',
        ),
        migrations.RemoveField(
            model_name='calibrationcertificate',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='calibrationcertificate',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='clinicalprocurementplan',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='clinicalprocurementplan',
            name='department',
        ),
        migrations.RemoveField(
            model_name='conflictofinterestdeclaration',
            name='related_suppliers',
        ),
        migrations.RemoveField(
            model_name='conflictofinterestdeclaration',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='conflictofinterestdeclaration',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='departmentalrequisition',
            name='admin_approved_by',
        ),
        migrations.RemoveField(
            model_name='departmentalrequisition',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentalrequisition',
            name='dept_head_approved_by',
        ),
        migrations.RemoveField(
            model_name='departmentalrequisition',
            name='finance_approved_by',
        ),
        migrations.RemoveField(
            model_name='departmentalrequisition',
            name='procurement_validated_by',
        ),
        migrations.RemoveField(
            model_name='departmentalrequisition',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='duplicateorderdetection',
            name='flagged_by',
        ),
        migrations.RemoveField(
            model_name='duplicateorderdetection',
            name='procurement_request',
        ),
        migrations.RemoveField(
            model_name='duplicateorderdetection',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='duplicateorderdetection',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='emergencyprocurement',
            name='authorized_by',
        ),
        migrations.RemoveField(
            model_name='emergencyprocurement',
            name='premium_supplier',
        ),
        migrations.RemoveField(
            model_name='emergencyprocurement',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenanceschedule',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenanceschedule',
            name='maintenance_provider',
        ),
        migrations.RemoveField(
            model_name='equipmentmaintenanceschedule',
            name='service_contract',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednoteenhanced',
            name='inspected_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednoteenhanced',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednoteenhanced',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceivednoteenhanced',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='grnlineenhanced',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='grnlineenhanced',
            name='po_line',
        ),
        migrations.RemoveField(
            model_name='inventoryintegration',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='inventoryintegration',
            name='procurement_request',
        ),
        migrations.RemoveField(
            model_name='inventoryintegration',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='procurementaudittrail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='procurementplanitem',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='procurementreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderenhanced',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderenhanced',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='purchaseorderenhanced',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorderenhanced',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineenhanced',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='rfp',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='rfq',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='quotationline',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='regulatorycompliance',
            name='item',
        ),
        migrations.RemoveField(
            model_name='regulatorycompliance',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='regulatorycompliance',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='requestforproposal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requestforquotation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='requisition',
        ),
        migrations.AlterUniqueTogether(
            name='staffbiometric',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffbiometric',
            name='biometric_type',
        ),
        migrations.RemoveField(
            model_name='staffbiometric',
            name='enrolled_by',
        ),
        migrations.RemoveField(
            model_name='staffbiometric',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='stocklevelalert',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocklevelalert',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='suppliercontract',
            name='signed_by',
        ),
        migrations.RemoveField(
            model_name='suppliercontract',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='suppliercreditmanagement',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierdocument',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplierdocument',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='supplierqualification',
            name='qualified_by',
        ),
        migrations.RemoveField(
            model_name='supplierqualification',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='tenderevaluation',
            name='evaluated_by',
        ),
        migrations.RemoveField(
            model_name='tenderevaluation',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='tenderevaluation',
            name='rfp',
        ),
        migrations.RemoveField(
            model_name='threewaymatching',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='threewaymatching',
            name='payment_approved_by',
        ),
        migrations.RemoveField(
            model_name='threewaymatching',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='whistleblowerreport',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='whistleblowerreport',
            name='related_staff',
        ),
        migrations.RemoveField(
            model_name='whistleblowerreport',
            name='related_supplier',
        ),
        migrations.CreateModel(
            name='CorporateReceivableEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Corporate Receivable Entry',
                'verbose_name_plural': 'Corporate Receivable Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hospital.insurancereceivableentry',),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password Login'), ('manual', 'Manual Entry')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider', 'appointment_date', 'status'], name='hospital_ap_provide_9863a5_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='hospital_ap_appoint_82af2e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name', 'date_of_birth'], name='patient_name_dob_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name', 'phone_number'], name='patient_name_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patient_email_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='patient_national_id_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patient_phone_idx'),
        ),
        migrations.DeleteModel(
            name='BatchLotTracking',
        ),
        migrations.DeleteModel(
            name='BatchRecall',
        ),
        migrations.DeleteModel(
            name='BiomedicalEngineerReport',
        ),
        migrations.DeleteModel(
            name='BiometricAuthenticationLog',
        ),
        migrations.DeleteModel(
            name='BiometricDevice',
        ),
        migrations.DeleteModel(
            name='BiometricEnrollmentSession',
        ),
        migrations.DeleteModel(
            name='BiometricSecurityAlert',
        ),
        migrations.DeleteModel(
            name='BiometricType',
        ),
        migrations.DeleteModel(
            name='CalibrationCertificate',
        ),
        migrations.DeleteModel(
            name='ClinicalProcurementPlan',
        ),
        migrations.DeleteModel(
            name='ConflictOfInterestDeclaration',
        ),
        migrations.DeleteModel(
            name='DepartmentalRequisition',
        ),
        migrations.DeleteModel(
            name='DuplicateOrderDetection',
        ),
        migrations.DeleteModel(
            name='EmergencyProcurement',
        ),
        migrations.DeleteModel(
            name='EquipmentMaintenanceSchedule',
        ),
        migrations.DeleteModel(
            name='GoodsReceivedNoteEnhanced',
        ),
        migrations.DeleteModel(
            name='GRNLineEnhanced',
        ),
        migrations.DeleteModel(
            name='InventoryIntegration',
        ),
        migrations.DeleteModel(
            name='ProcurementAuditTrail',
        ),
        migrations.DeleteModel(
            name='ProcurementPlanItem',
        ),
        migrations.DeleteModel(
            name='ProcurementReport',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderEnhanced',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderLineEnhanced',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationLine',
        ),
        migrations.DeleteModel(
            name='RegulatoryCompliance',
        ),
        migrations.DeleteModel(
            name='RequestForProposal',
        ),
        migrations.DeleteModel(
            name='RequestForQuotation',
        ),
        migrations.DeleteModel(
            name='RequisitionItem',
        ),
        migrations.DeleteModel(
            name='StaffBiometric',
        ),
        migrations.DeleteModel(
            name='StockLevelAlert',
        ),
        migrations.DeleteModel(
            name='SupplierContract',
        ),
        migrations.DeleteModel(
            name='SupplierCreditManagement',
        ),
        migrations.DeleteModel(
            name='SupplierDocument',
        ),
        migrations.DeleteModel(
            name='SupplierQualification',
        ),
        migrations.DeleteModel(
            name='TenderEvaluation',
        ),
        migrations.DeleteModel(
            name='ThreeWayMatching',
        ),
        migrations.DeleteModel(
            name='WhistleblowerReport',
        ),
        migrations.AddField(
            model_name='roomavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='hospital.consultingroom'),
        ),
        migrations.AddField(
            model_name='doctorroomassignment',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor assigned to this room', limit_choices_to={'groups__name': 'Doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorroomassignment',
            name='room',
            field=models.ForeignKey(help_text='Consulting room assigned', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='hospital.consultingroom'),
        ),
        migrations.AddField(
            model_name='consultingroom',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Primary department using this room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_rooms', to='hospital.department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consulting_room',
            field=models.ForeignKey(blank=True, help_text='Consulting room assigned for this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='hospital.consultingroom'),
        ),
        migrations.AlterUniqueTogether(
            name='roomavailability',
            unique_together={('room', 'day_of_week', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='doctorroomassignment',
            index=models.Index(fields=['assignment_date', 'is_active'], name='hospital_do_assignm_9afba4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorroomassignment',
            index=models.Index(fields=['doctor', 'assignment_date', 'is_active'], name='hospital_do_doctor__b18c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorroomassignment',
            index=models.Index(fields=['room', 'assignment_date', 'is_active'], name='hospital_do_room_id_e61ed6_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorroomassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('doctor', 'assignment_date'), name='unique_active_doctor_assignment_per_day'),
        ),
        migrations.AddIndex(
            model_name='consultingroom',
            index=models.Index(fields=['status', 'is_active'], name='hospital_co_status_13f8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='consultingroom',
            index=models.Index(fields=['room_number'], name='hospital_co_room_nu_3b051b_idx'),
        ),
    ]
