# Generated by Django 4.2.7 on 2026-01-15 10:29

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1066_consultingroom_doctorroomassignment_roomavailability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingCatalog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Procedure code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Imaging study name', max_length=200)),
                ('modality', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammography', 'Mammography'), ('fluoroscopy', 'Fluoroscopy'), ('nuclear', 'Nuclear Medicine'), ('pet', 'PET Scan'), ('dexa', 'DEXA Scan')], default='xray', max_length=20)),
                ('body_part', models.CharField(blank=True, help_text='Body part or region', max_length=100)),
                ('study_type', models.CharField(blank=True, help_text='Type of study', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price for this imaging study', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Description of the imaging study')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this study is available for ordering')),
            ],
            options={
                'verbose_name_plural': 'Imaging Catalog',
                'ordering': ['modality', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='patient',
            name='uniq_patient_name_phone_dob_active',
        ),
    ]
