# Generated by Django 4.2.7 on 2026-01-15 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1067_add_imaging_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingRelease',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('release_status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('ready_for_release', 'Ready for Release'), ('released', 'Released to Patient'), ('emailed', 'Emailed to Patient')], default='pending_payment', max_length=30)),
                ('released_to', models.CharField(blank=True, help_text='Name of person who collected', max_length=200)),
                ('released_to_relationship', models.CharField(blank=True, help_text='Relationship to patient', max_length=100)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, help_text='e.g., National ID, Passport', max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('delivery_method', models.CharField(choices=[('in_person', 'Collected in Person'), ('email', 'Emailed'), ('proxy', 'Collected by Proxy')], default='in_person', max_length=20)),
                ('release_notes', models.TextField(blank=True)),
                ('sent_to_cashier_at', models.DateTimeField(blank=True, null=True)),
                ('imaging_study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_record', to='hospital.imagingstudy')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_releases', to='hospital.patient')),
                ('payment_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.paymentreceipt')),
                ('payment_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_imaging_payments', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_imaging_studies', to=settings.AUTH_USER_MODEL)),
                ('sent_to_cashier_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_cashier_tickets_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
