# Generated by Django 4.2.7 on 2026-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1068_imagingrelease'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pharmacystock',
            index=models.Index(fields=['drug_id', 'is_deleted'], name='hospital_ph_drug_id_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystock',
            index=models.Index(fields=['is_deleted', 'quantity_on_hand'], name='hospital_ph_is_del_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['is_active', 'is_deleted', 'category'], name='hospital_dr_is_act_del_idx'),
        ),
    ]
