# Generated by Django 4.2.7 on 2026-01-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1069_add_pharmacy_stock_indexes'),
    ]

    operations = [
        # Add unique constraint for medical records (prevent duplicates)
        # Only applies to non-deleted records
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX IF NOT EXISTS unique_medical_record_active
                ON hospital_medicalrecord (patient_id, encounter_id, record_type, title)
                WHERE is_deleted = FALSE;
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS unique_medical_record_active;
            """
        ),
    ]
