# Generated by Django 4.2.7 on 2026-01-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1070_add_medical_record_unique_constraint'),
    ]

    operations = [
        # Add index for ClinicalNote to prevent duplicates
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['encounter', 'note_type', 'is_deleted'], name='hospital_cl_encount_f78a94_idx'),
        ),
    ]
