# Generated by Django 4.2.7 on 2026-01-19 04:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1072_restore_pharmacy_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCatalog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(help_text='Procedure code (e.g., PROC001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Procedure name', max_length=200)),
                ('category', models.CharField(choices=[('minor_surgery', 'Minor Surgery'), ('major_surgery', 'Major Surgery'), ('dental', 'Dental Procedure'), ('ophthalmic', 'Ophthalmic Procedure'), ('endoscopy', 'Endoscopy'), ('biopsy', 'Biopsy'), ('injection', 'Injection'), ('wound_care', 'Wound Care'), ('catheterization', 'Catheterization'), ('dressing', 'Dressing Change'), ('suturing', 'Suturing'), ('incision_drainage', 'Incision & Drainage'), ('other', 'Other Procedure')], default='other', help_text='Procedure category', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of the procedure')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price for this procedure', max_digits=10)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30, help_text='Estimated duration in minutes')),
                ('requires_anesthesia', models.BooleanField(default=False, help_text='Whether procedure requires anesthesia')),
                ('requires_theatre', models.BooleanField(default=False, help_text='Whether procedure requires operating theatre')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this procedure is available for ordering')),
            ],
            options={
                'verbose_name': 'Procedure Catalog',
                'verbose_name_plural': 'Procedure Catalog',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='procedurecatalog',
            index=models.Index(fields=['category', 'is_active'], name='hospital_pr_categor_a20247_idx'),
        ),
        migrations.AddIndex(
            model_name='procedurecatalog',
            index=models.Index(fields=['code'], name='hospital_pr_code_6e7dce_idx'),
        ),
    ]
