# Generated by Django 4.2.7 on 2026-01-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1073_add_procedure_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecatalog',
            name='cash_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cash/Private patient price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='corporate_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Corporate client price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='procedurecatalog',
            name='insurance_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insurance/NHIS price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='procedurecatalog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default/Base price for this procedure (cash price)', max_digits=10),
        ),
    ]
