# Generated by Django 4.2.7 on 2026-01-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1074_add_procedure_multi_tier_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='expected_completion_datetime',
            field=models.DateTimeField(blank=True, help_text='Expected date and time when this test will be completed (for long-duration tests)', null=True),
        ),
    ]
