# Generated by Django 4.2.7 on 2026-01-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1075_add_labresult_expected_completion_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('account_personnel', 'Account Personnel'), ('account_officer', 'Account Officer'), ('inventory_manager', 'Inventory Manager'), ('store_manager', 'Store Manager'), ('procurement_officer', 'Procurement Officer'), ('marketer', 'Marketer'), ('business_development', 'Business Development')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staffperformancesnapshot',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('radiologist', 'Radiologist'), ('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('account_personnel', 'Account Personnel'), ('account_officer', 'Account Officer'), ('inventory_manager', 'Inventory Manager'), ('store_manager', 'Store Manager'), ('procurement_officer', 'Procurement Officer'), ('marketer', 'Marketer'), ('business_development', 'Business Development')], max_length=30),
        ),
    ]
