# Generated by Django 4.2.7 on 2026-01-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1076_add_marketer_profession'),
    ]

    operations = [
        # Remove erroneous RemoveIndex operations - they reference non-existent indexes
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('call_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_type', models.CharField(choices=[('cold_call', 'Cold Call'), ('warm_call', 'Warm Call'), ('follow_up', 'Follow-up Call'), ('consultation', 'Consultation Call'), ('partnership', 'Partnership Discussion'), ('customer_service', 'Customer Service Call'), ('other', 'Other')], default='cold_call', max_length=50)),
                ('call_duration_minutes', models.PositiveIntegerField(default=0, help_text='Call duration in minutes')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('contact_title', models.CharField(blank=True, max_length=100)),
                ('call_outcome', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('follow_up_scheduled', 'Follow-up Scheduled'), ('meeting_scheduled', 'Meeting Scheduled'), ('quote_requested', 'Quote Requested'), ('sale_closed', 'Sale Closed'), ('objection_raised', 'Objection Raised'), ('callback_requested', 'Callback Requested'), ('no_answer', 'No Answer'), ('voicemail', 'Voicemail Left'), ('wrong_number', 'Wrong Number'), ('other', 'Other')], max_length=50)),
                ('call_summary', models.TextField(help_text='Summary of the call conversation')),
                ('key_points', models.TextField(blank=True, help_text='Key discussion points')),
                ('objections_raised', models.TextField(blank=True, help_text='Any objections or concerns raised')),
                ('next_steps', models.TextField(blank=True, help_text='Agreed next steps')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('potential_value', models.DecimalField(blank=True, decimal_places=2, help_text='Potential deal value', max_digits=12, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Actual closed value', max_digits=12, null=True)),
                ('service_interest', models.CharField(blank=True, help_text="Services they're interested in", max_length=200)),
                ('relationship_stage', models.CharField(choices=[('new', 'New Contact'), ('prospect', 'Prospect'), ('qualified', 'Qualified Lead'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='new', max_length=50)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not shared with client)')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=500)),
            ],
            options={
                'verbose_name': 'Call Report',
                'verbose_name_plural': 'Call Reports',
                'ordering': ['-call_date', '-created'],
            },
        ),
        migrations.AddField(
            model_name='callreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_call_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callreport',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_reports', to='hospital.marketingcampaign'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_reports', to='hospital.marketingobjective'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_reports', to='hospital.corporatepartnership'),
        ),
        migrations.AddField(
            model_name='callreport',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['call_date', 'reported_by'], name='hospital_ca_call_da_85b9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['contact_phone'], name='hospital_ca_contact_290fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['call_outcome'], name='hospital_ca_call_ou_5fcfe6_idx'),
        ),
        migrations.AddIndex(
            model_name='callreport',
            index=models.Index(fields=['follow_up_required', 'follow_up_date'], name='hospital_ca_follow__c221d7_idx'),
        ),
    ]
