# Generated by Django 4.2.7 on 2026-01-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1077_add_call_report_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'status', 'is_deleted'], name='hospital_en_patient_fd08f8_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status', 'is_deleted'], name='hospital_en_status_87b9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['provider', 'status', 'is_deleted'], name='hospital_en_provide_1573c7_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['started_at'], name='hospital_en_started_200089_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['is_active', 'is_deleted'], name='hospital_la_is_acti_8ecaa1_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['name'], name='hospital_la_name_1f306a_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['code'], name='hospital_la_code_38367c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['encounter', 'order_type', 'is_deleted'], name='hospital_or_encount_1cc637_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['encounter', 'status', 'is_deleted'], name='hospital_or_encount_92ac45_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status', 'is_deleted'], name='hospital_or_order_t_23931d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['requested_at'], name='hospital_or_request_e2bc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['order', 'drug', 'is_deleted'], name='hospital_pr_order_i_3bc51c_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['order', 'is_deleted'], name='hospital_pr_order_i_4b86a8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_by', 'is_deleted'], name='hospital_pr_prescri_721941_idx'),
        ),
    ]
