# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1078_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingcatalog',
            name='corporate_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Corporate client price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='imagingcatalog',
            name='insurance_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insurance/NHIS price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagingcatalog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cash/private patient price', max_digits=10),
        ),
    ]
