# Generated by Django 4.2.7 on 2026-01-22 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1079_imaging_catalog_corporate_insurance_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureConsumable',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('default_quantity', models.DecimalField(decimal_places=2, default=1.0, help_text='Default quantity for this consumable in this procedure', max_digits=10)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this consumable is required for the procedure')),
                ('notes', models.TextField(blank=True, help_text='Notes about usage of this consumable in the procedure')),
            ],
            options={
                'verbose_name': 'Procedure Consumable',
                'verbose_name_plural': 'Procedure Consumables',
                'ordering': ['procedure', 'service_code'],
            },
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('specialist', 'Special Consultation'), ('inpatient', 'Inpatient'), ('er', 'Emergency'), ('surgery', 'Surgery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='imagingcatalog',
            name='modality',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammography', 'Mammography'), ('fluoroscopy', 'Fluoroscopy'), ('nuclear', 'Nuclear Medicine'), ('pet', 'PET Scan'), ('dexa', 'DEXA Scan'), ('ecg', 'ECG'), ('other', 'Other')], default='xray', max_length=20),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='modality',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('mammography', 'Mammography'), ('fluoroscopy', 'Fluoroscopy'), ('nuclear', 'Nuclear Medicine'), ('pet', 'PET Scan'), ('dexa', 'DEXA Scan'), ('ecg', 'ECG'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='encounter_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('specialist', 'Special Consultation'), ('inpatient', 'Inpatient'), ('er', 'Emergency'), ('surgery', 'Surgery')], max_length=20),
        ),
        migrations.AddField(
            model_name='procedureconsumable',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='hospital.procedurecatalog'),
        ),
        migrations.AddField(
            model_name='procedureconsumable',
            name='service_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_usages', to='hospital.servicecode'),
        ),
        migrations.AlterUniqueTogether(
            name='procedureconsumable',
            unique_together={('procedure', 'service_code')},
        ),
    ]
