# Generated by Django 4.2.7 on 2026-01-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1080_add_procedure_consumable_model'),
    ]

    operations = [
        # RemoveIndex ops removed: indexes may not exist on all DBs (1071/1072 vary).
        # Only adding new indexes below so migration always succeeds.
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['patient', 'is_deleted'], name='diag_patient_del_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['encounter', 'is_deleted'], name='diag_encounter_del_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['diagnosis_date'], name='diag_date_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['patient', 'is_deleted'], name='proc_patient_del_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['encounter', 'is_deleted'], name='proc_encounter_del_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['procedure_date'], name='proc_date_idx'),
        ),
        migrations.AddIndex(
            model_name='triage',
            index=models.Index(fields=['encounter', 'is_deleted'], name='triage_enc_del_idx'),
        ),
        migrations.AddIndex(
            model_name='triage',
            index=models.Index(fields=['triage_level', 'is_deleted'], name='triage_level_del_idx'),
        ),
        migrations.AddIndex(
            model_name='triage',
            index=models.Index(fields=['triage_time'], name='triage_time_idx'),
        ),
    ]
