# Generated by Django 4.2.7 on 2026-01-30 05:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1081_add_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningCheckTemplate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='e.g. Basic Pre-employment, School Entry, Executive Check', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code e.g. PREEMP-BASIC', max_length=50, unique=True)),
                ('category', models.CharField(choices=[('pre_employment', 'Pre-employment (Company)'), ('pre_admission', 'Pre-admission (School)')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='When to use this template')),
                ('physical_exam_sections', models.JSONField(blank=True, default=list, help_text='Physical exam sections to include in the report (list of strings)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order in list')),
                ('imaging_items', models.ManyToManyField(blank=True, help_text='Imaging studies to order when this template is applied', related_name='screening_templates', to='hospital.imagingcatalog')),
                ('lab_tests', models.ManyToManyField(blank=True, help_text='Lab tests to order when this template is applied', related_name='screening_templates', to='hospital.labtest')),
            ],
            options={
                'verbose_name': 'Screening check template',
                'verbose_name_plural': 'Screening check templates',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('specialist', 'Special Consultation'), ('inpatient', 'Inpatient'), ('er', 'Emergency'), ('surgery', 'Surgery'), ('pre_employment', 'Pre-employment (Company)'), ('pre_admission', 'Pre-admission (School)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='encounter_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('specialist', 'Special Consultation'), ('inpatient', 'Inpatient'), ('er', 'Emergency'), ('surgery', 'Surgery'), ('pre_employment', 'Pre-employment (Company)'), ('pre_admission', 'Pre-admission (School)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('overall_result', models.CharField(choices=[('fit', 'Fit'), ('unfit', 'Unfit'), ('fit_with_restrictions', 'Fit with restrictions'), ('pending', 'Pending review')], default='pending', max_length=30)),
                ('result_notes', models.TextField(blank=True, help_text='Explanation for fit/unfit or restrictions')),
                ('lab_summary', models.TextField(blank=True, help_text='Summary of laboratory findings')),
                ('imaging_summary', models.TextField(blank=True, help_text='Summary of imaging/radiology findings')),
                ('physical_exam_notes', models.TextField(blank=True, help_text='Physical examination findings')),
                ('general_remarks', models.TextField(blank=True, help_text='Any other remarks for employer/school')),
                ('recommended_actions', models.TextField(blank=True, help_text='Follow-up or recommendations')),
                ('requesting_organization', models.CharField(blank=True, max_length=255)),
                ('requesting_contact', models.CharField(blank=True, max_length=255)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_reports_approved', to='hospital.staff')),
                ('encounter', models.OneToOneField(help_text='The encounter this report belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='screening_report', to='hospital.encounter')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_reports_authored', to='hospital.staff')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='hospital.screeningchecktemplate')),
            ],
            options={
                'verbose_name': 'Screening report',
                'verbose_name_plural': 'Screening reports',
                'ordering': ['-reported_at', '-created'],
            },
        ),
    ]
