# Generated by Django 4.2.7 on 2026-03-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1090_receipt_80_72_1_x_810_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydispensing',
            name='substitute_drug',
            field=models.ForeignKey(blank=True, help_text='If set, dispense this drug instead of the prescribed drug', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_substitutions', to='hospital.drug'),
        ),
    ]
