# Generated by Django 4.2.7 on 2026-03-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1092_add_invoiceline_waiver_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinpharmacysale',
            name='payer',
            field=models.ForeignKey(blank=True, help_text='Cash, Corporate, or Insurance - who will be billed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walkin_pharmacy_sales', to='hospital.payer'),
        ),
    ]
