# Generated by Django 4.2.7 on 2026-03-11 08:51

from django.db import migrations, models
import hospital.models_advanced


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1095_add_labresult_attachment_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingimage',
            name='image',
            field=models.FileField(help_text='Upload medical imaging picture (JPG, PNG, DICOM)', upload_to=hospital.models_advanced._imaging_image_upload_path),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='service_type',
            field=models.CharField(blank=True, choices=[('lab', 'Laboratory Test'), ('pharmacy', 'Pharmacy/Medication'), ('pharmacy_prescription', 'Pharmacy Prescription'), ('pharmacy_walkin', 'Walk-in Pharmacy Sale'), ('medication', 'Medication Sale'), ('imaging', 'Imaging/Radiology'), ('imaging_study', 'Imaging Study'), ('consultation', 'Consultation'), ('admission', 'Admission'), ('detainment', 'Detainment'), ('procedure', 'Procedure'), ('combined', 'Combined Services'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
