# Generated by Django 4.2.7 on 2026-03-13 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1098_servicecode_code_max_length_80'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinpharmacysale',
            name='waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkinpharmacysale',
            name='waived_by',
            field=models.ForeignKey(blank=True, help_text='User who waived this sale (accountant only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_prescribe_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walkinpharmacysale',
            name='waiver_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
