# Generated by Django 4.2.7 on 2026-03-13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1099_add_prescribe_sale_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinpharmacysaleitem',
            name='waived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walkinpharmacysaleitem',
            name='waived_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='waived_prescribe_sale_items',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='walkinpharmacysaleitem',
            name='waiver_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
