# Generated by Django 4.2.7 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1100_walkinpharmacysaleitem_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='billing_closed_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When set, no new invoice lines may be added for this encounter (e.g. after discharge).',
                null=True,
            ),
        ),
    ]
