# Generated by Django 4.2.7 on 2026-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1102_invoice_one_per_encounter_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
