# Generated by Django 4.2.7 on 2026-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1107_backfill_insurancereceivableentry_entry_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_code'], 'verbose_name': 'Chart of Accounts (Account)', 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='walkinpharmacysaleitem',
            options={'ordering': ['created'], 'verbose_name': 'Prescribe Sale Item', 'verbose_name_plural': 'Prescribe Sale Items'},
        ),
        migrations.AddField(
            model_name='accountingpayroll',
            name='import_source_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='accountingpayroll',
            name='period_label',
            field=models.CharField(blank=True, help_text='Optional label shown in UI (e.g. January 2026 — Salary RMC)', max_length=120),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='other_deductions_detail',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='overtime_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='paye_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='pension_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='ssnit_employee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accountingpayrollentry',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('specialist', 'Special Consultation'), ('antenatal', 'Antenatal'), ('gynae', 'Gynae / Special'), ('inpatient', 'Inpatient'), ('er', 'Emergency'), ('surgery', 'Surgery'), ('pre_employment', 'Pre-employment (Company)'), ('pre_admission', 'Pre-admission (School)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientdocument',
            name='document_type',
            field=models.CharField(choices=[('lab_report', 'Laboratory Report'), ('imaging_report', 'Imaging Report'), ('external_report', 'External Report / Scan (from other facility)'), ('prescription', 'Prescription'), ('consent_form', 'Consent Form'), ('referral_letter', 'Referral Letter'), ('discharge_summary', 'Discharge Summary'), ('operative_note', 'Operative Note'), ('pathology_report', 'Pathology Report'), ('other', 'Other Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('insurance', 'Insurance'), ('deposit', 'Deposit (from patient account)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('insurance', 'Insurance'), ('deposit', 'Deposit (from patient account)')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='encounter_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('specialist', 'Special Consultation'), ('antenatal', 'Antenatal'), ('gynae', 'Gynae / Special'), ('inpatient', 'Inpatient'), ('er', 'Emergency'), ('surgery', 'Surgery'), ('pre_employment', 'Pre-employment (Company)'), ('pre_admission', 'Pre-admission (School)')], max_length=20),
        ),
    ]
