# Generated by Django 4.2.7 on 2026-03-20 13:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1109_accountingpayrollentry_rmc_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingpayroll',
            name='deduction_apply_percentages',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'When on, each staff line SSF (employee), PF (employee), PAYE, and optional other deduction '
                    'are computed from the rates below whenever a line is saved or Excel is imported.'
                ),
            ),
        ),
        migrations.AddField(
            model_name='accountingpayroll',
            name='deduction_other_deduction_pct',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                help_text='Optional extra deduction as % of gross earnings (maps to other deductions).',
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name='accountingpayroll',
            name='deduction_paye_pct',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                help_text=(
                    'Flat % for PAYE when Taxable income is set; if that is zero, estimated on '
                    '(gross earnings - personal relief). Set 0 to enter PAYE manually.'
                ),
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name='accountingpayroll',
            name='deduction_pension_employee_pct',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('5.0'),
                help_text=(
                    'Provident fund (employee): % of basic salary (falls back to gross earnings if basic is zero).'
                ),
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name='accountingpayroll',
            name='deduction_ssnit_employee_pct',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('5.5'),
                help_text='SSF employee: % of basic salary (falls back to gross earnings if basic is zero).',
                max_digits=6,
            ),
        ),
    ]
