# Generated by Django 4.2.7 on 2026-03-25 12:22
# Trimmed to only create PharmacyStockDeductionLog (no unrelated index/field churn).

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1111_pharmacystock_initial_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyStockDeductionLog',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('dispense_history', 'Dispense history row'), ('pharmacy_dispensing', 'Pharmacy dispensing record (API / no history)'), ('walkin_sale_item', 'Walk-in prescribe sale line')], db_index=True, max_length=32)),
                ('source_id', models.UUIDField(db_index=True, help_text='PK of the history / dispensing / sale item row')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_deduction_logs', to='hospital.drug')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='pharmacystockdeductionlog',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='uniq_pharmacy_stock_deduction_source'),
        ),
    ]
