# Generated by Django 4.2.7 on 2026-03-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1112_pharmacy_stock_deduction_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='diagnosis_icd10',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
